### ISSUE TITLE
Dev.to production IP de-anonymization

### ISSUE THREAD

**Issue by marataziat** [thepracticaldev/dev.to#1019]
**Describe the bug**
Using RSS feed and [webhook.site](https://webhook.site/) you can de-anonymize dev.to IP! Here an example: https://webhook.site/#/e3ad339a-6a09-4404-9c53-9f2558f661f7/fb261a09-aeed-47ff-8842-4e3b175954e7/1

Host | 54.162.154.53

https://who.is/whois-ip/ip-address/54.162.154.53
https://check-host.net/ip-info?host=dev.to

**Additional context**
Use something like a proxy

**Comment by pkfrank** [comment]
Hey @marataziat thanks for this issue.  Can you expand a bit on the ramifications of the IP being de-anonymized, and some potential solutions we should look at if we wanted to implement a proxy or otherwise hide the IP?

**Comment by marataziat** [comment]
You are using fastly as anti-DDOS service. So if an attacker wants to DDOS your site, fastly will filter all botnet traffic. But if an attacker knows your production IP your server can be DDOS easily!

**Comment by benhalpern** [comment]
Hey @marataziat I _believe_ that this is not necessarily an issue because we host with Heroku who rotates IP addresses on us anyway, so we couldn't even have our own dedicated IP unless we went out of our way to do so via a proxy.

But if I'm misguided here, I'd love some any further clarification you'd have on the matter.
