### ISSUE TITLE
Add a way to downvote articles

### ISSUE THREAD

**Issue by dertuxmalwieder** [thepracticaldev/dev.to#1084]
As solving #1058 is taking a long time and DEV is now spammed with both HTTP and Abu Dhabi spam trash, it *might* be a decent idea to adopt the downvoting system from Hacker News where everyone can give an article a "minus" and it will be faded out once it has enough "minuses".

I know that there is a "report abuse" function, but currently I have to fight reCAPTCHA to do so (which can be annoying when there are ten spam articles in a row, especially on mobile...) and I am increasingly less willing to do so. Furthermore, the automatic "hearts" make it notably harder to flag an article as spam, at least for the community. And since you don't stop doing that, I need an alternative.

**Comment by Link2Twenty** [comment]
Alternatively, get some post moderators from the community that can remove spam as they see it. Or have some sort of rep system (like StackOverflow) allow users with enough rep to hide post for manual checking.

**Comment by Some-Dood** [comment]
I agree with the fight against spam, but I don't think a downvote feature is the best solution. It just doesn't sound like "dev.to" to me. Adding a downvote button to the site is like adding a **full** implementation of classes in JavaScript (from property visibility to classical inheritance). It just doesn't sound "right". It sounds like a very foreign feature. It _can_ work, though. As a counter-suggestion, I propose a reCAPTCHA-like prompt every time a post is to be published.

For example, in the v2 Editor, there should be a prompt that only allows you to publish a post if the anti-bot/anti-spam check passes. The "Publish" button would be faded and unclickable until the user has been verified.

For the v1 Editor, I'm not quite sure how one could implement this. Perhaps make an algorithm that detects if the `published` field in the front matter has been changed to `true`? Then if it is `true`, prompt the user for a reCAPTCHA bot checker?

For sure, requiring verification before a post is published will lessen the number of spam posts. It will not, however, prevent spam posts; it will only lessen the frequency of such, which I believe is notable progress nonetheless.

**Comment by def14nt** [comment]
@Some-Dood Anti-spam bot? That sounds like a lot of API hell. 

I'm looking at this, and it makes no sense.
> Adding a downvote button to the site is like adding a full implementation of classes in JavaScript (from property visibility to classical inheritance).

How is it that difficult? (and classes exist in JavaScript)

**Comment by Some-Dood** [comment]
@def14nt I was making an analogy on how the two don't traditionally go together. JavaScript started out as a language that was never supposed to have classes, but now it does. What I mean by comparing them is that adding a downvote button does not reflect the original purpose of DEV.to, at least for me; similar to how adding classes to JavaScript does not reflect its original purpose.

**Comment by def14nt** [comment]
@Some-Dood How do you know it's original purpose? You aren't coming up as a member of the `dev.to` organization.

**Comment by Some-Dood** [comment]
@def14nt I apologize for the lack of clarity. Let me try to explain better without bad analogies.

Admittedly, no. I am not part of the organization. It's just a gut feeling I have. I don't know what their original purpose is given the fact that I'm relatively new to the DEV community.

However, as I have visited the site more over the past few weeks, it has become apparent to me what DEV.to truly is. At least for me, DEV.to is a vibrant community that prides itself in its kindness, warm welcomes, and positivity (aside from its great and diverse selection of user-generated articles). Simply put, the community is not _just like any other community out there_. It is a pretty special one that does its best to avoid toxicity.

Since the community prides itself in the aforementioned qualities, adding a downvote button seems contradictory to my observations. Though I agree with having a way to mitigate spam posts, a downvote button has a negative connotation to it. It doesn't align with the qualities of the DEV community. It sounds too much like Stack Overflow if you'd ask me.

Anyway, what I'm trying to say is that a downvote button deviates from the "original purpose" of the site (based on my observations). I'm sure you would agree that adding a downvote button doesn't align with the principles of the DEV community, where friendliness is the top priority. I hope you see my point here now. Sorry for the terrible analogies that added no value to my argument.

**Comment by jessleenyc** [comment]
Hi all, sorry for the delay in response here. We have community moderators that help us surface inappropriate/low quality content. We then have an internal process on deciding whether or not to take any action. We'll also continue improving everyone's feeds to help surface articles they'd be interested in. Going to close this issue since we won't be implementing a public downvoting system.
