### ISSUE TITLE
Limit who can create post

### ISSUE THREAD

**Issue by Puritanic** [thepracticaldev/dev.to#1177]
**Is your feature request related to a problem? Please describe.**
In the light of the recent spam/ad posts flood maybe you should limit what the new users can do somehow. 

**Describe the solution you'd like**
A few ideas:
- user can't create a post if his account is not older than a week
- user can't create a post if he doesn't have posted comments, with at least a few likes
- user can't create posts with links in the title
...

I would like to hear if you have any ideas to handle this or if you have planned something like this.

**Additional context**
The more steps bot/spam accounts have to take to post their spam the less motivated will they be to actually do it, at least it's what I think. There is a problem tho, if they can't create posts they'll maybe go for the comments and write their spam there 😕
From what I can see the most of the spam content comes from the Twitter accounts (and twitter is famous for bots) and newly created Github accounts, but I have no idea if this can be used somehow to limit those users 😕

**Comment by jessleenyc** [comment]
Hey @Puritanic, sorry for the delay here. We've continued to make our feeds smarter so spam won't show up as likely. We've also made it easier for community moderators to flag inappropriate posts for us so they get removed more quickly. Spam links in titles are also detected early. I'm going to close this issue because the direction we're taking to handle spam doesn't include limiting who can create a post at the moment.
