### ISSUE TITLE
Some article exist in index but doesn't exist on show

### ISSUE THREAD

**Issue by faqndo97** [thepracticaldev/dev.to#1178]
**Describe the bug**
For some weird reason when I go to the index, I can show an specific article, but when I want enter to read it, I can't, the site give me an 404.

**To Reproduce**
https://dev.to/sahilrajput/useful-javascript-resources-for-programmers-kdm

**Expected behavior**
Should open fine the article.

**Screenshots**
![giphy](https://user-images.githubusercontent.com/16840674/48912751-2e3a3e80-ee55-11e8-93d8-60bb2a55d4bd.gif)

**Desktop:**

- OS: macOS 10.4
- Browser: Chrome
- Version: 70.0.3538.102

**Comment by benhalpern** [comment]
Looks like it's an issue de-indexing after author unpublishes. Ran script to fix the current issue. Will look into the problem further. Thanks for the heads up.

**Comment by faqndo97** [comment]
@benhalpern ok, you're welcome 💪

**Comment by maestromac** [comment]
Hey thanks for this issue @faqndo97 . We are closing this issue because it is very similar to #1102 and both will be resolved together.

**Comment by Zhao-Andy** [comment]
@wolfhoundjesse, we have a `comments_blob` attribute that is searchable. It's a text column that grabs 2200 characters from the comments in the article. The `(comments)` at the end of the search query is meant to represent that, but I can see how it's confusing since there's the open parenthesis in `(fallout...`.

Here's the comment on that thread: https://dev.to/_morgan_adams_/comment/4f2c
