### ISSUE TITLE
GitHub logins sometimes fail authentication

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#1223]
There have been a couple of cases where a user tries to sign in via GitHub, and they run into an error that says "Invalid credentials". Most of the time it's because something went wrong and retrying usually works. So far we've had two reports where someone tries to log in, and they repeatedly hit the "invalid credentials" error.

For the more stubborn cases, I've tried removing their GitHub identity and having them authenticate again. This has worked sometimes, but when it doesn't, I suspect there's something else that's becoming invalid.

@dance2die has experienced this issue with Chrome specifically. Logging in with GitHub on Firefox and Safari works.

**Comment by dance2die** [comment]
Thanks, Andy.

The problem still persists in my case on all browsers now (on PC, laptop [windows 10 for both], iPhone 7).
The only way for me to log in is to copy following cookie values from working browser.

1. _PracticalDeveloper_session
1. _csrf_token

Here is the demo of 
1. trying to login (in Edge, but the process it the same on all browsers),
1. revoking GitHub access
1. authorize
1. and try to re-login.


![2018-11-29_15-49-35](https://user-images.githubusercontent.com/8465237/49251016-6f4ec780-f3ee-11e8-9f69-c9a89472ab98.gif)

**Comment by stephencweiss** [comment]
I'm totally locked out. I've revoked access (with the intent of reinstating it, but am unable to as I only see the "something went wrong" error). I've cleared my cache. Please help!

**Comment by tdwright** [comment]
As discussed with @Zhao-Andy via email, I'm experiencing this issue too. Like @stephencweiss, I've tried both Twitter and GitHub, with the same result.

I did have a working login on one laptop (the one from which I initially registered), but like @stephencweiss I revoked the permissions with the intent of reinstating them. I wish I'd thought of copying the cookie from the working machine to the others before I revoked. 😞 

Since this only seems to be affecting a very small minority of users, perhaps we can work out what the common factors are?

The potentially pertinent facts about me are:

* I connected both GitHub and Twitter in quick succession during my initial session
* My problems started by trying to log into the site from a mobile device (on the same wireless network as the working laptop)
* Subsequently I've also been unable to login (using either service) from a second laptop on a different network
* My GitHub and Twitter accounts are secured with U2F
* Both accounts have the same username @tdwright
* I'm in a non-US timezone (AEDT currently)

I'm sure I'm unique on any single one of these attributes, but perhaps I exhibit a strange combination of two or more?

**Comment by stephencweiss** [comment]
I don’t know that I can offer quite the same details as Tom, 

but some details:

* I did *not* try to connect to Twitter *until* after my GitHub was breaking
* I believe the problem first started when I was trying to log in on a different Chrome profile (i.e. different session cookies)
* I am now locked out on all devices, networks, and browsers as far as I can tell
* I am in US CDT

**Comment by Zhao-Andy** [comment]
In both instances, removing @stephencweiss and @tdwright's RSS feed URL seemed to work. Might be related to #1051.

We're going to close this for now and keep #1051 open. If you have issues signing in and see the error message of "Invalid credentials", let us know via yo@dev.to!
