### ISSUE TITLE
/connect/meta not loading messages

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#1250]
**Describe the bug**
Seeing no messages for meta channel in connect. Only happening for that group channel. 
When I click on it, this is what I see in the console:

![](https://cl.ly/23404924df7c/download/Image%202018-12-03%20at%205.04.58%20PM.png)

**To Reproduce**

1. Go to dev.to/connect
2. Click on meta

**Expected behavior**
Channel should have message history.

**Comment by benhalpern** [comment]
Okay, so I think this is what's going on:

When we return a 404 (which we return when access is denied), it is being cached. So the next person with privileged access gets the cached non-privilege response. We entirely don't cache the typical response, so there's no worry about data leaking. But I think the headers when we return these status pages ask Fastly to cache the response on the edge.

To fix: Adjust the headers of status pages so that they do not cache. Although we maybe do want them to cache in many cases for performance reasons, so this maybe only needs to apply in certain cases.

**Comment by benhalpern** [comment]
Fixed via VCL adjustment
