### ISSUE TITLE
Wrong page title with Latest filter

### ISSUE THREAD

**Issue by HZooly** [thepracticaldev/dev.to#1316]
**Describe the bug**

When you filter a tag with time filters, HTML title page is updated. This is working for time filters, and feed (default filter).

Selecting *week* changes page title in : *`<tag> - top this week`*.

Selecting *feed* changes page title in : *`<tag>`*

Selecting *latest* changes page title in : *`<tag> - top this latest`* // **wrong?**

**To Reproduce**
[Visit Flutter](https://dev.to/t/flutter/latest)

**Expected behavior**
Title : *`<tag> - latest`*

**Comment by Zhao-Andy** [comment]
Good catch @HZooly, thanks!

**Comment by Some-Dood** [comment]
https://github.com/thepracticaldev/dev.to/blob/074d50d2b70be66d800cefa2b11c249bb38725e9/app/views/articles/index.html.erb#L2-L6

https://github.com/thepracticaldev/dev.to/blob/074d50d2b70be66d800cefa2b11c249bb38725e9/app/views/articles/tags/_meta.html.erb#L1

For anyone who wants to work on this, adding some logic in these files should resolve this issue. I'm not of a Ruby person myself, which is why I'm not confident to work on this.

**Comment by HZooly** [comment]
@Some-Dood Same, I think this is the right way, but I'm not an expert with this template syntax, so I prefer let it to someone else.

**Comment by arku** [comment]
@Zhao-Andy Let me fix this issue.

**Comment by Zhao-Andy** [comment]
Go for it!
