### ISSUE TITLE
Bug: Can't delete RSS-based posts that I don't want to ever publish

### ISSUE THREAD

**Issue by SeanKilleen** [thepracticaldev/dev.to#137]
Big fan here by the way.

# _BUG_
### Steps to replicate

* Set up the RSS import on dev.to so that I can link it to my blog
* See articles come in, publish some, etc.
* Delete an article that I don't ever want to publish on dev.to

### Current Behavior

* The article comes back into my dashboard as unpublished, so I have several articles that will forever sit in my dashboard.

### Expected Behavior

* When I delete the article, I shouldn't see it in my dashboard again.

### Screenshots

> ![image](https://user-images.githubusercontent.com/2148318/34881424-882fa036-f781-11e7-8e8b-70fb8a3eac98.png)

> ![image](https://user-images.githubusercontent.com/2148318/34881462-9d48e054-f781-11e7-9cfc-de3e8275cef9.png)

**Comment by shindakun** [comment]
It looks like they would come back when the RSS refreshes and annoyingly it seems to be at the top of the article list. That's an interesting issue... The backend would need to keep a list of articles from RSS that you've removed to remove them again each time it refreshes.  But what happens if you deleted an article by accident?

**Comment by SeanKilleen** [comment]
Those were my thoughts exactly. I agree, it would be a list of IDs or some other identifiers for that RSS article. A URL perhaps? My thinking from user experience perspective is that if I delete an article by accident from my RSS list, it would still be easily achievable to republish that article on the site, because I still have the original content from wherever the source of the RSS file is.

**Comment by jessleenyc** [comment]
Thanks @SeanKilleen for bringing this up and @shindakun for jumping in. We've added this issue to our backlog.

**Comment by SeanKilleen** [comment]
Commenting on this to keep it open because I think it still makes sense as a backlog item and I haven't seen it addressed elsewhere. /cc @jessleenyc as FYI because she'd commented previously.

**Comment by maestromac** [comment]
not stale

**Comment by daneah** [comment]
Still seems like an interesting thing to discuss!

**Comment by SeanKilleen** [comment]
Agreed it's still worth doing. I may jump in for a PR on this.

I'd suggest the following as a minimal first pass:

* Add a boolean column in the db to capture whether a post is hidden
* Allow people to enter "hidden: true" in YAML. On save, if the field is present
* If you want, add a "hidden: false" by default on import from RSS to make authors aware
* Add logic to only display non hidden drafts
* Add a querystring or similar to show hidden drafts
* Add a button that redirects to that query string
* Add a post explaining how it works 

Do folks agree with this? If so we could probably get some PRs started.

**Comment by devjack** [comment]
I love the idea and have colleagues who would love to use it too.

From a taxonomy/terminology perspective, perhaps the ability to 'ignore' draft posts (rather than overloading 'hidden' and 'deleted' fields, and 'muting' notifications? For example, it could look like this:

<img width="824" alt="Screen Shot 2019-04-17 at 3 58 09 pm" src="https://user-images.githubusercontent.com/3516066/56264416-c4833f80-6129-11e9-968b-d61b17442c36.png">

The ability to hide or archive posts that are created manually (i.e. not a feed) is certainly useful, but the intent here is to specifically ignore external content being fed in.

Potential problems:
 - Identifying RSS content - there's no definitive "id" in RSS but there is a required URL field, and an optional guid field. I'd suggest using the guid where available, and the url by default. It's unlikely a url will change, and if it does, its in frequent enough to not be wildly inconvenient to re-ignore in the dashboard.
 - UI clutter around 'filtering' ignored content. I'm no UX expert and I'm conscious of cramming in more buttons and text in what is currently a nice simple UI.

**Comment by jessleenyc** [comment]
We could have an 'ignore' option _and_ an 'archived' option but I also think just 'archived' will likely accomplish what we're looking for, even if the intent is slightly different. 

Instead of handling this in the front matter, let's do it from the dashboard. The buttons are starting to clutter and we want to move them (mute notifications + this new button) as dropdown options. We can add an ellipses similar to where additional options appear on individual comments.

**Comment by SeanKilleen** [comment]
Makes sense. 👍 

To recap: from a UX perspective, it sounds like what we want to do is:

* Allow the users to mark a draft post as archived via an ellipsis menu
* Avoid resurfacing a draft post from RSS on the UI if it's already been archived
* Determine how to display archived posts for the user (the small text & link from @devjack above seems to cover this well if there are no objections).

Technical Analysis:

* Is there an RSS ID or URL associated with posts that come in through the RSS feeds? (it seems like there is currently)
* Seems like we'll need to add the "archived" bool (which there didn't seem to be any objection on)

## Acceptance Criteria (as I understand it)

* Can Archive an item in draft posts
* Archive link appears when there are archived items
* Archive link does not appear when no archived items exist
* Can view archived items by clicking on the link
* Items from feeds don't re-appear in drafts once archived

**Comment by SeanKilleen** [comment]
(oops, accidentally closed). No triage necessary hopefully (though I would like confirmation on the A/C)

**Comment by jessleenyc** [comment]
If we're able to get filtering in soon, we can probably have 'archived posts' as one of those options but I think what @devjack suggested for now makes sense  -- https://github.com/thepracticaldev/dev.to/issues/2351 (cc @omenking ) 

If you're going to tackle this, please post a mockup of the ellipses/dropdown design just to make sure we're on the same page. We can also take care of any last mile design stuff.

**Comment by maestromac** [comment]
@SeanKilleen guid seems to be the only reasonable one we can use to uniquely associate posts.

**Comment by danascheider** [comment]
@SeanKilleen I'm happy to start a PR on this if you think the specs/acceptance criteria you outlined above are well enough finalised.

**Comment by SeanKilleen** [comment]
I welcome a PR since I'm a hit swamped at the moment but the acceptance criteria etc. belongs to the dev.to folks :) I just made the original observation.

**Comment by danascheider** [comment]
Cool, well in that case I'll wait for some confirmation from them so I don't end up going too far down the wrong path.

**Comment by danascheider** [comment]
@maestromac What do you think?

**Comment by maestromac** [comment]
Yep, give it a go @danascheider !

**Comment by danascheider** [comment]
Sounds good, I'm on it :)

**Comment by danascheider** [comment]
@devjack @maestromac The RSS specification indicates that all fields under `<item>` are optional, including URL. In fact, every field under `<item>` is optional, with the exception that the item has to have either a title or a description. I'm trying to think of a workaround for how we can uniquely identify RSS content but any suggestions are welcome.

**Comment by SeanKilleen** [comment]
@danascheider for the purpose of this PR, would it make sense to address it using whatever method is currently in use? If URL is being used, I'd recommend using that for now and creating a follow up PR later. 

I'm ssuming they already have a way of doing this (via URL or another method) because posts don't repeat in my dashboard when they come in via my RSS)

**Comment by danascheider** [comment]
@SeanKilleen Ah true! Yeah, I'll figure out how they are already being differentiated.

**Comment by devjack** [comment]
New archive UI (and functionality) looks great @danascheider! I feel it solves our 'delete rss posts' bug scenario well, so suspect this can be closed now?

**Comment by SeanKilleen** [comment]
@devjack totally agree. Thanks to @danascheider for making this happen!

**Comment by kievsash** [comment]
Still observing that issue - imported mediums articles through rss, they are saved as draft on dev.to.
I delete them and they re-appear on my dashboard

**Comment by maestromac** [comment]
Hello @kievsash . The workaround we currently have in place is if you archive the said post, it won't be re-imported back.

**Comment by kievsash** [comment]
Thanks! Now I cannot archive)
"Failed to update article."
POST https://dev.to/articles/128728 404 - in Dev console

**Comment by maestromac** [comment]
Hey @kievsash thank you for reporting that! That is indeed a bug and it will be fixed.
