### ISSUE TITLE
Ability to merge similar tags

### ISSUE THREAD

**Issue by vnbrs** [thepracticaldev/dev.to#1469]
**Is your feature request related to a problem? Please describe.**
Recently I've posted ["I want to learn functional programming: where to start?"](https://dev.to/vnbrs/i-want-to-learn-functional-programming-where-to-start-3hek) and to tag it, I searched for what people were using to tag functional programming posts. I found out that there were two tags being used, "fp" and "functionalprogramming", but these two tags mean the same.

**Describe the solution you'd like**
Stack Exchange deals with it very well with moderation features. They provide a way to merge and make tags as synonym, considering one of the tags as the main one.

For instance, if we choose 'functionalprogramming" as the "right" one, this feature would:
1. Remove synonyms from existing posts, in my case it'd remove "fp" from my post
2. Add the main tag ("functionalprogramming") to these posts, if it isn't tagged with it yet
3. For new posts, auto-correct "fp" with "functionalprogramming"

**Comment by jessleenyc** [comment]
Hey @vnbrs, we're actually going to close the issue because this feature technically exists for admins already. We're going to schedule some time to batch merge some tags -- something we haven't done in a while. We're also going to ask tag moderators to alert us when they see tags that should be merged. Thanks for bringing this up!
