### ISSUE TITLE
Comments overlapping in Edge

### ISSUE THREAD

**Issue by kingdamian42** [thepracticaldev/dev.to#1593]
**Describe the bug**
When using Edge, some comments render as overlapping eachother

**To Reproduce**

1. Go to https://dev.to/ilonacodes/frontend-developers-do-you-want-to-transition-to-fullstack-why-44b9 in Edge
2. Scroll down to the first child comments under "Xander"'s comment.
3. See error 

**Expected behavior**
The comments should not overlap while using Edge.

**Screenshots**
Example of issue: https://imgur.com/a/IW3sbEG

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge
- Version: Microsoft Edge 42.17134.1.0

**Comment by Zhao-Andy** [comment]
Thanks for the report. This is most likely because we have HTML toggles that collapse and expand the comments, but it's not supported by Edge yet.

https://caniuse.com/#search=details

**Comment by benhalpern** [comment]
@Link2Twenty I think that hack is okay in this case.

We knew the `<details>` element wasn't going to be supported by Edge, but went ahead with the idea that it was okay because it generally looked like it never existed overlooked this part when making the additional change of putting the toggle button next to sub-comments.

So it seems like a sensible patch that doesn't add unnecessary debt elsewhere.

**Comment by Zhao-Andy** [comment]
Still an issue. @Link2Twenty's suggestion should be a good starting place if anyone wants to work on this.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/3553
