### ISSUE TITLE
Search term autocomplete

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#1643]
**Is your feature request related to a problem? Please describe.**
Users should be able to get suggested search terms as they type in the main site searchbar.

**Describe the solution you'd like**
We want to show suggested search completions as users type. Once we have this, we could possibly augment it with suggestions for search results right in the dropdown. But what we don't want to do is _only_ show results because we'd like the experience where users can jump to a dedicated results page with additional filters and a list to pick from, ala Google etc. I think if the autocomplete is full of results it will not be obvious that the next page might also be helpful.

Implementation:

We already have a component area for the search bar, and this functionality can be built on top of it there: `app/javascript/src/components/Search`.
CSS for the nav bar is here: `app/assets/stylesheets/top-bar.scss`

Algolia is currently made available globally outside the context of our componentized JS, so access the Algolia API similar to how we do in the tag autocomplete in the editor:

```javascript
    const algoliaId = document.querySelector("meta[name='algolia-public-id']")
      .content;
    const algoliaKey = document.querySelector("meta[name='algolia-public-key']")
      .content;
    const env = document.querySelector("meta[name='environment']").content;
    const client = algoliasearch(algoliaId, algoliaKey);
    this.index = client.initIndex(`Tag_${env}`);
```

On the Ruby side of things, we have a `SearchKeyword` model we currently only use for a select few purposes, but this is the table we'd like indexed to display. We would need Algolia functionality added via `algolia-rails`, similar to how we do elsewhere.

This is the data we currently hold on that table:

```ruby
    t.datetime "created_at", null: false
    t.datetime "google_checked_at"
    t.integer "google_difficulty"
    t.integer "google_position"
    t.string "google_result_path"
    t.integer "google_volume"
    t.string "keyword"
    t.datetime "updated_at", null: false
```

The Google info is just used for other details related to helping us determine keyword ranking. The "keyword" string is probably most important here.

In addition to this PR, we still have the additional outstanding element of improving functionality on the results page. That can be seen here:

https://github.com/thepracticaldev/dev.to/issues/797

**Comment by R4ph-t** [comment]
Hello @benhalpern, thanks for all the great resources provided!

I just wanted to dig a little on one point :
> We want to show suggested search completions as users type. Once we have this, we could possibly augment it with suggestions for search results right in the dropdown. But what we don't want to do is only show results because we'd like the experience where users can jump to a dedicated results page with additional filters and a list to pick from, ala Google etc. I think if the autocomplete is full of results it will not be obvious that the next page might also be helpful.

Your point makes sense from a usability point of view, but I think it creates more friction than necessary in the UX which could be avoided by a simple clever UI.
Why adding another step into the search process (type > see/click suggestion > see results) when you can provide results from multiple index right away as you type and also clearly show that there are more results available with a **show x more items** button below.

I drafted something, it’s far from complete on the design side and using very limited data set, but it does give an idea of what could be possible.

![devto auto](https://user-images.githubusercontent.com/1368445/52216466-90241500-2896-11e9-8ddb-1f928a80ca7a.gif)

A few things to have in mind: 
* the show more would redirect to a full page search experience with facets.
* Query suggestions could be one of the section of the dropdown, or show only when the results are empty.
* Query suggestions with Algolia are based on the analytics feature: in order to build a relevant (and safe) index of suggestions. It’s an advanced feature you need to have enabled (available for higher-end plans).

I think for a start having autocomplete with multi-category indexes and `show more` to redirect to full page search would already be a great improvement over the search bar as it is today.
Looking forward to get your thoughts on that!

**Comment by R4ph-t** [comment]
Need a bit more time for that one, had to focus on other priorities but will be back to it hopefully soon.

**Comment by mstruve** [comment]
Since all the implementation details for this are for Algolia I am going to close. If we decide this is still something we want to do with Elasticsearch we can explore that. I do think that as we add more search filter options to a sidebar that we wont need a typeahead.
