### ISSUE TITLE
Number of views doesn't change

### ISSUE THREAD

**Issue by sandordargo** [thepracticaldev/dev.to#1765]
Hi,

I found something strange for my number of views.

I have the same number of views (user: @sandordargo, views: 156) for my last three posts.

The last one is strange, it hasn't changed for like two days, while the number of reactions are going up and it was featured on twitter as well. I don't think that the number of reactions can go up without the number of views also going up.

Thanks for having a look.

Cheers

**Comment by Glennmen** [comment]
I have noticed the same, my post views has been 101 the entire day even though it has also been featured on twitter. I thought that views might not be updated live, unlike reactions, but was updated with a job once a day.
Curious about the reactions here if it is indeed a bug or intentionally.

**Comment by sandordargo** [comment]
For me it's been 156 for days. Once a day makes sense, but having three posts with exactly the same number of views and for days... Must be a coincidence! :D We'll see!

**Comment by jessleenyc** [comment]
Hm. Previously stats were updated each time someone interacts (reacts or comments) on a post but I believe we've started to pull numbers more frequently. I'll bring it up in our team meeting later.

**Comment by jessleenyc** [comment]
That is indeed the case. I think we should consider adding an update button next to each post so people can manually fetch the latest numbers. I'll create a separate issues for that. 

I don't seem to be able to recreate your issues though. Have the numbers updated at all?

**Comment by Glennmen** [comment]
Isn't this the part that causes the issue of article views not getting updated (when there are no new reactions)?
https://github.com/thepracticaldev/dev.to/blob/8b8dbd017253e05d0a00fc568f487fd602144dcc/app/labor/article_analytics_fetcher.rb#L47-L51

I see there is `article.previous_positive_reactions_count` to check if reactions have changed since last Analytics check, couldn't we solve this with a `previous_analtyics_update_at` datetime column that will trigger a new Analytics check if it has been more than 24 hours.

Having a manual `Update` button might be abused by people checking every 5 minutes.

**Comment by Glennmen** [comment]
@jessleenyc This is very strange, according to the logic in `app/labor/article_analytics_fetcher.rb` if the article has more reactions than the previous check it will fetch the views again for the article.

In the last ~4 days I gained 5-6 reactions for my last article but my views stayed at 711. It seems to stop updating at some point, there has to be something we are overlooking because according to the logic my views should have been updated.

**Comment by jessleenyc** [comment]
Hey all, this should be fixed now!

**Comment by sandordargo** [comment]
Thanks!

**Comment by Glennmen** [comment]
@jessleenyc Will it also update/fix old articles? None of my article views seem to have been updated.

**Comment by jessleenyc** [comment]
Looks like it didn't update old articles. We'll run a script to fix that soon - will keep this issue open until then!

**Comment by Glennmen** [comment]
@jessleenyc What PR fixed it for new articles? I think I missed it.

**Comment by jessleenyc** [comment]
@Glennmen i believe it was this one: https://github.com/thepracticaldev/dev.to/pull/1985

**Comment by jessleenyc** [comment]
@Glennmen how do things look now?

**Comment by Glennmen** [comment]
@jessleenyc Hard to say honestly, I don't see any difference compared to what I can remember from earlier or yesterday.

**Comment by jessleenyc** [comment]
Hmm... well, we ran the script to update older article analytics. It's possible that the numbers haven't changed too much since the article is past its initial burst of engagement?

I'm going to close this issue for now but if you notice out of sync numbers again, definitely feel free to open a new issue!
