### ISSUE TITLE
Footer visually overlaps Left Hand Nav Card

### ISSUE THREAD

**Issue by 12vanblart** [thepracticaldev/dev.to#1794]
**Describe the bug**
In a Chrome window sized 1305x842, I scrolled to the bottom of the "My Reading List" and the Footer overlapped the Left Hand Card. 
![visual overlap showing](https://user-images.githubusercontent.com/16465776/52667862-069cc480-2ee0-11e9-9d82-ad26edd9f816.png)

**To Reproduce**
0. (Resize window to ~ 1305 x 842) 
1. Go to "My Reading List"
2. Scroll down to the bottom of the page (As far down as possible)
3. See overlap

**Expected behavior**
I'm not sure what the bet way to handle this is, but possibly by shrinking the width of the footer card to match the width of the center column. 

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 72.0.3626.96

**Comment by Link2Twenty** [comment]
Looks as though if the height is below `880px` and the width is above `950px` this issue will arise.

**Comment by aspittel** [comment]
Thanks for reporting this @12vanblart, and thank you @Link2Twenty for looking into it more! Will look into this.

**Comment by willamesoares** [comment]
Hey @aspittel, is this currently being worked on by someone? If not, let me know and I can take a look at it this week, thanks ;)

**Comment by mariocsee** [comment]
@willamesoares are you currently working on this? If not, I can hop on it soon

**Comment by willamesoares** [comment]
@mariocsee I was hoping that someone would let me know that this could be worked on since I don't know if there's someone already on it. I think since I didn't get any answer I'll just go ahead and fix this ;)

**Comment by mariocsee** [comment]
@willamesoares It doesn't seem like anyone is working on this, especially since no PR has referenced this issue. Thanks Will!

**Comment by willamesoares** [comment]
Hey, @mariocsee I looked into this and realized there are a few ways of solving it but I'm not sure which layout would be better since this needs more discussion. I was thinking about making the footer the same width as the posts list container for screens sizes that show the overlap and keep the current behavior for other sizes.

Would you be willing to take a shot at this one and see if you can come up with an alternative for what I proposed and then we could investigate which way would be better from a UX/UI standpoint?

**Comment by mariocsee** [comment]
@willamesoares Looking at how articles pages have the footer width match with the article content to prevent overlap with the cards on the right side, I think you've good idea of how to go about this issue to prevent the overlap with the cards on the left. Something to potentially check for is how the footer behaves in other DEV pages since it's used all throughout. 

<img width="791" alt="Screen Shot 2019-03-15 at 11 02 06" src="https://user-images.githubusercontent.com/13403332/54441008-2d822c80-4712-11e9-91c6-2751bee45840.png">

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2166
