### ISSUE TITLE
Can't Login with Twitter

### ISSUE THREAD

**Issue by clsource** [thepracticaldev/dev.to#186]
# _BUG_
### Current Behavior
Can't Login with twitter account.

### Expected Behavior
User should be enabled to login. Or enabled to login with multiple login methods in order to avoid lock down if one of the login methods is no longer available.

### Additional Info (steps to replicate, device/browser, helpful links)
The account was previously registered in dev.to. Then was deleted from twitter and created again.
dev.to no longer enables login. Probably because twitter changed the access tokens and a mismatch occurs in the dev.to internal db.

### Screenshots
![imagen](https://user-images.githubusercontent.com/292738/37916783-1e623fb4-30f3-11e8-913f-548f7834153d.png)

**Comment by Zhao-Andy** [comment]
Hey @onderweg, this is a weird edge case that happens when you don't have an email attached your account. If you go to https://dev.to/settings, add your email and confirm it, you should be able to view articles properly.

That said, we should fix this edge case. Thanks for the report!

**Comment by clsource** [comment]
Yes.
My account is https://dev.to/clsource
And it´s linked with the twitter account https://twitter.com/camcasc

That twitter account was deleted because I wanted a fresh start. Then created again.

I tried login with github but the system created another account

https://dev.to/clsource_18

It would be nice to be able to login with twitter or github linked to the same account 👍 

Thanks.

**Comment by Zhao-Andy** [comment]
Oh, gotcha. I think deleting your Twitter account expires the OAuth token, which is why you ran into that error page. That's an edge case that we don't account for (yet). I've attached your GitHub account to your original dev.to account, @clsource. 

I believe these steps should solve the issue:
1. Log into dev.to via GitHub.
2. Check that you're signed into your original dev.to account with the username `clsource`.
3. Go to https://dev.to/settings and attach your Twitter account to your account again.
4. Success!

Let me know if it works, and if it does you can close the issue. :)

**Comment by jessleenyc** [comment]
@clsource closing this issue but please reopen if it's not resolved!

**Comment by ali2210** [comment]
Twitter Disconnect

**Comment by Zhao-Andy** [comment]
@ali2210 not sure what you mean but feel free to send yo@dev.to an email if you're having issues with your account.
