### ISSUE TITLE
Followers page doesn't display the correct number or the full list of followers

### ISSUE THREAD

**Issue by BogDAAAMN** [thepracticaldev/dev.to#1921]
**Describe the bug**
I believe that the number of followers in the dashboard is computed wrong or the follower's list is not complete. 

The dashboard indicates that I have *349* followers  

![The current number of followers](https://user-images.githubusercontent.com/22895284/53522523-d574e480-3ada-11e9-80cd-35b77ecaf9f2.png)

but the number of follower cards on followers page is **80**.

![Count of cars](https://user-images.githubusercontent.com/22895284/53522567-f0475900-3ada-11e9-883e-e5f0c95d5fc8.png)

Also, when I got notifications about a new follower, the number of followers in my dashboard was incremented with a random number (not +1). Not only in emails, but in dev.to notifications as well. I remeber seeing a notification `<somebody> followed you!` and the number of followers would increase by 10. This might happen because I don't get notifications for each follower, I don't know how it currently works.

![Emails about followers](https://user-images.githubusercontent.com/22895284/53522830-88ddd900-3adb-11e9-8c79-b96cb694be40.gif)

**To Reproduce**

1. Go to Dashboard.
2. Click on Followers tab.

**Expected behavior**
To print the real number of followers. To print all the followers if the number is correct.

**Comment by rhymes** [comment]
Regarding the first one (you should probably open two separate issues because they are two separate things :D). 

The reason is that only the last 80 are shown:

https://github.com/thepracticaldev/dev.to/blob/4ac36bbeffad09210cc25be5a586a67e36d2e43e/app/controllers/dashboards_controller.rb#L18-L20

That page is also not paginated so you can't scroll through all of them.

There's an old issue #258 about this, I agree that there should be a way to scroll or paginate through all followers :)

I don't know about the second issue you raise.

**Comment by BogDAAAMN** [comment]
I feel so dumb, I should've take a look at the controller first.
