### ISSUE TITLE
navigation-progress not work

### ISSUE THREAD

**Issue by Butonix** [thepracticaldev/dev.to#1926]
The code has a progress bar, but it does not work
`<div class="navigation-progress" id="navigation-progress">`

**Comment by rhymes** [comment]
@Butonix I think your bug issue would be more effective if you followed the template you can find here https://github.com/thepracticaldev/dev.to/issues/new?template=bug_report.md

For example:

* how to reproduce?
* what is the bug?
* what does it affect?
* do you have screenshots?
* which platforms?

Otherwise is next to impossible to understand and then work on the issue :)

Thank you!

**Comment by aspittel** [comment]
Hey @Butonix, thanks for filling out this issue! Would love more details on what you're seeing. Thanks again!
