### ISSUE TITLE
Old post missing content

### ISSUE THREAD

**Issue by ProfessorBeekums** [thepracticaldev/dev.to#2036]
**Describe the bug**
I was just browsing some of my old posts and noticed that the two oldest from 2016 have no post content:
https://dev.to/pbeekums/teach-writing-code-first
https://dev.to/pbeekums/technical-debt

Everything from 2017 on still exists.

**To Reproduce**

1. Go to https://dev.to/pbeekums/teach-writing-code-first
2. See empty post content and some comments.

**Expected behavior**
The original post content (I could probably dig it out from somewhere, but I'm hoping there wasn't data loss on dev.to)

**Desktop (please complete the following information):**

- OS: LinuxMint 18
- Browser: Chrome
- Version: 65

**Comment by Zhao-Andy** [comment]
Hey @ProfessorBeekums, sorry about that. The data is still there, but I believe the issue is because in the past, we had a different way of writing posts and the data was saved into a different column called `body_html`. We might have accidentally missed an `if` statement to render that specific column on the page.

**Comment by benhalpern** [comment]
Hey, I'm running a script to update everything now. Sorry about the issues. You're user #113 so this is a unique type of issue to run into for early adopters only. 🙌

**Comment by benhalpern** [comment]
Fixed 👌

If there are any edge cases that went unfixed, let us know.
