### ISSUE TITLE
Possible race condition when sending new reaction notifications?

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#2124]
There seems to be a weird race condition or something where a reaction notification is created twice. Both notifications have `json_data: nil` and the same `created_at` timestamp.

![double notifications](https://user-images.githubusercontent.com/17884966/54693704-6f89e480-4afd-11e9-867a-14f96398bb93.png)

@lightalloy's WIP PR #2122 might resolve it, but I'm not sure what the root cause is.

**Comment by abraham** [comment]
I remember seeing weird things around the reactions count displayed when rapidly clicking on a reaction. It might be related.

**Comment by Zhao-Andy** [comment]
@abraham oh hm, good point.

**Comment by lightalloy** [comment]
@Zhao-Andy My pr will address the possible deserialization errors (from #1621), it won't make the job idempotent by default. 
Reacting/then unreacting might be a case, though it's weird that the `json_data` is set to `nil`.
I'll do the research on this issue.

**Comment by lightalloy** [comment]
I researched a bit and I suspect that this code may cause this problem:
https://github.com/thepracticaldev/dev.to/blob/9470ad8e7f42bc15cf5c4752c4a61e448eba7df5/app/models/notification.rb#L154-L159

There's a unique validation on Notification fields `user_id`, `notifiable_id`, `notifiable_type`, `action`, but there's no unique index in the database for these fields. The model validation doesn't prevent race conditions, so it's possible for the same notification to be created more than 1 time. Later in the code, there's an attempt to update values (`save!`), which fails because the unique validation fails, so the `json_data` remains `nil`.
For now, I suggest at least adding a unique db index for these fields. I think the `find_or_create` can also be replaced with `find_or_initialize`.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2213
