### ISSUE TITLE
Dark mode - org CTA box content is hard to read (needs contrast)

### ISSUE THREAD

**Issue by andypiper** [thepracticaldev/dev.to#2222]
**Describe the bug**
It is difficult to read the black text on dark background in the CTA box on organisation posts.

**To Reproduce**

1. Go to https://dev.to/twilio
2. Click on any post
3. Check the sidebar
4. See below

**Screenshots**
<img width="297" alt="Screenshot 2019-03-26 at 20 40 43" src="https://user-images.githubusercontent.com/552452/55031939-ac773f00-5007-11e9-9e77-718ac4e9ed29.png">

**Comment by co16353sidak** [comment]
@andypiper not able to reproduce the same issue, I have followed along with steps but not able to reproduce, can you check if the issue has not been already fixed by checking again ?
<img width="341" alt="Screenshot 2019-03-30 at 11 44 52 PM" src="https://user-images.githubusercontent.com/35738138/55280014-d2714c00-5345-11e9-8a8e-acf2fe73286d.png">

**Comment by mjraadi** [comment]
@andypiper, I experienced somewhat similar behavior shown below. I changed to default theme and then back to the "night mode" again and I didn't see the issue anymore. I'm not sure this is the "fix" but it worked for me.
![night-mode-profile-issue](https://user-images.githubusercontent.com/20579660/55458459-49d30400-5602-11e9-84d4-c5efdb06666b.gif)

**Comment by andypiper** [comment]
Looks much better now. Thanks for checking!
