### ISSUE TITLE
Self-serve live broadcasting

### ISSUE THREAD

**Issue by coreyja** [thepracticaldev/dev.to#2317]
I'm making this as a place for discussion following this post by @benhalpern https://dev.to/devteam/dev-feature-idea-self-serve-live-broadcasting-5bli

I wanted to open this up for discussion and figure out what features might be involved in the dev.to build. I am also willing to work on this project and contribute to it and this seemed like a good place to start!

**Is your feature request related to a problem? Please describe.**
I've tried live streaming coding a handful of times before, but felt like there was never a good platform for developer focused live streaming.

**Describe the solution you'd like**
I think that the best way to get this started is probably to embed one or more streaming platforms such as Twitch and Youtube Live. Most of the commentators in the original post seemed to think embedding was a good place to start.

One question this raises is how to deal with chat
Ben mentioned in the original post, that dev.to has some in-house chat architecture build. This is one potential solution, but means that each stream may need to manage two chats. The main streaming platforms chat, and the dev.to chat
Another solution would be to completely embed a streaming platform(s) including the chat. Both Twitch(1) and Youtube Live (2) support this behavior. A downside to this approach is that it makes it harder for the dev community to moderate directly.

restream.io does offer some sort of chat consolidation tools, but I don't know much about their offerings or how to integrate with them.

**Describe alternatives you've considered**
One alternative is to host the live streaming platform natively. I will admit I don't have much experience in this domain, but I feel like this is a large amount of work to build and maintain, that is fairly tangentially to the current dev.to offerings and (uneducatedly) assumed infrastructure.
However a native build might make the chat question easier, as having a native chat offering already is a huge plus!

(1) https://dev.twitch.tv/docs/embed/everything/
(2) https://support.google.com/youtube/answer/2524549?hl=en

**Comment by benhalpern** [comment]
I think we can explore some of the ideas as we go while building this out.

We _basically_ need something like this to get started:

- `is_currenty_livestreaming` attribute on user. Boolean letting us know if they are streaming.
- `stream_source` some identifying string letting us know what service they're using. Twitch, YouTube, or native DEV (which could be rolled in as an option after initially offering others).
- A webhook to tell us whether the stream state has changed.

Looks like there is everything we need in the Twitch API:
https://dev.twitch.tv/docs/api/webhooks-reference/#topic-stream-changed

Here are the YouTube docs:
https://developers.google.com/youtube/v3/live/getting-started

Here are the docs for Mixer:
https://dev.mixer.com/guides/core/introduction

I'm pretty happy to start with just trying to support Twitch and then try for integrating others after. The same primitives of knowing what the service is and what state the stream is in should be the same for everything, but Twitch seems like the right default and the most comprehensively documented API.

We already have a page for our "centralized" livestreaming we did in the past, which we can build off of. I have a pretty good idea of how the pieces would fit together for the UX once we got the underlying functionality working properly.

I'm going to resist the urge to jump in on take this on myself early on because we have other priorities, but I'll help the pieces fall in place if anyone wants to create the functionality to get the ball rolling.

**Comment by coreyja** [comment]
Ok!

Got `dev.to` cloned locally and running so I am ready to get started!

Got started and got a question I thought I'd bounce around with whoever here! It does NOT seem like we NEED to oauth login the User in order to get their stream info, or to create webhooks.

However, adding oauth may also give us a good user experience, especially around not having to manually enter a `user_id` or `twitch_login`.

It also opens up the door for stronger integrations to come, but I feel like it may be overkill for this use case.
Thoughts?

**Comment by coreyja** [comment]
VERY Work in progress diff can be seen here. Started with getting a job written that will subscribe us to a Twitch webhook. A total hack at the moment but it's a start!

https://github.com/thepracticaldev/dev.to/compare/master...coreyja:ca/master/twitch-live-streaming?expand=1

**Comment by benhalpern** [comment]
Hey @coreyja this looks really cool! I feel like I'd be happy with any form of authorization (or not). I think you have a decent idea of the tradeoffs, so I'd be okay with whichever choice you make.

I think the progress looks like a really solid start!

**Comment by coreyja** [comment]
Got some of the webhook registration job stuff cleaned up and got a controller stood up to receive the webhooks! Making progress on this!

**Comment by coreyja** [comment]
Making some good progress! Might even get a PR open today! Definitely not ready to go out yet, but most of the pieces are falling into place!

If I can get a page that will display the live stream for a User I think this will be in a great place to have some eyes on it!

**Comment by coreyja** [comment]
I just got an MVP PR opened for this! 🎉

https://github.com/thepracticaldev/dev.to/pull/2591

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/2591
