### ISSUE TITLE
Can't publish a blog post draft

### ISSUE THREAD

**Issue by erwald** [thepracticaldev/dev.to#2357]
**Describe the bug**
When trying to publish my blog post (currently existing as a draft), I get the following error:

😱 Heads up:
base: can't modify middleware stack after making a request

Displayed on a big red banner.

**To Reproduce**

1. Go to my blog post draft
2. Press "EDIT POST"
3. Press "PUBLISH"
4. See the error above

**Expected behavior**
I expect my blog post to get published.

**Screenshots**
<img width="893" alt="Screenshot 2019-04-10 at 12 30 50" src="https://user-images.githubusercontent.com/1210335/55866507-8e761680-5b91-11e9-9c3f-574629de50e0.png">

**Desktop (please complete the following information):**

- OS: macOS Mojave
- Browser: Chrome
- Version: 73.0.3683.86

**Comment by Glennmen** [comment]
I am also having this issue when I try to add a Github liquid tag to a draft post. Also can't preview it.

**Comment by rhymes** [comment]
By a quick Google search for "can't modify middleware stack after making a request" seems to be an issue with the Faraday gem triggered by something that misconfigures its middleware setup, there's some info here https://github.com/oauth-xx/oauth2/issues/173

Unfortunately Faraday is not used in the dev.to source code but by many of its dependencies so whomever takes this on might have to investigate which gem upgrade introduced this error.

Judging by the history of the `Gemfile.lock` I'd say it's [faraday-honeycomb](https://github.com/honeycombio/faraday-honeycomb) introduced in #2319 - it must be incompatible with something else. IIRC Faraday having a state machine sort of configuration is quite strict on the sequence of calls to setup its engine.

I can't verify it right now, but maybe I can take a look later

**Comment by Zhao-Andy** [comment]
Related issue: https://github.com/thepracticaldev/dev.to/issues/2336

@rhymes I was taking a look into #2336 and I found that there's an issue with how [faraday-honeycomb](https://github.com/honeycombio/faraday-honeycomb) is using Faraday. My understanding from reading https://github.com/oauth-xx/oauth2/issues/173 is that since we upgraded `faraday` itself to 0.15.4, this broke the way `faraday-honeycomb` used Faraday.

I think I'll either:
1. make a PR to fix it in `faraday-honeycomb`,
2. figure out how `faraday-honeycomb` is being used when the GitHub tag uses it, and intercept or prevent Honeycomb from being used there,
3. or come up with a different solution altogether. 🙃

**Comment by rhymes** [comment]
Wow Andy, great catch, can you fork Faraday honeycomb, apply the fix and then tell devto's gemfile to use that instead of the upstream gem?

**Comment by Zhao-Andy** [comment]
Oh yeah, that's a good point! I always forget about forking. I think I'll fork so we can have it working more quickly, and then make a PR on the upstream gem.

**Comment by erwald** [comment]
Yep, removing the GitHub tag worked as a workaround for me.

**Comment by nickytonline** [comment]
This is related to the bug I reported. I get the middleware error as well in #2336.

**Comment by nickytonline** [comment]
Ooops, just noticed that @Zhao-Andy already mentioned it. 🙃

**Comment by JeremyLikness** [comment]
It is consistent for me with the GitHub tag. Attached is the error that I get. I tried both formats:

```
{% github jeremylikness/azure-fn-file-process-hol %}
{% github https://github.com/jeremylikness/azure-fn-file-process-hol %}
```

And both prevent saving or previewing until I remove the tag. 

![error](https://user-images.githubusercontent.com/5479675/55902140-b6f51500-5b7f-11e9-852b-b25ccbb2f50c.png)

**Comment by nestedsoftware** [comment]
I see this issue was just closed, but I am currently getting this error when I try to save an existing, published, article (even without making any changes). I get this message:

can't modify middleware stack after making a request

This is the article I am trying to edit: https://dev.to/nestedsoftware/coding-interview-the-matchstick-game-43a8

**Comment by maestromac** [comment]
Hello @nestedsoftware . The fix is being deployed. Please give it another try in 15-30min and let us know if you are still experiencing the issue.

**Comment by Glennmen** [comment]
I am now getting this error:

```
POST https://api.github.com/markdown: 400 - Problems parsing JSON // See: https://developer.github.com/v3/markdown/#render-an-arbitrary-markdown-document
```

**Comment by Zhao-Andy** [comment]
Hey @nestedsoftware @Glennmen @JeremyLikness @erwald, could you give it a try again? The fix should be live now.

**Comment by Glennmen** [comment]
@Zhao-Andy Now it is working 👍

**Comment by Glennmen** [comment]
@Zhao-Andy Now it is working 👍

**Comment by nestedsoftware** [comment]
@Zhao-Andy working on my end as well! Thank you for the quick fix!
