### ISSUE TITLE
Followers/Following list doesn't contain all items, pagination needed

### ISSUE THREAD

**Issue by aershov24** [thepracticaldev/dev.to#258]
# _TASK or Feature_
### Request or User Story
It seems there is currently a limitation how many followers you could see on the https://dev.to/dashboard/user_followers page. Consequently there is no ability to follow people back who followed you while ago. 

### Definition of Done
user_followers page contains all the list of following users or has pagination to reach anyones contact to follow back.

**Comment by jessleenyc** [comment]
@benhalpern are you thinking pagination or infinite scroll for this?

**Comment by michael-tharrington** [comment]
Need to reopen.

**Comment by jessleenyc** [comment]
This is approved if anyone wants to work on it.

**Comment by omenking** [comment]
@jessleenyc what was wanted here? infinite scroll or traditional pagination?

**Comment by jessleenyc** [comment]
@omenking let's go with infinite scroll!

**Comment by omenking** [comment]
So infinite scroll exists on `articles/index` so going to see how I can translate that over to the `dashboard/followers` page.

Here I see a loading articles element
```erb
    <div class="loading-articles" id="loading-articles">
      loading...
    </div>
```

I'm thinking this has the js required to infinite scroll
```
<%= render "stories/stories_list_script" %>
```
Yep it looks like I'm right. I can do th same here for the other page. I do wonder if @benhalpern wants inline javascript because I would think it may be preferred for this code to go into app/javascript. My though being this code does not get minified/uglified being over here. I don't personally care which way but can align to whatever standards the project wants to achieve.

**Comment by omenking** [comment]
Doing a search for `'loading-articles` I was able to locate infinite scroll functionality.

<img width="854" alt="Screen Shot 2019-04-09 at 7 30 40 PM" src="https://user-images.githubusercontent.com/7776/55841659-0a268380-5afe-11e9-95ad-3c93a1864d8e.png">

**Comment by eschafer** [comment]
Hi - just wanted to point out that this page has a footer, which would potentially be really difficult to get to with an infinite scroll above it.

**Comment by omenking** [comment]
This is the footer. I think this would be negligible if we couldn't access it because of the infinite scroll.

<img width="735" alt="Screen Shot 2019-05-12 at 12 30 12 PM" src="https://user-images.githubusercontent.com/7776/57585123-b7037000-74b1-11e9-9eac-5e7cce8eff11.png">

I really want this feature so I'm going get on this again this week. It's mostly done but I have to do Q&A with it.

**Comment by johncurcio** [comment]
I'd love to work on this if nobody is working anymore. @omenking are you still working on this?

**Comment by omenking** [comment]
go for it. I did finish it but was never able to have it easily tested based on the lack of seed data
