### ISSUE TITLE
Mentor/Mentee description too short

### ISSUE THREAD

**Issue by Stargator** [thepracticaldev/dev.to#260]
# _Increase size of Mentor/Mentee description to 1000 characters_
### Request
Increase the number of characters a mentor or mentee can use to describe what they are looking for.

### Definition of Done
The description's max size is increased to somewhere between 750 and 1001 characters.

### Notes
As a mentee, I would like to explain further the problem or outcome I want.

# _BUG_
### Current Behavior
Says the description must be no longer than 500 characters. But I typed in 413-496 characters.

### Expected Behavior
For it to accurately detect the number of characters entered.

**Comment by M0nica** [comment]
@jessleenyc I would like to work on this issue if @maestromac did not fix this. Can you assign this to me?

**Comment by jessleenyc** [comment]
@M0nica go for it!!

**Comment by M0nica** [comment]
I am working on this. Ran into some issues with the format (unrelated lines being too long for Robocop) and my test suite was crashing. I am going to work on fixing the formatting issues so that I can commit and will check if the test suite crashes for me on master (and is related to my setup) or specific to the local changes I made.

**Comment by maestromac** [comment]
Resolved by #405
