### ISSUE TITLE
Negative Number Incorrectly Appeared Beside "Discuss" on An Article

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#2614]
**Describe the bug**
When looking at an article on DEV, I noticed it had "-1" beside "Discuss" which is used to denote how many comments there are on an article. The article is here - https://dev.to/steveblue/build-angular-like-an-architect-part-2-208l and this happened on April 26th. To be honest, I can't remember how many active comments the article had... I just noticed the negative one, thought it was weird, and snapped a photo.

**To Reproduce**
I can't figure out how to reproduce this for now. :-(

**Expected behavior**
I expect to only see positive numbers by "Discussion" and expect those numbers to correlate with the number of comments an article has beneath it.

**Screenshots**
![](https://cl.ly/a1ab569e8011/Image%2525202019-04-26%252520at%2525206.02.47%252520PM.png)

**Desktop (please complete the following information):**

- OS: MacOS Mojava 10.14.4
- Browser: Chrome 73.0.3683.86

**Additional context**
The number beside discussion has since been fixed.

**Comment by bolariin** [comment]
https://github.com/thepracticaldev/dev.to/blob/0e41a37eb61f58f7308d1da4b51c8bb2f72dbc9d/app/views/articles/_actions.html.erb#L18-L23
To resolve this, would it enough to change this from `nonzero?` to `positive`?

**Comment by Zhao-Andy** [comment]
@bolariin That makes sense. Nice find!

**Comment by bolariin** [comment]
After making the change to `_actions.html.erb`, I'm getting an error from the erb linter because of the use of `html_safe`. 
https://github.com/thepracticaldev/dev.to/blob/0e41a37eb61f58f7308d1da4b51c8bb2f72dbc9d/app/views/articles/_actions.html.erb#L61
I found that this can be resolved using `sanitize`. Following the other use of `sanitize`, I tried `<%= sanitize @html_variant.html.html_safe %>` but that did not resolve the issue.

I just wanted to confirm if  I can replace the current use of html_safe with `<%= sanitize @html_variant.html %>`.

**Comment by maestromac** [comment]
hey @bolariin , `@html_variant` needs use html_safe. Please ignore that lint.
