### ISSUE TITLE
Finalize Article Editor v2

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#272]
This is a pretty good first issue for front-end devs because it's pretty contained, it may be a bit of a time commitment, so not great if you just want to get your feet wet.

We now have the next-gen editor in the works. It should make creating articles simpler and more powerful, while maintaining the basic markdown folks love. Once this is done we will also have a link to the original front-matter form, which we will continue to support.

The new editor is default in development and available in production at https://dev.to/new?state=v2

But it still has some work before it can be really launched.

The big thing is the **tag input autocomplete**, which is pretty janky/buggy/spaghetti code.

And overall the code is hacky and untested.

I may have a few last-mile UI adjustments, but that will be easier once we have the solid base to build off that works well for all users.

Done is better than perfect, but the current code is far from perfect, so this task is to clean things up, fix the bugs, and ship this feature.

Don't worry about whether all the form data gets sent properly if you don't have a great idea of what's going on in the backend, but you can take note of anything that doesn't seem to be working.

### Definition of done

The tag system works properly and the tests are written. Code is probably refactored, but we're not expecting perfection. At that point, I'll make some last-minute adjustments and we'll ship the feature. If you have UI adjustments you'd like to make along the way we can chat about all that as it comes up.

### Notes
The tags are coming over the wire via Algolia. If you don't currently have your tags indexed, open up Rails console and reindex them: `bin/rails c` and `Tag..reindex!`.

**Comment by djhopper01** [comment]
I've started to write some [snapshot tests](https://github.com/thepracticaldev/dev.to/compare/master...djhopper01:feature/finalize-article-editor-v2?expand=1) for this. It's helping me understand how the tags input currently works.

My hope is these tests will come in handy when refactoring.

I have a few thoughts about the code so far, so let me know if my thinking is on track. I could be missing some important context about this, but this is what I've noticed at the moment.

1. It seems like `<ArticleForm />` knows too much about the tags input. It's doing a lot of work for handling tags. I think it's great that it handles the state for tags, but maybe much of this work can be done in `<Tags />`? I was thinking of moving most of the tags handling to `<Tags />`, but still passing in methods as props to change the state.
2. Currently, algolia is only used in `<ArticleForm />` to search for tags. This seems like a good candidate to move to `<Tags />` to get rid of the dependency for `<ArticleForm />`.
3. Rather than using `document.querySelector` to retrieve algolia credentials, maybe we can pass these as props to the component? In the tests I've built so far, I had to build up some of the DOM to render `<ArticleForm />` because of the dependency on `document.querySelector`.

By the way, I don't consider myself a full time front end developer. If anyone else is tackling this already, just let me know. I thought it'd be good to get the conversation going however.

**Comment by donimathis** [comment]
Does this particular project already have someone assigned to it?  How can I help with this project?

**Comment by djhopper01** [comment]
@donita I've started writing tests and refactoring some of the tags input code to get a better understanding of what it's currently doing. That's about it though!

Here's [the branch](https://github.com/thepracticaldev/dev.to/compare/master...djhopper01:feature/finalize-article-editor-v2?expand=1) I've been working on. Apologies for the mess of changes... prettier formatted the js. The main issue I fixed is outlined in https://github.com/thepracticaldev/dev.to/commit/4cf20a39d6c48023d86edbacf347acfbbb86b7e8

@jessleenyc Did you have an idea of how you want the tags input to work?

Based on what I've played around with so far, these seem to be the key points:

1. User can type anything they want. Separate tags with commas. Ultimately, what the textarea contains is what we should submit to the server.
2. As a user types, algolia is searched. This search should work from anywhere in the textarea, even when editing a tag you've already typed. For example, if you currently have "javascript,go,linux", you can change "javascript" to "java".
3. In the case of editing a previously typed tag, clicking on a search result replaces the tag. For example, if you're changing "javascript" to "java", we'd replace "javascript" with "java". This should work from anywhere in the textarea.

That's what I understand so far, but let me know if I'm way off base here.

**Comment by djhopper01** [comment]
Here's what I have so far. I haven't opened a PR yet as it's not tested well enough. I've mainly been exploring how it all was working previously and how it could be improved. I'd still like to extract more of the `<Tags />` behavior into its component as I think `<ArticleForm />` doesn't need to know about much of it.

Here's a gif of where things are:

1. Typing is smooth. No "missed" keys. This was something I saw when playing around with it at first. Took me awhile to figure out what was going wrong though! 😄 
2. You can edit previously typed tags. You also get search results as you're editing.

![aug-20-2018 21-26-25](https://user-images.githubusercontent.com/634902/44375076-c5db6a00-a4bf-11e8-8425-38ddfc79d865.gif)

**Comment by benhalpern** [comment]
Hey @djhopper01 I think you're thinking about this all the right way. I think you're basically spot on with your assessment of the current behavior.

Ultimately the contents of this state element will be submitted as a string.

Other considerations: This should be a max 4 tags, so the last one doesn't need that comma.

If we had automatic spaces after the comma but not allow the user to type a space I think that might be a nice user experience, but wouldn't be necessary.

Overall I think you're totally on the right page.

**Comment by djhopper01** [comment]
@benhalpern Cool, thanks for the good information. I had noticed a check for a maximum, but wasn't quite sure about it so that's great to know. I'll keep pushing forward with this, adding more tests along the way to confirm all of this behavior.

**Comment by donita** [comment]
Okay, I will look through the branch later this evening!
