### ISSUE TITLE
Followers count and total views on user profile.

### ISSUE THREAD

**Issue by UddeshJain** [thepracticaldev/dev.to#2778]
**Is your feature request related to a problem? Please describe.**
Whenever I visit someone's profile, I can't differentiate between the person writing amazing posts and the person here only to read posts.

**Describe the solution you'd like**
There should be followers count and total views count on every person's profile so that people will know the person is an amazing writer and I should follow him/her.

**Describe alternatives you've considered**
It can be an optional feature. User can decide whether he/she should show the information on the profile or not.

**Additional context**
None.

**Comment by Glennmen** [comment]
I believe it was a DEV team decision to not show this because they don't want it to turn into a social media platform where people compared their popularity. Having lots of followers doesn't have any added benefit to the quality of the posts.

You can currently see on a users profile the amount of posts and comments they made and the amount of tags they follow. I don't miss the feature to view how many followers they have.

But stil interested to look at the opinions of other people.

**Comment by Glennmen** [comment]
Also I found an issue about this topic already maybe it can be reopened to continue the conversation, for reference: https://github.com/thepracticaldev/dev.to/issues/396

**Comment by jessleenyc** [comment]
Hey @UddeshJain, thanks for the request. We have deliberately chosen not to show follower/following counts for some of the reasons @Glennmen mentioned above. The best way to determine whether or not someone is posting quality content is by reading their posts! You can also check out the badges on their profile. The 7 Badge means they've made it to our weekly Top 7 post roundup.

It's always possible that we revisit and change our minds about this in the future, but for now, we'll keep these types of counts hidden.
