### ISSUE TITLE
Why there is no check for RSS feed URL

### ISSUE THREAD

**Issue by aimenbatool** [thepracticaldev/dev.to#2795]
**Describe the bug**
I was trying to publish my post from Medium RSS feed. Upon fetching, I got each article twice (duplicate) on my dashboard and when I tried to edit one article and save it, it gave me an error saying that **"Feed source URL has already been taken"**

Why my feed source URL is taken and by whom?

I went to my setting and tried a random Medium feed URL to see if I can get their posts or not. I could see all their posts on my dashboard and I was able to edit and then publish that article. (I didn't let me publish because of the same error.)

**Expected behavior**
It should fetch one article only once and let me edit, save and then publish without any error.

**Comment by maestromac** [comment]
Hey @aimenbatool , sorry you are experiencing this issue. With the nature of how RSS work, there's no fool-proof way to verify a feed's ownership. So yes, it is possible to pull anybody's feed and claim it as yours. But we take article ownership and plagiarism seriously on this platform.

Onto the problem you are experiencing. I was not able to replicate this issue. It seems like there was either a hiccup on our end or on medium's end that led to your feed being pulled in twice. Each article pulled in are tagged with`feed_source_url`, which is the original article's link. You are seeing that error message because your article was potentially pulled down twice.

Have you already removed the duplicate articles? If so, were you able to publish successfully without an issue?

**Comment by aimenbatool** [comment]
Hi @maestromac, Thanks for updating. 

I don't know the reason for getting articles twice and at that time I was also unable to delete duplicate articles because there was no *Delete* button visible to me. But after a few days, I was able to see the delete button so I deleted the repeated articles and then published those. 

Because of duplicate articles, I was also not able to publish them. But It worked fine after a few days and I don't know how.

**Comment by maestromac** [comment]
The missing delete button was a bug that was resolved. That was unfortunate for you to deal with 2 bugs at the same time, sorry about that. We're glad to hear that things are working for you now but please let us know right away if you are experiencing this again.

Closing.
