### ISSUE TITLE
Please add bookmark button/ save button for read later  in article detail page like medium 

### ISSUE THREAD

**Issue by shahzaibanwar009** [thepracticaldev/dev.to#2864]
`**Is` your feature request related to a problem? Please describe.**
UI

Please add bookmark button/ save button for read later  in article detail page like medium

**Comment by rhymes** [comment]
Hi @shahzaibanwar009 - can you please elaborate?

The article page currently has the "save" button.

When you have a wide enough screen is on the left side:

![Screenshot_2019-05-17 The DEV Community - Latest posts](https://user-images.githubusercontent.com/146201/57909555-67db8780-7883-11e9-9cf3-29435d8b47ba.png)

Otherwise it's on the bottom:

![Screenshot_2019-05-17 The DEV Community - Latest posts(1)](https://user-images.githubusercontent.com/146201/57909571-7164ef80-7883-11e9-8666-725ac21e8e29.png)

Hope this is what you were looking for

**Comment by shahzaibanwar009** [comment]
Thanks
