### ISSUE TITLE
Escaping Vue code with backticks works partially

### ISSUE THREAD

**Issue by cfjedimaster** [thepracticaldev/dev.to#2925]
**Describe the bug**
According to the docs, we can escape Liquid tags, Vue tags, with backticks, so: (backtick){{ foo }}(backtick). Not sure how to escape backticks in GitHub, so forgive me. ;)

In my testing this "worked" as in my Vue template tokens showed up, but so did the backticks, you can see it here: https://dev.to/raymondcamden/reading-client-side-files-for-validation-with-vue-js-2io9

**Expected behavior**
I'd expect the backtick to work and *not* render.

**Screenshots**
![image](https://user-images.githubusercontent.com/393660/58126016-8c16cb80-7bd7-11e9-9c97-4d3f84512e17.png)

**Comment by Zhao-Andy** [comment]
Hmm, looking at your post and the screenshot you gave, the text inside `<tr v-for>` _should_ be rendering the single backticks because it's within a codeblock of triple backticks. Perhaps I'm missing something?

If you want to escape Liquid tags/Vue tags (double curly bracket) regularly outside of a codeblock, that's when you would use single backticks.

**Comment by cfjedimaster** [comment]
You know - I think I figured out the issue. When I *originally* posted to my blog, I forgot to escape them. dev.to sucked in that version from RSS, and I bet they were hidden there. So when I fixed it on dev.to, I added the tags AND the backticks. Let me try removing them.

**Comment by cfjedimaster** [comment]
Yep, brain fart on my side. Sorry! :)
