### ISSUE TITLE
Dev.to stopped working on Facebook browser

### ISSUE THREAD

**Issue by I-NOZex** [thepracticaldev/dev.to#3121]
**Describe the bug**
Dev.to pages won't load on Facebook built-in browser 

**To Reproduce**
Open a dev.to link from a Facebook share

**Expected behavior**
Load the page correctly 

**Screenshots**
![error](https://user-images.githubusercontent.com/5805207/59265868-8c3e4000-8c46-11e9-9f96-6a3a8f2f5f73.png)

**Smartphone**

- Device: nubia z17 lite (nx591j)
- OS: Android 7.1.1
- Browser: Facebook (Browser )
- Version: 224.0.0.33.114

**Comment by jessleenyc** [comment]
@maestromac heads up on this.

**Comment by maestromac** [comment]
related https://github.com/thepracticaldev/DEV-Android/issues/36

This turns out to be a [Chromium Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=977784). They've rolled out a fix but it might take additional days for people to receive it. Please try it out and let us know if the issue still persists!

**Comment by I-NOZex** [comment]
Hi, I confirm now that the issue is solved on Facebook for Android v. 226.0.0.49.120
