### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by beatngu13** [thepracticaldev/dev.to#3133]
**Describe the bug**

One of [my articles](https://dev.to/beatngu1101/a-formal-look-at-seleniums-nosuchelementexception) uses various math symbols, which was fine when I wrote and published it. But today I've looked at it again and there are various encoding issues. Besides the math symbols, also plain dashes now cause issues, for instance:

>[…] described situationâ€Š–â€Šthe GUI element identification problem […]

Which once was:

>[…] described situation — the GUI element identification problem […]

You can check the expected behavior on the [Medium version](https://medium.com/@beatngu13/a-formal-look-at-seleniums-nosuchelementexception-bafce97df2e7) of the article.

**To Reproduce**

Go to https://dev.to/beatngu1101/a-formal-look-at-seleniums-nosuchelementexception.

**Expected behavior**

Compare with https://medium.com/@beatngu13/a-formal-look-at-seleniums-nosuchelementexception-bafce97df2e7.

**Desktop (please complete the following information):**

- OS: macOS Mojave (10.14.5)
- Browser: Firefox Quantum (67.0.1, 64 Bit)

**Comment by Zhao-Andy** [comment]
Hey @beatngu13, thanks for the heads up. We'll take a look into it and see what's going on.

**Comment by beatngu13** [comment]
Thanks for looking into it, but the issue has been closed without a comment? I assume you cannot reproduce the original state? I can also manually fix the content, just thought the issue may be interesting for you, too.

**Comment by benhalpern** [comment]
Oh hey sorry my bad @beatngu13 . I meant to comment and then close. I think I had two tabs open and messed this up.

The issue here is related to a somewhat one-off data transfer issue that occurred and affected some old articles, but not a ton. So we are aware of the issue and have done our best to automate the fix where it's simple.

A few fall into edge cases likely outside of what would be simplest to do automatically so if you could manually fix the content that would be great (I wouldn't want to misinterpret something.)

Thanks for making us aware of this. It's largely been dealt with and I think we'll have to continue the rest of the updates on a case-by-case basis. Does that all work for you?

**Comment by beatngu13** [comment]
Sure, thanks for the information. And dev.to! 🙏
