### ISSUE TITLE
Unable to fetch https://github.com/thepracticaldev/acts_as_follower.git while bundle install

### ISSUE THREAD

**Issue by Gaurav-Shankar** [thepracticaldev/dev.to#3174]
I was getting this while doing bundle install.

**Comment by maestromac** [comment]
Thanks for this issue @Gaurav-Shankar . In the future, please use our [help thread](https://dev.to/devteam/devto-open-source-helpdiscussion-thread-v0-1l45) for technical issues.

The reason we are using our fork version of that gem is because the original gem has been inactive for a bit now. Have you tried the suggestion from your terminal to remove the cache directory?

**Comment by maestromac** [comment]
I assume this issue is resolved. If you need anymore help please let me know!
