### ISSUE TITLE
Reading time estimate is inconsistent across pages

### ISSUE THREAD

**Issue by tducasse** [thepracticaldev/dev.to#3257]
**Describe the bug**

The time estimate is not the same in the search results and if you go to the article.

I _think_ some of them are right? I'd say the one in the search results seems smaller.

**To Reproduce**
Either:
- click [here](https://dev.to/archiewald/create-react-app-with-typescript-tutorial-291d)
- and [here](https://dev.to/search?q=create%20react%20app%20with%20typescript%20tutorial)

Or:
- go to the search bar
- type something
- choose an article, read the time estimate
- click on the article, check the estimate

**Expected behavior**

Both estimates should be the same.

**Screenshots**

<img width="623" alt="Screen Shot 2019-06-21 at 9 22 11 pm" src="https://user-images.githubusercontent.com/11507599/59920233-356a0f00-946d-11e9-8461-7388c7b9e7bd.png">
<img width="534" alt="Screen Shot 2019-06-21 at 9 22 21 pm" src="https://user-images.githubusercontent.com/11507599/59920234-356a0f00-946d-11e9-87f1-28b239cf1bf0.png">

**Desktop (please complete the following information):**

- OS: Mac OS Mojave 10.14.5
- Browser: Chrome
- Version: 75.0.3770.100

**Comment by rhymes** [comment]
I think it's because the search results come from the search index and it hasn't probably been updated.

Nonetheless the logic here:

https://github.com/thepracticaldev/dev.to/blob/e46bd26223847e35b9de2cd57380bad12a97286f/app/assets/javascripts/utilities/buildArticleHTML.js.erb#L100-L104

should be similar to this one:

https://github.com/thepracticaldev/dev.to/blob/e46bd26223847e35b9de2cd57380bad12a97286f/app/views/articles/_single_story.html.erb#L54-L58
