### ISSUE TITLE
Vertical Scrollbar toggles on and off with every other character inputted

### ISSUE THREAD

**Issue by dylanesque** [thepracticaldev/dev.to#3330]
**Describe the bug**
When inputting text in the post editor in a document long enough to make the vertical scrollbar necessary (around line 21 or so), the scrollbar toggles on and off (rather, appears and disappears) with every character inputted, causing an annoying page jump when writing.

**To Reproduce**
Edit a document of x length as described above to see the behavior.

**Expected behavior**
Expected behavior is that the vertical scrollbar appears when needed and stays there.

**Desktop (please complete the following information):**

- OS: Windows 10 (64-bit)
- Browser: Google Chrome
- Version: 75.03

**Comment by Zhao-Andy** [comment]
Thanks for the bug report! We'll take a look into it.

**Comment by Almenon** [comment]
I got the same problem. I'm investigating it.

**Comment by dylanesque** [comment]
Weirdly, I haven't seen this big consistently across posts. It seems to pop up if text is copied from elsewhere, like another markdown file.

**Comment by Almenon** [comment]
It happens when the line of text is more than 20 lines down and you have a space going outside with width of the textarea. It's a bit more complicated than that and rather finicky to reproduce. It's easier to run into the problem in the V1 editor - I ran into it twice in a row just randomly. But it can still happen in V2 as well.

https://i.imgur.com/f9xnKIC.gifv

https://i.imgur.com/WjiePDj.gifv

I'm thinking I might be able to do a easy fix by just applying an `overflow:hidden` style to disable the scrollbars (you have scrollbar on far right of page anyways) but I still need to test it in Firefox. Do you have a mac you can test `overflow:hidden` in safari with by any chance?
