### ISSUE TITLE
Give users more control of their feeds

### ISSUE THREAD

**Issue by MatMoore** [thepracticaldev/dev.to#340]
### User Story / Description
I want to be able to be able to curate a feed around topics that interest me, so I can stay up to date and participate in discussions about them.

My understanding of the "feed" feature is I subscribe to topics and people, then a mysterious algorithm decides what I should read.

Some content is not obviously related to anything I follow. For example, it shows me something tagged to `#javascript`, `#node`, `#podcast` and `#news` when I don't follow any of those topics. I can't actually tell if my choices have influenced the feed at all, so I don't know if I'm fundamentally misunderstanding how dev.to works.

Either way, it's hard to curate what I follow, and I dislike the feed feature because it encourages this addictive behaviour of just endlessly scrolling through content, which is not really what I want to get out of the platform. 🙁 

### Definition of Done
This could go in different direction, but the feed should be optimised for [happiness rather than engagement](https://medium.com/thrive-global/the-apps-that-make-us-happiest-are-the-ones-we-spend-the-least-time-with-d2bbb56855fa).

Users should either be able to control what goes into their feed or disable it altogether. It shouldn't be infinite or padded with irrelevant content. One thing that might help is the ability to block topics or people from appearing the feed. We could also include an explanation of why each item has been selected for the feed so that the user has some way to influence it.

I'm a new contributor but I would be happy to work on this if people think it's worth working on.

**Comment by benhalpern** [comment]
100% on-board. I'd push back against the notion that we can create anything that nobody would feel is ever "padded with irrelevant content", and as much as we can, we are definitely trying to optimize for happiness rather than engagement. I could have created this type of issue myself.

Currently the top three posts are shared amongst the whole community and everything else is based on your follows. The shared thing is partly for user experience (perhaps there should be some globally shared things) but mostly because we've grown in terms of size and that model no longer makes sense. There is also the performance benefits of shared context which we are not ready to lose, but we won't have to, it's just a constraint.

Some of the answers here are not easy and we may not agree on everything but we can definitely work towards the ideals outlined here.

One thing I've had some thoughts about experimenting with is having more than one version of the home page people can choose from if they want to, so rather than solve all problems for everyone with the "main" one, we can look to accommodate users with different tastes in different ways.

Love this issue as a guiding light. I'm already thinking about some actionable things we can do to make things better and clearer, and we can go from there. I'll have a specific issue or two written up by tomorrow.

Any further input on the subject is super appreciated at any point.

**Comment by michaelgv** [comment]
I feel an option to disable globally shared would be useful for user experience, ie, I can click a button that will disable global posts and only filter on the tags and users, and allow me to refine further, ie: only show user posts I follow which have X tags

**Comment by pkfrank** [comment]
I've been noodling about this issue over the past week.  Currently, there are a few views that offer a bit more "control" for exploring new content around the site than the main feed:

1) You can browse site-wide **new articles** in the [Global Latest](https://dev.to/latest) view.
2) You can browse tag-specific **new articles** in the [Tag-Specific Latest](https://dev.to/t/javascript/latest) view
3) You can browse **new comments** posted into your Saved Articles through the [Reading List](https://dev.to/readinglist?v=comments) view.

I think a good blend of offering more control would be to build an "Activity Explorer" view to augment/replace the current "Global Latest."  

Some of the details / naming would need work, but my initial thought is that the "control" would come in via the sidebar.  It would have filtering options that would allow you to explore by:

```
- Global
- Users You Follow
- On Your Saved Posts

- Comments Only
- Articles Only
(default is both)

- tag list
- tag list
- tag list
```

Here's a rough mockup:
![Activity Explore Mockup](https://cl.ly/02c1be861a08/Image%202018-08-22%20at%2011.09.09%20AM.png)

I feel like this view would be sort of tucked away for most users, but would offer a lot more granular control and freedom for power users.  I'm sure that @benhalpern will have some much-needed insights into the feasibility of this all.  I imagine this might be "blocked" — at the very least — until we [rewrite the search page in Preact](https://github.com/thepracticaldev/dev.to/issues/360#issuecomment-413649247) as Ben mentioned in #360.

What do you think, @MatMoore and @michaelgv ?

**Comment by benhalpern** [comment]
I'm really glad we're having this convo. This is an incredibly nuanced discussion and really central to the core platform mechanics—which is what makes it so difficult.

I'll try to add more to the convo when I get a chance to really get my thoughts down. We'll make some things happen for the better one way or another.

**Comment by benhalpern** [comment]
Hey @MatMoore stalebot got to this last week, but we are currently shipping a really helpful feature for this issue:

https://github.com/thepracticaldev/dev.to/pull/1229

Thanks for your patience ❤️

**Comment by MatMoore** [comment]
Awesome, this looks very interesting!
