### ISSUE TITLE
Get dashboard stats from the API

### ISSUE THREAD

**Issue by pacoita** [thepracticaldev/dev.to#3424]
**Is your feature request related to a problem? Please describe.**
I would like to be able to get my personal statistics (followers, views) as I get them in my dashboard.

With the endpoint "https://dev.to/api/articles?username=MyUserName" I can get some data (like positive reactions or comments), but not the views and followers.

**Describe the solution you'd like**
I would like to be able to fetch the personal metadata as seen in the dashboard by providing my personal token as api-key.

**Additional context**
I tried to call the `https://dev.to/api/analytics/historical` endpoint, but I always get an `401 Unauthorized `error (probably it is not *open*?).

**Comment by benhalpern** [comment]
Hey, this functionality will be available soon. We're rolling out advanced stats as part of a pro feature which will go live within a week or so.

We're starting with pro because we'd rather fully support this for users who want it most rather than trying to water it down for the need to scale to the entire userbase. If we get to the point where it's comfortably scaling it will go to general availability. This is pretty much the pattern we'll be using for pro accounts. They'll get bleeding edge functionality so we can deliver stuff like this at a faster pace.
