### ISSUE TITLE
figcaption tag is behind image

### ISSUE THREAD

**Issue by eusonlito** [thepracticaldev/dev.to#3439]
**Describe the bug**
For example on article https://dev.to/linuxfuture/icon-fonts-vs-svgs-an-ultimate-guide-to-accessible-web-icons-2lh6 the `<figcaption>` tag is behind the image.

**To Reproduce**
1. Go to article https://dev.to/linuxfuture/icon-fonts-vs-svgs-an-ultimate-guide-to-accessible-web-icons-2lh6
2. Scroll down to first image

**Expected behavior**
`<figcaption>` tag on correct position.

**Screenshots**

![dev to figcaption](https://user-images.githubusercontent.com/644551/60987393-cbdd7200-a341-11e9-8184-2fa212932998.jpg)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.2 LTS
- Browser: Google Chrome
- Version: Version 76.0.3809.46 (Official Build) beta (64-bit)

**Comment by maestromac** [comment]
Thanks for reporting this @eusonlito !

**Comment by Elecweb** [comment]
@maestromac `figcaption` has `margin-top: -0.8em;`

https://github.com/thepracticaldev/dev.to/blob/567579daf3df42efbe92c094f774d971e87b254a/app/assets/stylesheets/article-show.scss#L546-L548

it looks great when it's next to `p` element, so I think we can use selector like this ?
```
p + figcaption {
    margin-top: -0.8em;
}
```

**Comment by maestromac** [comment]
@Elecweb that seems fine. Be sure to test it with [this article](https://dev.to/maestromac/vim-wont-make-you-a-more-productive-developer-h9f) too since the figcaption isn't causing a problem there.

**Comment by scottaohara** [comment]
per the referenced instance of the `figcaption`, it's used incorrectly as well, as it is not meant to be used outside of being a direct child of a `figure` element.

If adding the `figure` element to correctly wrap the `img` and `figcaption`, the text does not get positioned behind the `img`.

**Comment by rianadon** [comment]
Since many articles contain markdown like:
```html
<img src="fig.png" />
<figcaption>My yummy fig</figcaption>
```

What would be the correct way to wrap these elements into `figure` elements? Should we always assume that whenever someone uses a `figcaption`, the item above is the corresponding element of the figure? I have a sad feeling someone out there is relying on `figcaption` tags to not be wrapped as [part of their workflow](https://xkcd.com/1172/). Or, since adding a `figure` shouldn't affect the layout of the page at all, maybe this is ok.

Otherwise, whether we introduce `figure` tags or not, @Elecweb's solutions seems necessary.

**Comment by scottaohara** [comment]
>What would be the correct way to wrap these elements into figure elements?

since a `figcaption` is only a valid child of a `figure`....within a `figure`.

>Should we always assume that whenever someone uses a figcaption, the item above is the corresponding element of the figure?

That is often how they're used...though the HTML spec does allow for a `figcaption` to be placed above or below the said content of the `figure`, below is more often than not the manner in which authors use the `figcaption`.

>I have a sad feeling someone out there is relying on figcaption tags to not be wrapped as part of their workflow.

i mean, yeh.  there are likely a lot of people out there that rely on browsers correcting shit markup practices for them.  I'd submit an adequate response to the code example you posted would be to either attempt to create valid markup, or to kill the `figcaption` all together, since it's only allowed parent element is a `figure` element.
