### ISSUE TITLE
Ignore validation for github and twitter username, if they didn't change

### ISSUE THREAD

**Issue by markfrst** [thepracticaldev/dev.to#346]
### Current Behavior
When i tried change profile image, i get error validation:
![image](https://user-images.githubusercontent.com/4071096/44053025-dea61354-9f57-11e8-829e-a93fd1a327de.png)
but i didn't change my github and twitter username
### Expected Behavior
I think need ignore validation this fields if they not changes
### Additional Info (device/browser, helpful links)
Browser: Chrome
Page: https://dev.to/settings

**Comment by jessleenyc** [comment]
Hey @markfrst, this is happening because it looks like you have two accounts with us. This usually happens if you logged in once with twitter, and separately with github but then tried connecting the two accounts. We're working on making it easier for people to merge their own duplicate accounts but for now we need to handle it on our admin end. Would you mind sending us an email at yo@dev.to so we can confirm some things with you and take care of this?

**Comment by markfrst** [comment]
@jessleenyc thanks
