### ISSUE TITLE
Throw a proper error and message for Jekyll links

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#3470]
**Describe the bug**
There are some cases where someone might be copying and pasting or importing in general their post from their Jekyll blog. AFAIK Jekyll also uses Liquid syntax, and this seems to be a common way to link something:
```
[my example]({% link https://github.com/something/something-else %})
```

Interestingly, this renders in preview with a link that sends you to `https://dev.to/{% link https://github.com/something/something-else %}`.

When attempting to save the draft or publish though, it will throw a 500 error and not identify what exactly went wrong.

**To Reproduce**
1. Go to the editor (v1 or v2, doesn't matter)
2. Copy and paste this markdown:
```
[my example]({% link https://github.com/something/something-else %})
```
3. Click preview (it should send a proper preview)
4. Click "Save changes" or "Save draft"  or "Publish"
5. Get 500 error

**Expected behavior**
The error should be handled properly by our parser and should throw an understandable error message, like: `Markdown parsing error! [my example]({% link https... %}`

Possible related files:
- https://github.com/thepracticaldev/dev.to/blob/master/app/labor/markdown_parser.rb
- https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/article-form/elements/errors.jsx
- https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/article-form/elements/bodyMarkdown.jsx
- https://github.com/thepracticaldev/dev.to/blob/master/app/javascript/article-form/actions.js

**Comment by bolariin** [comment]
The PR #3608 resolves the 500 error.

It looks like the reason why a link appears in preview without an error is because of `sanitize_rendered_markdown` in `markdown_parser.rb`. It turns the example link from `[my example]({% link https://github.com/something/something-else %})` to 
`<p><a href="%7B%%20link%20/sherri_mrs_effertz/as-i-lay-dying-a1c%20%%7D">my example</a></p>`. 

https://github.com/thepracticaldev/dev.to/blob/e5deb9f431b12746e404167ec5c3553e5fa17107/app/labor/markdown_parser.rb#L16-L18

Due to the liquid tag parsing happening after the `santized_rendered_markdown`, it does not detect the link tag.

**Comment by jessleenyc** [comment]
I'm going to close this since the Jekyll links are now supported.
