### ISSUE TITLE
Integration with google analytics or similar?

### ISSUE THREAD

**Issue by marianopeck** [thepracticaldev/dev.to#3472]
**Is your feature request related to a problem? Please describe.**
I am trying to move away from my wordpress blog into dev.to. However, one of the major drawbacks I see is the lack of proper analytics. I can just see number of visits and reactions. That's all. I cannot see where the visits come from, which country, etc tc.

**Describe the solution you'd like**
Either improve the analytics or allow binding your own posts / profile with a third party lib like google analytics

**Comment by jessleenyc** [comment]
Hey, this functionality will be available soon. We’re rolling out advanced stats as part of a pro feature which will go live within a week or so.

We’re starting with pro because we’d rather fully support this for users who want it most rather than trying to water it down for the need to scale to the entire userbase. If we get to the point where it’s comfortably scaling it will go to general availability. This is pretty much the pattern we’ll be using for pro accounts. They’ll get bleeding edge functionality so we can deliver stuff like this at a faster pace.

**Comment by marianopeck** [comment]
Hi @jessleenyc 
Thanks for the answer. Where can I read more about pro accounts? I cannot seem to find anything through the website...I mean, what are the extra features, pricing, etc...
I will be done with a RTFM :)
Thanks!

**Comment by Glennmen** [comment]
@marianopeck I don't think this has been released yet: https://github.com/thepracticaldev/dev.to/pull/3461

**Comment by marianopeck** [comment]
Ahhh ok. I misunderstood then the `This is pretty much the pattern we’ll be using for pro accounts.`. Made me thought the pro accounts were already in place since some time. 
OK....eager to wait for the Pro accounts then!
