### ISSUE TITLE
Can't tag user in italics

### ISSUE THREAD

**Issue by Glennmen** [thepracticaldev/dev.to#3493]
**Describe the bug**

When tagging a user in an article inside an italics block the link to the user profile isn't added.
https://dev.to/glennmen/contributing-to-improve-yourself-2pkg

**To Reproduce**

1. Create a new post
2. Add an italics block with inside a user tag `@ben`

**Expected behavior**

Even in italics the user tag should work.

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

Doesn't work:
```
_This piece was originally written for [Your First Year in Code](https://leanpub.com/firstyearincode) by @isaacdlyman. Even though it didn't make it in the book I still wanted to share it with the community and hope that it helps at least a couple of people with some of the tips._
```

Possible workaround:
```
_This piece was originally written for [Your First Year in Code](https://leanpub.com/firstyearincode) by_ @isaacdlyman. _Even though it didn't make it in the book I still wanted to share it with the community and hope that it helps at least a couple of people with some of the tips._
```

**Comment by JoelMontano** [comment]
I could grab this!

**Comment by Zhao-Andy** [comment]
@JoelMontano go for it!

**Comment by notapatch** [comment]
So the issue is in markdown parser, here it's getting a list of children nodes under the body node and then searching for any text nodes. When you add an italic then it makes an `<em>` node' and the text node gets added to it making the text node a grandchild of the body - which means it will never get seen. 

```
Without italic
[body]---[text with @mention]

With italic
[body]---[em]--[text with @mention] 
```

```
  # markdown_parser.rb
  def wrap_mentions_with_links!(html)
    ...
    # give me all the nodes under body but not ones with css class highlight
    html_doc.xpath("//body/*[not (@class='highlight')]").each do |el|
      el.children.each do |child|
        if child.text?
          new_child = child.text.gsub(/\B@[a-z0-9_-]+/i) do |s|
            user_link_if_exists(s)
          end
          child.replace(new_child) if new_child != child.text
        end
      end
    end
   ...
```

So I was thinking of two solutions

1) A more complicated XPath solution which could return (all text nodes beneath body  - nodes under class=".highlight") - I have not managed this but maybe someone with better XPath skills could.

2) Recursive parse_children function - I've done this but you may not want the additional complication of recursive code which _might_ be avoidable with better XPath skills - it would be something like this.

```
  def wrap_mentions_with_links!(html)
    html_doc = Nokogiri::HTML(html)
    html_doc.xpath("//body/*[not (@class='highlight')]").each do |el|
      parse_children(el.children)
    end
    if html_doc.at_css("body")
      html_doc.at_css("body").inner_html
    else
      html_doc.to_html
    end
  end

  def parse_children(children)
    children.each do |child|
      if child.text?
        new_child = child.text.gsub(/\B@[a-z0-9_-]+/i) do |s|
          user_link_if_exists(s)
        end
        child.replace(new_child) if new_child != child.text
      else
        parse_children(child.children)
      end
    end
  end
```

(I'm only commenting on it and not claiming the issue - because I'm not in position to put in a pull request yet)
