### ISSUE TITLE
Why there is a hideous white bar under the code block?

### ISSUE THREAD

**Issue by wheatup** [thepracticaldev/dev.to#3544]
**Describe the bug**
There's a white block under each `pre` block that I'm not sure it's a feature or something. Just doesn't look right :/

**To Reproduce**
Navigate to a post that has code blocks:

[https://dev.to/thepracticaldev/daily-challenge-24-shortest-step-41o3/comments](https://dev.to/thepracticaldev/daily-challenge-24-shortest-step-41o3/comments)

**Screenshots**
<img width="848" alt="Screen Shot 2019-07-26 at 11 50 33" src="https://user-images.githubusercontent.com/6663691/61922679-40e4b480-af9c-11e9-876e-dfe23a939ece.png">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome 
- Version: Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by wheatup** [comment]
I think you need to add `overflow-x: auto;` to the `<pre>` block..

**Comment by rhymes** [comment]
The answer to your question is: because there might be a bug somehow, there's no actual reason :-)

Interestingly enough I don't see the bar in either Firefox 69 nor Chrome 75.0.3770.142 on macOS 10.14.6

Firefox:

![Screenshot_2019-07-26 Discussion of Daily Challenge #24 - Shortest Step](https://user-images.githubusercontent.com/146201/61931483-fe61ae80-af80-11e9-97ab-9fc4cfe01f70.png)

Chrome:

![Screenshot 2019-07-26 at 8 39 42 AM](https://user-images.githubusercontent.com/146201/61931510-10dbe800-af81-11e9-809a-dceaa7db9e8f.png)

Same with Safari.

I have tried to resize the windows in many different ways but the bar doesn't appear.

Could you have by any chance any extension that works on the DOM?

**Comment by wheatup** [comment]
> The answer to your question is: because there might be a bug somehow, there's no actual reason :-)
> 
> Interestingly enough I don't see the bar in either Firefox 69 nor Chrome 75.0.3770.142 on macOS 10.14.6
> 
> Firefox:
> 
> ![Screenshot_2019-07-26 Discussion of Daily Challenge #24 - Shortest Step](https://user-images.githubusercontent.com/146201/61931483-fe61ae80-af80-11e9-97ab-9fc4cfe01f70.png)
> 
> Chrome:
> 
> ![Screenshot 2019-07-26 at 8 39 42 AM](https://user-images.githubusercontent.com/146201/61931510-10dbe800-af81-11e9-809a-dceaa7db9e8f.png)
> 
> Same with Safari.
> 
> I have tried to resize the windows in many different ways but the bar doesn't appear.
> 
> Could you have by any chance any extension that works on the DOM?

Sorry, this page, with `/comments` 

https://dev.to/thepracticaldev/daily-challenge-24-shortest-step-41o3/comments

**Comment by rhymes** [comment]
@wheatup that's where I got the screenshots from, I don't see it. Can you check with Firefox on your machine and with Chrome with extensions disabled? Thank you

**Comment by wheatup** [comment]
Yep, I checked with firefox(just downloaded), safari and chrome incognito mod(no extension), still appears. I even checked with my windows pc :/
<img width="1286" alt="Screen Shot 2019-07-26 at 18 54 29" src="https://user-images.githubusercontent.com/6663691/61943626-d3a24500-afd6-11e9-9429-20c763bca436.png">

**Comment by rhymes** [comment]
Thank you for testing. It is weird indeed.

**Comment by Zhao-Andy** [comment]
For anyone interested in this, you can add the relevant CSS as @wheatup mentioned:

> I think you need to add overflow-x: auto; to the <pre> block..

The best file is probably `app/assets/stylesheets/comment.scss`.
