### ISSUE TITLE
Add more filters when searching for posts

### ISSUE THREAD

**Issue by domcorvasce** [thepracticaldev/dev.to#360]
### User Story / Description

When searching for posts, I would like to be able to filter the given results by their likes, comments and publishing date.

### Definition of Done

I've a filter section right above the posts feed when searching for posts and I can adjust results by filtering posts by their reception, publishing date or comments received.

**Comment by benhalpern** [comment]
Yeah, we have this in the plans. First step is we need to rewrite the page in Preact. The current one is Vanilla and just needs to be ported because extending the search filters needs to be state-driven. It's not an overly complicated view so shouldn't be too hard.

@nickytonline we had discussed you taking this next as a follow-up on the search box but let me know what your timeline will be, if anyone else might grab this.
