### ISSUE TITLE
File is deleted after executing test suite

### ISSUE THREAD

**Issue by cyrillefr** [thepracticaldev/dev.to#3731]
**Describe the bug**
The following file is deleted while going through the test suite:
`spec/support/fixtures/approvals/liquid_tweet_tag_spec.received.html`

**To Reproduce**
`rspec spec/liquid_tags/tweet_tag_spec.rb:24`
(It "renders properly ...)

**Expected behavior**
The file should not be deleted

**Screenshots**

**Desktop (please complete the following information):**
not applicable

**Smartphone (please complete the following information):**
not applicable

**Additional context**
Chromium 76 installed to handle Selenium tests, on Ubuntu 19.04

**Comment by jessleenyc** [comment]
Very interesting, confirmed that I can replicate this.

**Comment by johncurcio** [comment]
If we look at the files in ``spec/support/fixtures/approvals/``, all of them are ``.approved`` except for this one which has both an ``.approved`` and a ``.received`` file.

![fixtures](https://user-images.githubusercontent.com/9089551/63643372-46b9dc80-c6a5-11e9-9dc5-c3bf431fdab4.png)

According to the [github page for approvals](https://github.com/kytrinyx/approvals):

```
If the contents of the received file is to your liking, you can approve the file by renaming it.

mv my_spec.received.txt my_spec.approved.txt
```

This probably means that at some point ``spec/support/fixtures/approvals/liquid_tweet_tag_spec.received.html`` was approved, renamed, but was not removed from git history.

If we look at [the source code for Approvals.verify](https://github.com/kytrinyx/approvals/blob/7977db195ac062625d6a43ed9f4ef32c8e71896a/lib/approvals/approval.rb#L41), it creates a ``.received`` file from an object, looks for an ``.approved`` file, check if they match, and then deletes the ``.received`` if the match is successful, so this seems to be the expected behaviour. 

The correct thing to do here would be to actually **delete this file and commit the changes**.
