### ISSUE TITLE
Create page with links for official iOS and Android apps

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#3736]
**Is your feature request related to a problem? Please describe.**
As a user, I want to find the official mobile apps in one organized page.

As an admin, I want to easily be able to send people to a specific URL where they can find the apps.

**Describe the solution you'd like**
A page at `dev.to/apps` (or similar) with the download links.

**Additional context**
- [iOS link](https://apps.apple.com/us/app/dev-community/id1439094790)
- [Android link](https://play.google.com/store/apps/details?id=to.dev.dev_android&hl=en_US)

**Comment by jessleenyc** [comment]
I like dev.to/download 😁

**Comment by johncurcio** [comment]
Hello, I would like to work on this issue :). My initial idea would be to create a page similar to ``/connect``, like this:

![downloads](https://user-images.githubusercontent.com/9089551/63392716-1c5add00-c38e-11e9-9dce-949e12c455cb.png)

Any feedback is appreciated. 

The route, however, would have to be ``dev.to/apps`` or ``dev.to/downloads`` (plural), because ``dev.to/download`` is taken. 

Furthermore, where should I put a link to this page? The footer?

**Comment by jessleenyc** [comment]
Hey! I think this looks really great. I think we could add a link in the 'key links' area on the left hand side bar as well as the 'key links' page that's accessed from the main drop down on your profile pic!

**Comment by jessleenyc** [comment]
Also dev.to/downloads works! We can also make some last minute adjustments on that.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/3798
