### ISSUE TITLE
Welcome post or other replies not shown

### ISSUE THREAD

**Issue by eyp** [thepracticaldev/dev.to#3746]
As a new user I wanted to post a presentation post in the Welcome thread, so I wrote it and everything seemed to be fine (the post was there at the top pf the other posts), but then, when I reload the page, it isn't there anymore.

I also replied another of the welcome post, my reply was there when I did it, but afterwards is not.

**To Reproduce**

1 - Go to the welcome thread: https://dev.to/welcome (it goes to  https://dev.to/thepracticaldev/welcome-thread-v36-3dem)
2 - Write the post and submit.

![image](https://user-images.githubusercontent.com/1089286/63244238-2204d580-c25d-11e9-8c8c-9fc471c0b747.png)

3 - Reload the page.
4 - The post is not there anymore.

- OS: Windows 10
- Browser: Brave
- Version: 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)

**Additional context**

New user.

**Comment by jessleenyc** [comment]
Hey @eyp! We don't sort comments by latest, and since there were so many comments on that thread, yours was not at the top. If you click on 'View All Discussions' you should be able to see your post. Here's a link to see all comments directly: https://dev.to/thepracticaldev/welcome-thread-v36-3dem/comments 

We actually just created a new welcome thread because the one you were in got so long! Feel free to re-introduce yourself in that one if you'd like :)

I'm going to close this because I don't think there was an actual bug but please leave another comment if I'm mistaken and I'll reopen it!
