### ISSUE TITLE
Support for runnable kotlin snippets

### ISSUE THREAD

**Issue by jmfayard** [thepracticaldev/dev.to#3776]
**Is your feature request related to a problem? Please describe.**

`thepracticaldev` has support for runnable code snippets, which is really nice, 

Example: `{% codepen https://codepen.io/twhite96/pen/XKqrJX %}`

I want runnable snippets for my favorite programming language: Kotlin

**Describe the solution you'd like**

https://play.kotlinlang.org  is an online sandbox to explore Kotlin programming language. 

See an example of runnable embedded snippet in Kotlin: 

https://play.kotlinlang.org/byExample/05_Collections/01_List

![image](https://user-images.githubusercontent.com/459464/63345016-0af3df80-c352-11e9-908f-11c1f1eeca16.png)

I can define my own snippet and link it like this: 

https://pl.kotl.in/zYp4eGLeP

The embedded code is then this:

`<iframe src="https://pl.kotl.in/PeS0lkpou?theme=darcula"></iframe>`

Suggestion: add a liquid tag for kotlin

**Comment by Zhao-Andy** [comment]
Thanks for the feature request! If it's simply an embedded iframe then following the code examples from the [CodePen](https://github.com/thepracticaldev/dev.to/blob/master/app/liquid_tags/codepen_tag.rb) or the [Repl.it](https://github.com/thepracticaldev/dev.to/blob/master/app/liquid_tags/replit_tag.rb) should work. We have other similar liquid tags, all under `app/liquid_tags` as well.

For anyone who wants to work on this, I think we'll probably want these specs:
1. embed the Kotlin Liquid tag in the editor like so: `{% kotlin https://pl.kotl.in/zYp4eGLeP %}`
2. display the iframe
3. have tests to go along with it

**Comment by jessleenyc** [comment]
Here's some more info on liquid tags: https://docs.dev.to/frontend/liquid-tags/

**Comment by jmfayard** [comment]
I gave it a try but I don't know ruby or rails, so that probably need more work :)

**Comment by jmfayard** [comment]
@Zhao-Andy
Giving it a try taught me that there is a better way than using the iframe. 
The npm package `kotlin-playgroung` should be installed like explained here.
Would that be ok?
https://jetbrains.github.io/kotlin-playground/examples/

**Comment by Zhao-Andy** [comment]
@jmfayard I haven't given it a review yet, but my initial thoughts are that I'm more in favor of using the iframe instead of adding the package. This feature should be more for embedding examples you've made before for a post, and less for a place to test and sandbox code. Since we're embedding a runnable codeblock in an article, I don't think we would need to use the full extent of the package, and therefore don't need to include it in our bundle. 

Also, It weighs in at about ~423.2kb according to [Bundlephobia](https://bundlephobia.com/result?p=kotlin-playground@1.20.0), which seems like extra weight for something we might not be able to use completely.

I'll read the link you shared and give a proper review soon, but if you could share your thoughts on the benefits of it having included as a package over an iframe that'd be great. Perhaps I'm misunderstanding this; if so, probably cause I didn't give a proper review. 🙃

**Comment by jmfayard** [comment]
@Zhao-Andy the advantage would be that we could manage both the code snippets and the text in one markdown document like this:

```
This is how you do an hello-world in Kotlin

 ```run-kotlin 
fun main(args: Array<String>) {
    println("Hello, World!")
}
. ```

```

That could make sense if we can manage to load the javascript only for articles tagged with `#kotlin`

But that's for later, maybe. 

I had another simpler problem in mind yersterday, the iframe didn't look like it should. I didn't realize every kotlin playground has two URLs, one for editing and the other for embedding. 

I have updated the PR https://github.com/thepracticaldev/dev.to/pull/3801

**Comment by maestromac** [comment]
resolved with https://github.com/thepracticaldev/dev.to/pull/3801
