### ISSUE TITLE
&amp in Org Name

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#3779]
**Describe the bug**

When creating an org, if a user puts an ampersand (`&`) in the title of their org, it's shown as `&amp;`.

Here's an image:

![https://cl.ly/b810132a574b/Image%202019-08-20%20at%201.27.28%20PM.png](https://cl.ly/b810132a574b/Image%202019-08-20%20at%201.27.28%20PM.png)

**Expected behavior**

The ampersand should show up as normal.

**Comment by michael-tharrington** [comment]
Here's the test org I created - https://dev.to/atestorganization ... happy to delete whenever.

**Comment by johncurcio** [comment]
Well, I think the culprit is here https://github.com/thepracticaldev/dev.to/blob/39618f66a2167e88e65527b68d0fd996f0869c0a/app/controllers/organizations_controller.rb#L73

According to issue [28060 on the rails project](https://github.com/rails/rails/issues/28060), strip_tags since v1.0.3 encodes special html characters (&, <, > ...) by default. To restore its previous behaviour, we can use Loofa directly:

```
Loofah.fragment(value).text(encode_special_chars: false)
``` 

 **This solution, however, does *NOT* fix existing organizations.** 

Another way to fix this would be to mark the fields in the view ``app/views/users/_profile_header.html.erb`` as ``raw`` or ``html_safe``. This solution DOES fix existing organizations, but it won't scale well: we would have to mark every existing that accepts & (and any new ones we might add in the future) as ``raw`` before displaying it.

I'd love to make a pull request to fix this issue later today, but I want to make sure these solutions don't introduce a sneaky security bug.
