### ISSUE TITLE
Notification time display is glitchy...

### ISSUE THREAD

**Issue by CalinZBaenen** [thepracticaldev/dev.to#4023]
**Describe the bug**

So you know how a notification system works, right? Shown in an orderly fashion from most recent to least. Well DEV's notification clock decided to take a break...
I got a post for 2 minutes ago, and it has already been an hour and I refreshed (even used the DEV app) (So the clock isn't updating the upload time), then a comment from "14" hours ago, after a post from..... 4 minutes ago..... WHAT!?!?

**To Reproduce**

I don't know how, it just happened....

**Expected behavior**

**Screenshots**

Notification view:

![chrome_2019-09-14_00-30-23](https://user-images.githubusercontent.com/50878485/64903948-a6dde600-d687-11e9-821f-8abe46cf5457.png)

Full view:

![chrome_2019-09-14_00-30-32](https://user-images.githubusercontent.com/50878485/64903947-9f1e4180-d687-11e9-8360-51d36fe5f71d.png)

**Desktop (please complete the following information):**

- OS: Windows 10 (dev.to website) / Amazon Kindle Fire Tablet (DEV app)
- Browser: Chrome / (App)
- Version: (Chrome) 76.0.3809.132 (Official Build) (64-bit) (cohort: Stable)

**Smartphone (please complete the following information):**

- Device: Amazon Kindle Fire
- OS: Android 
- Browser: N/A
- Version: N/A

**Additional context**

**Comment by rhymes** [comment]
I noticed the same, I think the bug is a combination of caching and how those "times ago" times are rendered.

I think all of the "times ago" string are rendered server side and part of the cache which, if not perfectly orchestrated, means that you'll likely get stale content. I haven't looked at the caching strategy for notifications yet but it could have bugs.

The notification itself can be fully cached once created, but the time is a moving target and I believe we should just cache the timestamp and have the client side calculate the "time ago" on rendering.

**Comment by CalinZBaenen** [comment]
@rhymes Yea, and I don't receive any new notifications (or I am not getting any...), so It's just broken......

**Comment by phillipknight** [comment]
Getting this consistently, including "5 hours ago" for a post 5 days ago and "2 minutes ago" for a post 7 days ago.

**Comment by msfjarvis** [comment]
From what I can tell the clock stops updating as soon as you open the notifications view. The last post in the screenshot was posted on [19th of September](https://dev.to/devteam/welcome-to-the-big-thread-club-yaser-al-najjar-you-are-the-latest-winner-of-the-big-thread-badge-ni2) while the one before it was posted on [20th of September](https://dev.to/jess/what-was-your-win-this-week-301d).

![image](https://user-images.githubusercontent.com/13348378/65389970-94933480-dd78-11e9-87b6-2ff00d78f599.png)

**Comment by rhymes** [comment]
So, I checked the code and we essentially have two options here, for the following reason: the cache is based on the last time the article has been updated which can be a long time ago, which means that the "time ago" string will get stale at some point.

- option a: we remove the cache altogether for this part: https://github.com/thepracticaldev/dev.to/blob/master/app/views/notifications/_article.html.erb#L25-L52

- option b: we cache separately the pieces of HTML surrounding the "time ago" part. The part before that is the owner info: https://github.com/thepracticaldev/dev.to/blob/master/app/views/notifications/_article.html.erb#L26-L33 and the part after that is the link, title and tags: https://github.com/thepracticaldev/dev.to/blob/master/app/views/notifications/_article.html.erb#L40-L51

Changing the cache key doesn't really solve the problem because if the article never gets updated the key expires too late and you can't set an explicit expiration date on fragments

**Comment by maestromac** [comment]
Would there be any repercussions to option a @rhymes ?

**Comment by rhymes** [comment]
@maestromac without testing it i'm honestly not sure, by looking at the code i don't see any heavy computations, they are both basically rendering JSON data which is already computed
