### ISSUE TITLE
Improve Offline Wording

### ISSUE THREAD

**Issue by erturne** [thepracticaldev/dev.to#404]
### Description

The current wording in the offline.html file is rather political, and probably does not foster an open and welcoming environment. Currently it says:

> This must be frustrating, but to put it in context, Trump's still president, so a poor Internet connection can't be so bad, right? On the other hand, you don't have access to the Internet, so maybe he's been impeached by now, for all you know.

Regardless of your political beliefs, the offline page is probably not the place to express political preferences. We should adhere to the spirit of the Code of Conduct:

> Examples of behavior that contributes to creating a positive environment include:
>
>    Using welcoming and inclusive language
>    Being respectful of differing viewpoints and experiences

### Definition of Done

The offline.html page will be apolitical.

**Comment by rhymes** [comment]
@erturne check this discussion they already had on the topic 10 days ago https://github.com/thepracticaldev/dev.to/pull/305

**Comment by erturne** [comment]
They should have left it open.

**Comment by benhalpern** [comment]
@erturne. That PR was closed because it was a PR and we weren't going to implement that specific change. This one can stay open.

Here's the change we would make: **_A new easter egg_**. The offline page can be a place to express something a little different from the core platform. Like a "doodle" of sorts. I have someone in mind who may have fun designing a new one.

Regarding the code of conduct stuff, I believe this is consistent with our values. But we don't have to get into it. The technical constraint of the offline page is that it should have no outside dependencies. The current one _does_ because I didn't really think through the implications of how service workers would work with it. This made it more complicated. A new one should be all inlined so it can act as one cached document.

**Comment by benhalpern** [comment]
Hey, we've just merged our next easter egg offline page, so I'll close this issue.
