### ISSUE TITLE
OpenGraph links use http instead of https

### ISSUE THREAD

**Issue by abenettt** [thepracticaldev/dev.to#4055]
OpenGraph links use http instead of https.
I found this to be the case with at least these two posts.

https://dev.to/ben/if-you-were-tasked-to-conduct-a-security-audit-on-a-server-database-backed-web-app-where-would-you-start-573o

https://dev.to/nerdmom630/free-code-camp-and-it-s-community-4el1

**Screenshots**
![image](https://user-images.githubusercontent.com/7523903/65125611-fad52b80-d9f5-11e9-8367-978cbb3c87a1.png)
![image](https://user-images.githubusercontent.com/7523903/65125667-17716380-d9f6-11e9-92f4-db96a40c206c.png)

**Comment by rhymes** [comment]
Thanks @abenettt, great find! 

I think this has to do with how we build the URLs server side.

The same happens for listings https://dev.to/listings/products/base-api-for-authentication-email-sending-image-upload-and-more-5911 if you look at the source code

It seems like `_url()` routing functions are generating HTTP URLs instead of HTTPS, for example in here: https://github.com/thepracticaldev/dev.to/blob/master/app/view_objects/articles/social_image.rb#L27 or https://github.com/thepracticaldev/dev.to/blob/master/app/helpers/social_image_helper.rb#L17

It probably has to do with the fact that the `default_url_options` aren't setting the `https` option to true:

https://github.com/thepracticaldev/dev.to/blob/705da8fbde946f2c33f4eae7bff5e9d73571e218/config/environments/production.rb#L128-L129

we only set the domain, which unfortunately [defaults to http](https://api.rubyonrails.org/classes/ActionDispatch/Routing/UrlFor.html#method-i-url_for)

**Comment by rhymes** [comment]
The same happens for tags as well: https://dev.to/t/discuss and comment pages and user profiles:

```html
<meta name="twitter:image:src" content="http://dev.to/social_previews/user/2693.png">
```

this is my own profile's social image URL
