### ISSUE TITLE
Datetime for thread

### ISSUE THREAD

**Issue by adhocore** [thepracticaldev/dev.to#406]
## Feature Request or Task

Showing full date time on hovering the date at the right top edge of thread comment/reply (eg `Aug 19` as in SC below)

Thanks

-------
### Current Behavior
> On hover nothing

### Expected Behavior
> On hover full date time (preferably in current user's timezone)

### Mobile & Desktop Screenshots/Recordings
![image](https://user-images.githubusercontent.com/2908547/44310532-1b514180-a402-11e8-881a-21a54554920f.png)

**Comment by spinualexandru** [comment]
I would be willing to work on this if anyone allows me to.

**Comment by jessleenyc** [comment]
A title attribute would get us part of the way there, so let's start with that.

**Comment by maestromac** [comment]
Not stale

**Comment by rhymes** [comment]
@maestromac @aspittel  I wonder if we could find a way to bring this to its conclusion because it seems like a fruitful quick win. There are two different PRs:

* #426  open since August 2018
* #1656 open since January 2019

They are slightly different. The first one displays a full formatted date with a CSS based hover, has quirky naming and includes a test, the second uses the `title` builtin hover functionality but has no tests and has a conflict.

I lean towards the second, maybe adding a test for the decorator.

A third approach, which I like but goes in a different direction, maybe less explored by the code base, is to take advantage of Rails i18n support. It was suggested here https://github.com/thepracticaldev/dev.to/pull/1656#issuecomment-458710157

Either way, it would be nice if the team could "adopt" this feature. I'd like to help to get this to the finish line somehow.

If you'd prefer to merge one of the two as is or with modifications we could ping the OPs
Otherwise if you prefer a different approach I'm down to implement a different one.

Thank you!

**Comment by maestromac** [comment]
Thanks for the ping @rhymes . The i18n implementation is the most interesting. Unfortunately, none of the implementation accounts for user's local time.

The solution I have in mind is to embed the time data to somewhere on the article/comment's div and for Javascript to convert it to user's local time. We currently use [initializeTimeFixer.js](https://github.com/thepracticaldev/dev.to/blob/master/app/assets/javascripts/initializers/initializeTimeFixer.js)

**Comment by rhymes** [comment]
@maestromac got it. I'm working on a PR to do just that
