### ISSUE TITLE
Increase seed data for development purposes

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#4149]
**Is your feature request related to a problem? Please describe.**

In some cases, like testing notifications or paginations or situations where a lot of data is required to successfully develop a feature, the developer would want to increase the amount of data the development DB contains.

Since increasing default seed data is going to slow down the developer experience of casual contributors (but also regular ones), we should lean on the ability to **add** data to a DB that's already seeded, instead of merely increase its default size.

**Describe alternatives you've considered**

The premise here is that the developer has to be able to essentially do two things:

- increase the amount of data (which could be everything or in an advanced capability only a type of resource, eg. articles or notifications)
- specify the ID of the user (likely themselves) to attribute things like articles to.

I'm going to list the possible solutions:

- add environment variables for the seed file (but it would still have the issue of resetting the db and hence deleting the developer's user account)
- add an additional rake task that can use parameters and/or environment variables to add things to an already seeded database
- split the seed in various files with gems like [seedbank](https://github.com/james2m/seedbank)

**Additional context**

See https://github.com/thepracticaldev/dev.to/pull/2361 for a past discussion

**Comment by omenking** [comment]
I put forward again a vanilla solution could be implemented. I don't believe we need to reduce the number of records but need to solve what is causing the slowdowns of creating seed data.

I have identified the large slow down with being with `act_as_taggable`. I believe this gem can be replaced with a vanilla solution which would greatly improve performance where large amount of seed data would take little to no time to complete.

For the organization of seed data, I would suggest it be broken up into files and be placed in a directory called seeds alongside the seeds.rb.

You can supply environment variables for the quantity but it would make sense for the defaults to be what is enough data to test common actions.

So if pagination requires for a page 100 records for a page you have to at least that amount. This was the intent of my original pull request.

Even if you were to use tasks to generate seed data in order to write test code you'll likely want to place whatever code in modules first hense the `db/seeds` directory. The reason is ease testing. It is possible to write tests for tasks but isolating them in modules makes things easier.

You could place them in `lib/seeds` as well.

I would not like to see another dependency added to DEV.to so I would suggest not to use seedbank.

If @benhalpern and the core team came to a ruling you could have put forth what you wanted I would have adjusted my original pull request. From the ticket, I don't know what is wanted here.

**Comment by omenking** [comment]
![Screen Shot 2019-09-30 at 1 29 16 PM](https://user-images.githubusercontent.com/7776/65901497-530d1580-e386-11e9-81e2-d675d488651a.png)

**Comment by iagocavalcante** [comment]
Hey, can i take this ?

**Comment by rhymes** [comment]
@iagocavalcante yes, do you have a general idea of how you would want to go about for this? I feel in this case a discussion before implementation (which could be beneficial for any type of issue actually) is warranted.

What do you propose?

**Comment by FeruzOripov** [comment]
[https://github.com/james2m/seedbank](url) is really cool one

**Comment by worldofprasanna** [comment]
@rhymes Can you please give your thoughts about this approach,

1. Use seedbank and keep the db/seeds.rb as such.
2. Create one more seed file `db/seeds/large_data.seeds.rb` which contains data volume as mentioned in this PR #2361 
3. Update the document accordingly, 
          a. For regular users, they have to run `rails db:seed:original`
          b. If you want more data `rails db:seed:large_data`. This would run both the seed files.

What do you say ?

**Comment by rhymes** [comment]
@worldofprasanna maybe we should proceed with various degrees of customization, what if we start with the multiplier option before integrating another gem?

**Comment by worldofprasanna** [comment]
@rhymes Sure it would be much simpler. 

As suggested by you in the other thread, I will use the env variable as the multiplier for the seed data.

**Comment by rhymes** [comment]
I think we can consider this closed by #6003 and https://github.com/thepracticaldev/dev.to/pull/6058

We can always increase data in further PR if we need to
