### ISSUE TITLE
A user gets mentioned when they comment with a twitter liquid tag where their user name is the same as their dev.to user name

### ISSUE THREAD

**Issue by nickytonline** [thepracticaldev/dev.to#4262]
**Describe the bug**

I've noticed this twice now. If I comment on a post and the comment contains a liquid tag for a Twitter post of mine, where the DEV user's handle name is the same as their twitter handle, they receive a notification that they were mentioned in a comment.

Here is the comment I made a few minutes ago that exhibits this behaviour, https://dev.to/nickytonline/comment/g7p7.

**To Reproduce**

1. Create a comment on any post and in the comment, include a Twitter liquid tag that references a tweet of yours (your DEV and Twitter handle need to be the same for this to work).
2. Submit the comment.
3. Check your notifications. You will have a notification about your own comment mentioning yourself.

NOTE: This would probably happen for other liquid tags as well if they generate a piece of text that matches a reference to a DEV handle, e.g. `@nickytonline`.

**Expected behavior**

When a user submits a comment that includes a tweet of theirs via a Twitter liquid tag, they should not receive a mention if it is their own tweet, where the Twitter handle is the same as the DEV handle.

**Screenshots**

![image](https://user-images.githubusercontent.com/833231/66271912-7d048300-e831-11e9-92f6-a164edda9e81.png)

**Desktop (please complete the following information):**

- OS: N/A
- Browser: N/A
- Version: N/A

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser: N/A
- Version: N/A

**Additional context**

**Comment by shushugah** [comment]
I think the fix is to not ever mention anyone via a tweet tag, because this is not explicitly meant to tag people.

**Comment by nickytonline** [comment]
I'm not sure how the mentions are processed, but my guess is it is post generation of liquid tags in content. It probably makes sense to add a check when generating mentions for a user. If the current user is the one being mentioned, omit that from mention from their mentions.

**Comment by jessleenyc** [comment]
Yeah, I agree with that @nickytonline. Not just for Twitter liquid tags but a final check that we should only send a mention notification to the same user once per comment.

**Comment by artoodeeto** [comment]
@nickytonline  @jessleenyc  let me take a crack on this one.

**Comment by artoodeeto** [comment]
Hi, I also found out that if the current user tries to mention it self in the comments it will notify the user. So this is not just the twitter liquid tag or any liquid tag, guessing its in the comments mention. 

Im kinda lost, what I'm trying to achieve is upon submitting a comment:
1. intercept the comments params from CommentController#create. payload looks like this:
```
Parameters: {"comment"=>{"body_markdown"=>"@artoo_o\n@artoodeeto\n@foo\n@bar\n@waaa", "commentable_id"=>"22", "commentable_type"=>"Article", "parent_id"=>nil}}
```
2. check @mentions (regex i guess)
3. filter the params mentioned users then send notifications to all mentioned except current_user

Problems:
I cant locate the file where the comments are being parse specifically the users that are being mentioned. im sure this is implemented because created 2 accounts and both are being notified

Cant locate the file that send a notifications to each user. I only have this on comments_controller.rb
```
NotificationSubscription.create(user: current_user, notifiable_id: @comment.id, notifiable_type: "Comment", config: "all_comments")
      Notification.send_new_comment_notifications_without_delay(@comment)
```

Where is the `body_mark_down` extracted? you only have this `@comment = Comment.new(permitted_attributes(Comment))` I checked the comment_policy.rb nothing there about permitting body_mark_down

sorry im trying my best not to ask questions but its been 3 hrs since i started. ill continue tomorrow after work. im a bit new to ruby still confused a bit. 😢

**Comment by Zhao-Andy** [comment]
Hi @artoodeeto, sorry for the late reply! Rails follows a traditional MVC framework, so you can find most of the logic in either the model files (`app/models/comment.rb` or `app/models/mention.rb`) or the controller files (`app/controllers/comments_controller.rb`). The payload `CommentsController#create` means the code running is in the `create` method of the `CommentsController`. 

To answer your questions, you can find where the mentions are created by following this rabbit hole:
1. comments_controller.rb, line 59
2. mention.rb, line 15
3. create_all_job.rb, line 9
4. create_all.rb (the final file where the mention creation happens)

Since the creation is run asynchronously, you'll need to run background jobs if you're not already. Using our binary command should handle that for you: `bin/startup`

I don't think you'll need to figure out much about the parsing of the markdown for comments, but if you do, you can find the logic in `markdown_parser.rb`.

Hope that helps! Feel free to reply with more questions. :)

**Comment by artoodeeto** [comment]
@Zhao-Andy hey thanks for the info andy. So what im trying to understand about the comments part is. 

after this part right here. after the user submits a comment
```
<%= f.text_area :body_markdown,
                    placeholder: "Add to the discussion",
                    onfocus: "handleFocus(event)",
                    onblur: "handleBlur(event)",
                    onkeyup: "handleKeyUp(event)",
                    onkeydown: "handleKeyDown(event)",
                    id: "text-area",
                    autofocus: @comment.persisted?,
                    required: true,
                    'aria-label': "Add a comment to the discussion" %>
```

it will be processed by `CommentsController` in `create` action but on the create action I can only see this.

```
@comment = Comment.new(permitted_attributes(Comment))
    @comment.user_id = current_user.id

    if @comment.save
      current_user.update(checked_code_of_conduct: true) if params[:checked_code_of_conduct].present? && !current_user.checked_code_of_conduct
  
      Mention.create_all(@comment)
      NotificationSubscription.create(user: current_user, notifiable_id: @comment.id, notifiable_type: "Comment", config: "all_comments")
      Notification.send_new_comment_notifications_without_delay(@comment)

      if @comment.invalid?
        @comment.destroy
        render json: { status: "comment already exists" }
        return
      end
```
I thought this is where everything is being done. after the user submits it goes to controller calls a parser method to parse the usernames, puts it in an array structure and then loops through each user names to send a notification. I was thinking of that way but It's not so theres something in between. this is where I get lost looking for that something. lols. hope im making sense here. ✌️

**Comment by artoodeeto** [comment]
@Zhao-Andy hey I think I got it. but im not sure. but i tested it on browser seems to work.

heres the code though. So I just add a check if the user owns the comments.
```
def call
      # Only works for comments right now.
      # Paired with the process that creates the "comment-mentioned-user"
      doc = Nokogiri::HTML(notifiable.processed_html)
      usernames = []
      mentions = []

      doc.css(".comment-mentioned-user").each do |link|
        username = link.text.delete("@").downcase
        user = User.find_by(username: username)
        if user && user.id != notifiable.user_id
          usernames << username
          mentions << create_mention(user)
        end
      end
      delete_removed_mentions(usernames)
      mentions
    end
```

next problem is how to write a test on this one. lols

**Comment by artoodeeto** [comment]
@Zhao-Andy damn. I was looking at the wrong file again. I was `/spec/jobs/mentions/create_all_job_spec.rb` thanks. :smile:

**Comment by artoodeeto** [comment]
im not sure who to tag but I have a pr for this. @Zhao-Andy @jessleenyc @nickytonline
