### ISSUE TITLE
DIV alignment issue on one specific post, possibly missing html tag?

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#4379]
Something going on with the content area under this post…
https://dev.to/jess/what-was-your-win-this-week-dch
Looks like maybe a missing closing div or something (notice the lack of padding at the bottom in addition to the alignment issue)
Only that post is off from what I see right now.

<img width="1227" alt="Screen Shot 2019-10-11 at 1 48 01 PM" src="https://user-images.githubusercontent.com/3102842/66673196-16ff6d80-ec2e-11e9-8ea4-9fa26d037d8e.png">

**Comment by Amorpheuz** [comment]
In terms of the page's HTML, the div elements for classes `show-page-content-display`, `more-articles` and id `additional-content-area` ended up being added outside the main div with class `home`. Due to this, the margin-property they have of `25px` ends up being taken from main `page-content` div rather than `home`.
![image](https://user-images.githubusercontent.com/22113778/66677417-35458780-ec87-11e9-909f-f35ba112ead3.png)

The standard behavior for them is to be inside the class `home` div, fixes the issue:
![image](https://user-images.githubusercontent.com/22113778/66677400-2a8af280-ec87-11e9-9df2-3c35c3fddb07.png)

**Comment by jessleenyc** [comment]
This could be a caching or markdown issue, we're thinking the latter. There might be an unclosed div in one of the comments on the post that's creating this.

**Comment by maestromac** [comment]
Resolved with https://github.com/thepracticaldev/dev.to/pull/4445
