### ISSUE TITLE
Use Client-side Storage in the Markdown Editor

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#442]
## Feature Request or Task
Whenever someone tries to save their post, we should save their Markdown data into the client. We would want to use something like Local Storage to save the data. Ideally, this rolls out with the new editor (see #272).

### Description
There are a few design considerations here to think about:
1. If a post failed, and someone revisited `/new`, would their post be there already? Or should there be button to fetch it, or maybe a button to clear it?
2. Should this happen whenever someone previews their post, too? 
3. We'll have to consider this design for the new Markdown editor more so than the current version.
4. Using local storage shouldn't be too difficult. 

### Definition of Done
We've discussed and decided on a design, and having a working auto-save feature.

**Comment by jessleenyc** [comment]
@benhalpern looks like we're seeing more timeout errors while saving posts -- does it make sense to prioritize this?

**Comment by aspittel** [comment]
A few notes:

- https://github.com/localForage/localForage came recommended for browser compatibility
- GitHub's similar feature is implemented like this https://twitter.com/MrTurnerj/status/1087697569579298822 -- I think it would be really cool to do something similar so that if a person accidentally presses back, or closes the tab, their work isn't gone!
