### ISSUE TITLE
Add ES6 support to non-preact frontend

### ISSUE THREAD

**Issue by maestromac** [thepracticaldev/dev.to#460]
## Feature Request or Task
Our frontend, the portion not covered by preact/webpacker, does not officially support ES6. ES6 works in development but not in production. There are a few band-aids in place but an official change in our configuration would be more ideal.
### Definition of Done
Contributors can freely use ES6 JS.
### Resources
- (This might be our solution) https://stackoverflow.com/questions/41531527/cant-precompile-production-assets-when-using-es6
- https://blog.arkency.com/2015/05/start-using-es6-with-rails-today/

**Comment by twhite96** [comment]
I may be able to take a look at this @maestromac.

**Comment by jeann2013** [comment]
Is possible add reactjs with preact?

**Comment by twhite96** [comment]
@jeann2013 think they're going to move the whole front end to Preact. I don't think it would be a good idea to add straight React. What do you think @bendhalpern @maestromac?

**Comment by nickytonline** [comment]
Preact was chosen. For the reasons why, see https://dev.to/ben/why-we-went-with-preactjs-to-power-the-devto-frontend-8d6. Having said that, React libraries can be used with Preact. This is how I got [Storybook](https://storybooks.org) setup for dev.to with Preact.

**Comment by benhalpern** [comment]
It's not so much the "preact" portion of the site and the non-preact. Moreso the webpacker-driven part and the legacy.

Just saying that as a way to think about it.

The roadmap includes refactoring (and in some case getting rid of) older parts of the JS and getting it more fully tested and consistently implemented.

(As a bit of an aside, in order to make best use of Preact's minimalism, we will also need to smarten up our codesplitting. We're naively still sending a lot of bytes due to a few large libs.)

That is to say, I think we want to be moving old-to-new and if we are refactoring a section, I think that is ideally how we would do it.
