### ISSUE TITLE
Reading list not updated after I click 'Save' post

### ISSUE THREAD

**Issue by spuccia** [thepracticaldev/dev.to#4839]
In my feed when I click 'Save' post/article the number of posts in my reading list is updated but if I open my reading list the saved post there isn't. If I do logout and then login the reading list contains the saved post.

1. Go to 'Feed'
2. Click on 'Save'
3. Go to 'Reading List'
4. The last post saved miss

I expect to see the saved post on my reading list after that I click 'Save'.

- OS: MacOS 10.14.6
- Browser: Chrome
- Version: 78.0.3904.97

**Comment by rhymes** [comment]
I have the same problem, I have to wait a bit and refresh it or refresh a few times. I think it's because the save operation is async but it might not be the whole story.

It also happens with the opposite operation. When you remove a a post from the reading list it takes a while for it to actually disappear from the list.

**Comment by sibis** [comment]
I tried debugging this issue. Looks like it occurs due to the background job takes time since we are calling the  **send_reaction_notification** which then calls the **perform_later**. Changing the method to **send_reaction_notification_without_delay**  in `app/controllers/reactions_controller.rb` for create reaction works fine in local test. 

@rhymes Can you please make sure whether my approach here makes sense, before I start this.

**Comment by rhymes** [comment]
@sibis sorry if I didn't reply on time, I'm going to review your code and answer you inline in the PR!

**Comment by mstruve** [comment]
No longer a problem since moving to Elasticsearch
