### ISSUE TITLE
Tag blacklist

### ISSUE THREAD

**Issue by dogweather** [thepracticaldev/dev.to#485]
### User Story / Description

As a site reader, I want my feed to exclude posts with certain tags because they get in the way of me seeing the tags I've registered my interest in. And/or certain tagged posts generate drama which I'd rather not see.

Although a user can specify **my tags**, these are treated as "soft" recommendations, and the user is still shown other tags when browsing to the site home page and seeing the feed. This may be an acceptable strategy. But a user should be in control of their experience enough to hide their most undesirable tags from their feed.

### Definition of Done

A second tag list, analogous to `my tags` will exist, e.g. `don't show`. There'll be a facility for editing this list similar to `my tags`. And the site feed will respect this list in choosing what to show the user.

**Comment by misterhtmlcss** [comment]
I love this idea. I'm always in favour of what I call 'negatives'; is there a correct term for this? I really dislike my feed getting poluted with everything under the sun. A great example is Webpack; it's used for everything and written about often, but I don't want to subscribe, because it's got 70% content I don't want. 

@benhalpern I'd like to raise an expansion of this proposal. We should have a double click behaviour (on nearly every button/icon type interaction) and this will allow bahaviours like @dogweather's to be done inclusive of a larger effort that implements this across the UI making for a consistent experience across the site. 

@dogweather @benhalpern thoughts?

I'm also happy to contribute and create the Tag Blacklist if that's what is decided; I'm easy.

**Comment by benhalpern** [comment]
Sorry I never jumped into this conversation. This feature should address this:

https://dev.to/devteam/changelog-adjust-the-weights-of-tags-you-follow-571k

It's a bit weird to follow something you don't want to see, so the feature isn't fully fleshed out, but this is the root of the approach we're taking for this general issue. I'm going to close this. Feel free to open another PR with ways we can build on this implementation.

**Comment by skeet70** [comment]
Setting something to 0 weight doesn't prevent it from showing up in my feed, which seems like the core of this feature request. It's certainly how I ended up finding this issue. I recently signed up for dev.to and immediately realized I don't want to see _any_ of the linkedin style motivational #life junk that was showing up in my feed. Followed #life and set it to 0, but it still shows up.

**Comment by maestromac** [comment]
Thank you for brining that up @skeet70 . We'll reopen this.

**Comment by maestromac** [comment]
My apology. Since this is closed before, we'll keep it closed. Please continue the conversation here https://github.com/thepracticaldev/dev.to/issues/1856
