### ISSUE TITLE
Redis connection problem in the dockerized application.

### ISSUE THREAD

**Issue by abdellani** [thepracticaldev/dev.to#4962]
**Describe the bug**
Hi,
In the dockerized application, I tried to authenticate using my Github account. 
Knowing that I followed the guide to add the different Github's keys into the EnvFile, I got the following error after clicking on the Signup via Github button
```
Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)
```
It seems that the redis is not defined in the docker-compose.yml file. I tried to fix the error by adding it, but I think that the environment variable  `REDIS_URL` in docker-compose is ignored.
You can check my [ modifications here ](https://gist.github.com/abdellani/d3729c356103d5391dda315f398a39a1) 
**To Reproduce**

1-Run 
```
docker-compose build
docker-compose run web rails db:setup
docker-compose run web yarn install
docker-compose up
```
2- Try to authenticate using Github account.

**Expected behavior**
- Getting authenticated to the application

**Screenshots**

![Screenshot_2019-11-28 Action Controller Exception caught](https://user-images.githubusercontent.com/16113997/69811785-2131f700-11ef-11ea-8fc4-f2bda340ec49.png)

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment]
Hi @abdellani, great catch! 

Can you try replacing `redis://redis:6379` with `redis://localhost:6379`, would that work?

**Comment by abdellani** [comment]
Hi @rhymes 

I got the same error.

**Comment by delbetu** [comment]
@rhymes It seems that you have a solution to this issue.
I notice this:
within the session store configuration, REDIS_SESSIONS takes precedence over REDIS_URL

within the cache store configuration, REDISCLOUD_URL takes precedence over REDIS_URL

within cable.yml only REDIS_URL is valid

REDIS_CLOUD is defined by Heroku addon.

So I think that we can remove the REDIS_SESSIONS and use only REDIS_URL

Also, we could define REDIS_URL with the same value of REDISCLOUD_URL or a default value 

So we also can get rid of REDISCLOUD_URL usage within the 
session store initializer.

**Comment by rhymes** [comment]
Hi @delbetu, it looks to me that's not the actual problem here though.

`REDIS_URL` is used in production for caching storage, `REDIS_SESSIONS_URL` is used for session storage but by default they both point to the same DB, allowing people to use the same Redis for both.

`REDISCLOUD_URL` as you mention is part of Heroku but since it defaults to empty string, it will fallback to `REDIS_URL` which is the same string in the `Envfile`, or something else if you change it in the `application.yml`

Ultimately they all have the same value if you don't change. 

Regarding you changing the Envfile, theoretically you're not supposed to do it. To change the default values you can create a `config/application.yml` similar to `config/sample_application.yml` and edit that. `Envfile` is a readonly file for all intents and purposes.

The [Docker installation guide](https://docs.dev.to/installation/docker/#installing-dev) mentions this.

If you can confirm that by tuning the `config/application.yml` and setting both `REDIS_URL` and `REDIS_SESSIONS_URL` to `redis://redis:6379` everything works, we can add this info to the Docker installation guide and also fix @abdellani's issue :)

Can you try? Make sure the `Envfile` is reverted to the default

ps. `cable.yml` is not used, it's part of the configuration of `ActionCable` which we aren't using

**Comment by abdellani** [comment]
@rhymes 
Sorry, I didn't pay attention to that detail.
I confirm that it works after setting the two variable REDIS_URL and REDIS_SESSIONS_URL to "redis://redis:6379" in application.yml

**Comment by Prajapatisantu** [comment]
how to establish action cable connectin in dockerized app.

**Comment by L-Zuluaga** [comment]
> how to establish action cable connectin in dockerized app.?

the same way they explained previously, but replacing on the `cable.yml` the url from `redis://localhost:6379` to  `redis://redis:6379`
