### ISSUE TITLE
High Error for redirect, CSS very danger, I ran brakeman

### ISSUE THREAD

**Issue by jeann2013** [thepracticaldev/dev.to#511]
I ran brakeman last version dev.to and i got this

This the last version: 

** b0a7e3c - (5 hours ago) Add finishing touches to reports dashboard - Zhao-Andy (upstream/andy/feature/internal-reports-v2)
**
-------
## Bug Report

`

 Confidence | Class                                | Method                                    | Warning Type  |

| High       | ArticlesController                   | redirect_after_creation                   | Redirect      |
| High       | CommentsController                   | update                                    | Redirect      |
| High       | CommentsController                   | destroy                                   | Redirect      |
| High       | Internal::FeedbackMessagesController | update                                    | Redirect      |
| High       | Internal::WelcomeController          | create                                    | Redirect      |
| High       | StoriesController                    | redirect_to_changed_username_profile      | Redirect      |
| High       | StoriesController                    | redirect_to_changed_username_profile      | Redirect      |
| High       | StoriesController                    | redirect_to_changed_username_article_page | Redirect      |
| High       | StoriesController                    | redirect_to_changed_username_article_page | Redirect      |
| High       | TagsController                       | update                                    | Redirect      |
| High       | articles/_comments_section (Template:articles/index)   | Cross Site Scripting | 
| High       | articles/_markdown_form (Template:articles/new)        | Cross Site Scripting | 
| High       | articles/_sidebar_additional (Template:articles/index) | Cross Site Scripting | 
| High       | comments/index (CommentsController#index)              | Cross Site Scripting | 
`

**Comment by jessleenyc** [comment]
Thanks @jeann2013, we'll take a look at this. Also a heads up that you're on @Zhao-Andy's branch and not master!

**Comment by benhalpern** [comment]
Hey, @jeann2013 I believe these are generally known to be dismissable by us given that we know these are not actually user-generated content. We have investigated and dismissed most of these ourselves. 

We can work to adjust the code so it is exactly what brakeman expects, and probably should, but I do not think these are active concerns. Will investigate further just to be sure.

I'm going to close this for now in order to limit cause for alarm. You are welcome to email yo@dev.to to discuss any of this further. If these turn out to be true vulnerabilities, you'll be eligible for our bounty.
