### ISSUE TITLE
Do not escape characters for <title>

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#5226]
**Describe the bug**

The article is called "Why & How I built css.gg - A life story.". In Firefox, "&" is escaped as HTML in `<title>` and the tab looks like this:

![image](https://user-images.githubusercontent.com/7100645/71374133-99ab8e00-25ca-11ea-9c7d-0d77b667f6f8.png)

**To Reproduce**

Open https://dev.to/astrit/why-how-did-i-build-500-css-only-icons-library-a-life-story-34on

**Expected behavior**

"Why & How I built css..." in the title.

**Screenshots**

above.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 71.0

**Comment by Defman21** [comment]
Reproduced here again https://dev.to/devteam/the-dev-stackbit-integration-is-in-the-running-for-a-product-hunt-golden-kitty-award-23ge

**Comment by maestromac** [comment]
Thanks for pointing that out @Defman21

**Comment by bighappytrees** [comment]
Can I take a crack at this?

**Comment by rhymes** [comment]
Hi @bighappytrees, thanks for volounteering! This seems not to be a problem anymore, see the article that this issue was based upon:

![Screenshot_2020-02-22 Why amp; How I built css gg - A life story - DEV Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/75096550-f282ad00-55a0-11ea-8a4c-6f33cc251d68.png)

In addition there's a PR opened to fix this https://github.com/thepracticaldev/dev.to/pull/5788 - even though I'm not sure it's still necessary.

I'll confirm if this is still an issue and if this is still necessary and get back to you, in the meantime you're welcome to take a pick of another issue marked both [ready for dev and good first issue](https://github.com/thepracticaldev/dev.to/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22good+first+issue%22+label%3A%22ready+for+dev%22)

Sorry for the misunderstanding!

**Comment by bighappytrees** [comment]
Thank you @rhymes I'll find another issue to tackle.
