### ISSUE TITLE
Help with local setup (Storext NameError, dry-gems missing, reverse markdown load error)

### ISSUE THREAD

**Issue by swiknaba** [thepracticaldev/dev.to#5313]
✅ API related issue, no browser necessary

✅ not related to profile

**Describe the bug**

see comment here: https://github.com/thepracticaldev/dev.to/issues/5305#issuecomment-569926644
copy-paste of the comment:

I'd like to contribute, however, the local setup gives me quite some troubles. Should I open a new issue for each individually, all at once, or none (could be just my machine)? All the problems:

- `cannot load such file -- dry-equalizer` => resolve via: `gem install dry-equalizer` (why is it not in the Gemfile?)
- `cannot load such file -- dry-configurable` => resolve via: `gem install dry-configurable` (why is it not in the Gemfile?)
- `uninitialized constant ReverseMarkdown::Converters::Base (NameError)` => not sure, why it does not pick up the [reverse markdown gem's base file](https://github.com/xijo/reverse_markdown/blob/master/lib/reverse_markdown/converters/base.rb) -> I wrapped the manual loading inside a `defined?(ReverseMarkdown::Converters::Base)` guard clause for now. Any idea, why that fails, is it my problem, or do others have this issue?
- `uninitialized constant Article::Storext (NameError)` => I had this issue after upgrading storext from 2.x to 3.x in a previous project for which we did not find a solution and thus had to lock that gem to 2.x (`gem 'storext', '~> 2.2', '< 3.0'`), which is preventing you to upgrade to rails 6, thus that is not a viable solution. Is that just my machine, if so, does anyone have an idea for a solution?

My machine runs macOS 10.14, I went through the setup guide, use `rbenv`, etc. I have many ruby/rails projects running on Mac machine, so Postgres/Ruby/etc. is all installed properly and running. Thanks for any advice 🙂

=> after those mentioned "fixes", `bin/setup` finally succeeds and the app is running locally. However, `spec/services/rss_reader_spec.rb` is failing. See my changes here: https://github.com/swiknaba/dev.to/pull/1

**To Reproduce**

- forked & checked out the project
- install pre-requisites (Postgres, Ruby, ..)
- run `bundle install`
- run `bin/setup` => fails (see errors above)

**Expected behavior**

running `bin/setup` succeeds.

**Screenshots**

don't have screenshots, if necessary, can paste trace of errors 🙂 

**Desktop (please complete the following information):**

- OS: macOS 10.14.6
- Browser: /
- Version: latest commit hash: https://github.com/thepracticaldev/dev.to/commit/8aa9eb3534d3c07e49aac74e1a939622d09be223

**Smartphone (please complete the following information):**

API only

**Additional context**

/

**Comment by rhymes** [comment]
Hi @swiknaba, thanks for the patience, I believe there's a configuration problem somewhere, let's see if we can get to the bottom of it.

The gems you installed manually are present in the [Gemfile.lock](https://github.com/thepracticaldev/dev.to/blob/master/Gemfile.lock) so you shouldn't have to install them manually. The only required global gem is `bundler`.

> uninitialized constant ReverseMarkdown::Converters::Base (NameError) => not sure, why it does not pick up the reverse markdown gem's base file -> I wrapped the manual loading inside a defined?(ReverseMarkdown::Converters::Base) guard clause for now. Any idea, why that fails, is it my problem, or do others have this issue?

this sounds like the same problem as the previous two, your Gemfile is not correctly installed

> uninitialized constant Article::Storext (NameError) => I had this issue after upgrading storext from 2.x to 3.x in a previous project for which we did not find a solution and thus had to lock that gem to 2.x (gem 'storext', '~> 2.2', '< 3.0'), which is preventing you to upgrade to rails 6, thus that is not a viable solution. Is that just my machine, if so, does anyone have an idea for a solution?

By reading this I have a suspicion: are you using a virtual environment with isolated gems or are you installing everything in the global gem list? Because the app should be isolated from everything else you've installed. 

Have you followed the mac installation guide: https://docs.dev.to/installation/mac/ - either with rbenv or rvm? What version of the packages do you have?

Can you create a [gist](https://gist.github.com/) with the following info and link it here?

- Ruby version: `which ruby && ruby --version`
- Bundler version: `which bundle && bundle --version`
- List of bundled gems: `bundle list`
- maybe also the list of all gems: `gem list`

There's obviously something that's conflicting in the loading order...

**Comment by swiknaba** [comment]
Thank you @rhymes for your help 🙌.

My local setup:
https://gist.github.com/swiknaba/5dda5210ca7554bd7ba65034e8b40903

I went through all steps in https://docs.dev.to/installation/mac/, and got stuck at 
> 5. `Run bin/setup`
I was installing gems via `bundle install`, which run without troubles. Apart from using bundler, I did not use any virtual environment such as docker/virtualbox/..

**Comment by rhymes** [comment]
I'm going to close this as you eventually submit two PR after opening this: https://github.com/thepracticaldev/dev.to/pulls?q=is%3Apr+author%3Aswiknaba+is%3Aclosed
