### ISSUE TITLE
Tag Moderation Case Sensitive

### ISSUE THREAD

**Issue by CodeMouse92** [thepracticaldev/dev.to#5325]
**Describe the bug**

When a tag uses unconventional capitalization, it shows up in the normal list of posts for that tag, but it cannot be removed. For example, if a post has the tag `#C`, it shows up under `#c`, but cannot be removed by the `#c` tag moderator.

**To Reproduce**

1. Go to a post with a tag with unconventional capitalization, such as https://dev.to/norrischebl/epic-games-launcher-not-working-on-mac-26jc

2. Go to the Moderate Post page. (You must have tag moderator privileges on the oddly capitalized tag in question.)

3. Try to remove the tag, in this case, `c`. (The "Remove" option may not even be present!)

4. Note the error:

> Adjustment type is not included in the list

**Expected behavior**

Removing the `#c` tag should also remove `#C`.

**Screenshots**

![2020-45-01-0645](https://user-images.githubusercontent.com/7471402/71642580-556f5c00-2c62-11ea-80b1-2bb8c68eb273.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 19.04
- Browser: Brave (Chromium)
- Version: 1.1.23 (Chromium: 79.0.3945.88)
- All shields and privacy/ad blocker plugins disabled.

**Additional context**

I suspect that tag moderation is case-sensitive, while the core tag system is case-insensitive.

This could be a VERY BIG problem for DEV if unaddressed: as it stands, this makes it possible for a user to entirely circumvent tag moderation on their post.

**Comment by sunny-b** [comment]
I can work on this one. I already have a working solution, just need to figure out the specs

**Comment by rhymes** [comment]
@sunny-b yes, thank you! I'm going to assign you this issue :)

**Comment by rosejcday** [comment]
This is still a current issue that is on going, how is progress going to resolve this issue? 

**Describe the bug**

I am a moderator for the data science tag #datascience, and noticed that tags with different cases such as #Datascience or #DataScience, ect. cannot be moderated against due to case being different. They show up in the data science tag list but they do not allow for me to moderate and also appear to not have the same color highlighting in the list. 

**To Reproduce**

1. Select the #datascience tag page: https://dev.to/t/datascience or a moderator page and look at the tags of multiple posts 

<img width="1440" alt="Screen Shot 2020-03-23 at 9 41 18 PM" src="https://user-images.githubusercontent.com/16930240/77379562-61ddef00-6d4f-11ea-8ace-b6d1f4b8c36a.png">

2. You will find that one or more tags have different cases, as seen in the image below. That one does not appear to be highlighted in the same color as other data science tags, and when clicked upon does not allow to option to remove that tag. It assumes the data science tag needs to be added.

<img width="1440" alt="Screen Shot 2020-03-23 at 9 41 24 PM" src="https://user-images.githubusercontent.com/16930240/77379619-889c2580-6d4f-11ea-991c-45f1e6cac705.png">

3. Here is what I see when I click to moderate the tag. Even though the tag already is appended to the post, it asks if I want to add the tag. Other posts that I have tried to remove a tag from that is not relevant, do not even give me the option to add / remove.  

<img width="1440" alt="Screen Shot 2020-03-23 at 9 41 35 PM" src="https://user-images.githubusercontent.com/16930240/77379684-b08b8900-6d4f-11ea-9b6d-e524c4d44e5c.png">

<img width="1440" alt="Screen Shot 2020-03-23 at 9 47 59 PM" src="https://user-images.githubusercontent.com/16930240/77379801-fc3e3280-6d4f-11ea-823f-39b962d2586f.png">


**Expected behavior**

I would expect that case in tags would not matter and would allow moderating to still have the same functionality for #datascience, #DataScience, #Datascience, etc. as long as the words match. 

**Desktop (please complete the following information):**

- OS: Windows 10 and Mac OS 
- Browser: Internet Explorer (Windows), Chrome (both) and Safari (Mac) 

**Smartphone:**

- Device: iPhone 
- Browser: Safari 

**Additional context**

When asking about this in the moderator forum, others have also seen this problem stating "there are a couple of posts with my tags in different casing that I also can't edit."

**Comment by atsmith813** [comment]
Tag removal is no longer case sensitive with https://github.com/thepracticaldev/dev.to/pull/8024
