### ISSUE TITLE
Migrate from ENV vars to SiteConfig

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#5384]
**Is your feature request related to a problem? Please describe.**

As of now, admins need to update certain customizations. Right now it is mostly done via ENV vars, but we want to move to `SiteConfig`.

The initial work was done here...

https://github.com/thepracticaldev/dev.to/pull/4729
https://github.com/thepracticaldev/dev.to/pull/4831
https://github.com/thepracticaldev/dev.to/pull/4865

The initial work is done, but we still haven't actually put the functionality into the app code itself (e.g. ERB files, etc.)

The three main remaining parts of this:

- Add the functionality into the app for existing `SiteConfig` keys that has been implemented.
- Add new keys and functionality for `ENV` vars that have yet to be moved to `SiteConfig`
- Add new keys for entirely new variables which are currently hardcoded entirely (more exploratory).

**Comment by citizen428** [comment]
@benhalpern I assigned this issue to myself and will start poking around.

**Comment by rhymes** [comment]
Thanks @citizen428, we had an internal list of variables to move and they are those present in `models/site_config.rb`. You can start using them around the website and exposing them in the internal admin page. 

Possibly with small PRs (so either a single variable per PR or a small set of them) so that they can be quickly reviewed by multiple sets of eyes, and so that @mstruve can plan removal of environment variables in the Heroku env accordingly.

A couple of additional PRs to plan after this move is set:

- a PR to remove unused env variables, like:

```shell
TWITTER_ACCESS_TOKEN
TWITTER_ACCESS_TOKEN_SECRET
DACAST_STREAM_CODE
GA_OPTIMIZE_ID
TRENDING_TAGS
FACEBOOK_PIXEL_ID
SMARTY_STREETS_WEB_KEY
```

- a PR to expose remaining `ENV`/`ApplicationConfig` variables values in the admin panel (it'd be nice to have a dashboard with both the entire site configuration, model based variables that can be changed and those that are read only at runtime)

- a PR with some documentation on how to manage the site configuration

Hope this helps :)

**Comment by citizen428** [comment]
Currently working on `a PR to remove unused env variables`.

**Comment by citizen428** [comment]
@rhymes and @benhalpern From what I see, we're really only missing `a PR with some documentation on how to manage the site configuration` at this point, correct? I'll add it sometime this week.
