### ISSUE TITLE
Consolidate all "pre auth logon logo images" into one svg value held in SiteConfig

### ISSUE THREAD

**Issue by leewynne** [thepracticaldev/dev.to#5477]
**Is your feature request related to a problem? Please describe.**

As a future admin of a generalised community I would like to ensure that I can set a value in SiteConfig for all community icons displayed during pre auth navigation and at the auth request.

**Describe the solution you'd like**

A value set for each experience in SiteConfig (similar to logo SVG and favicon). With some variants allowed depending on where the logo is displayed (within the feed, when attempted to complete any actions that require auth).

**Additional context**

See some screenshots of the images in question.

Embedding in the feed.
<img width="594" alt="Screenshot 2020-01-13 at 09 18 11" src="https://user-images.githubusercontent.com/12694270/72244766-e0e3d800-35e6-11ea-998c-f6fa7c140b40.png">

Attempting to interact with an article
<img width="776" alt="Screenshot 2020-01-13 at 09 27 44" src="https://user-images.githubusercontent.com/12694270/72244831-01ac2d80-35e7-11ea-9983-23d75ce8ff3c.png">

**Comment by benhalpern** [comment]
I think establishing configs of `primary_sticker_image_url`, `secondary_sticker_image_url` (because we sometimes use rainbow and sometimes use purple as alternatives in different areas. I think that's a decent pattern for other communities.

And then we can add `mascot_image_url`. This means each community needs its own mascot.

And then we need a dedicated `tagline` which can replace "We're a place where coders..." (This will help us use the same tagline everywhere).

And then the question is what to do about the "x amazing humans who code". I could see replacing "amazing humans who code" with a variable describing who is part of the community, and keep the rest of the "NAME is a community of x" as part of the hardcoded format.

**Comment by JibranKalia** [comment]
@benhalpern The only thing missing in order to complete this issue is implementing `secondary_sticker_image_url`. However, that purple logo is implemented in jsx. I am not really sure how to push SiteConfig details into javascript. Do you have somewhere else in the code which does something similar. Just need to see a similar pattern.

**Comment by JibranKalia** [comment]
@thepracticaldev/oss ^^^.

**Comment by JibranKalia** [comment]
@thepracticaldev/oss ^^^

**Comment by rhymes** [comment]
Hi @JibranKalia, could you point us to the place in the core you're referring to? I'm not sure I understood :(

**Comment by JibranKalia** [comment]
Sure. @rhymes. Here: https://github.com/thepracticaldev/dev.to/blob/bbe0bf970fee1995ecce20bf788da3818c70064d/app/javascript/onboarding/components/IntroSlide.jsx#L99

**Comment by rhymes** [comment]
Got it! i think there's a way to get the JSX file to find the file through the `SiteConfig`.

If you look at this file:

https://github.com/thepracticaldev/dev.to/blob/bbe0bf970fee1995ecce20bf788da3818c70064d/app/javascript/packs/feedIcons.js.erb#L1-L7

you can see how they've imported images in a JS pack.

After that you can embed the image in the JSX with something similar to

https://github.com/thepracticaldev/dev.to/blob/bbe0bf970fee1995ecce20bf788da3818c70064d/app/javascript/articles/Feed.jsx#L3

Hope this helps!

**Comment by JibranKalia** [comment]
@Ridhwana I am actually not able to get this atm. Can this be reassigned. I don't want to hold up the issue.

**Comment by JibranKalia** [comment]
I actually noticed that benhalpern implemented `secondary_sticker_image_url` in PR https://github.com/thepracticaldev/dev.to/pull/8431/files. I believe this issue is complete and can be closed.
