### ISSUE TITLE
Error with Syntax Highlighting with XML markup mixed with Ruby

### ISSUE THREAD

**Issue by CalvinAllen** [thepracticaldev/dev.to#5680]
I normally utilize the RSS import from my blog into dev.to, but I ran into this problem there, so I tried the v2 editor - and it still exists.  I'm not certain if I'm doing something wrong in the markup, given the code block, but I cannot get it to work at all

**To Reproduce**

Create a new post using the v1 or v2 editor, and utilize syntax highlighting on a mixture of Ruby/Liquid tags, and XML code, marked as XML:

```
```xml
{% assign cover_image = post.path | prepend: '/' | prepend: site.source %}
{% capture cover_image_exists %}{% cover_exists {{ cover_image }} %}{% endcapture %}

{% if post.image and cover_image_exists == "true" %}
    <media:thumbnail xmlns:media="http://search.yahoo.com/mrss/" url="{{ site.url }}{{ post.url }}{{ post.image }}" />
{% else %}
    <media:thumbnail xmlns:media="http://search.yahoo.com/mrss/" url="{{ site.url }}/images/social/headshot.jpg" />
{% endif %}
<three backticks here - messes up formatting of issue>
```

**Expected behavior**

I would expect the code within the block to highlighted as xml (even though there is ruby markup inside as well), however, when I post (or preview), the highlighting is messed up starting with the initial backticks.

**Screenshots**

![markdown](https://user-images.githubusercontent.com/41448698/73025481-adcaf100-3dfd-11ea-9723-e0e94e5f71e2.png)
![preview](https://user-images.githubusercontent.com/41448698/73025482-adcaf100-3dfd-11ea-9f84-3a90d0f014ab.png)

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Edge (Dev Channel) - Also tried others
- Version:

**Smartphone (please complete the following information):**

- Device: N/A
- OS:
- Browser:
- Version:

**Additional context**
N/A

**Comment by rhymes** [comment]
Interesting, it must be a bug in the RSS reader, because it works correctly both in the editor v1 and v2:

**v1**

![Screenshot_2020-01-24 New Post - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/73070210-0fe42e80-3eb0-11ea-8f35-293a744d5912.png)
![Screenshot_2020-01-24 New Post - DEV(local) Community 👩‍💻👨‍💻(1)](https://user-images.githubusercontent.com/146201/73070212-0fe42e80-3eb0-11ea-9a86-0397e0773b3f.png)

**v2**

![Screenshot_2020-01-24 New Post - DEV(local) Community 👩‍💻👨‍💻(2)](https://user-images.githubusercontent.com/146201/73070219-15417900-3eb0-11ea-94c5-87c573390b90.png)
![Screenshot_2020-01-24 New Post - DEV(local) Community 👩‍💻👨‍💻(3)](https://user-images.githubusercontent.com/146201/73070220-15417900-3eb0-11ea-8f45-31d45302256e.png)

**Comment by CalvinAllen** [comment]
@rhymes That's so weird!  My original issue stemmed from the v1/RSS import, but the screenshots above are when I tried to recreate the issue in the v2 editor (new post instead of import).  Now I'm even further confused :)

**Comment by CalvinAllen** [comment]
Now I'm starting to wonder if this is, in fact, an issue with Edge....  Doing some more testing

**Comment by CalvinAllen** [comment]
I FINALLY figured it out (thanks to your help @rhymes).  In the text prior to the first code block, I had a rogue backtick, which was throwing off the rest of the document (but didn't seem to cause any issues inline where it existed).

I think this ticket can be closed, entirely my fault it seems :)

**Comment by rhymes** [comment]
Thank you for getting to the bottom of this! Glad you figured it out!
