### ISSUE TITLE
Send a comment with Ctrl+Enter

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#57]
I'd want to send comments with <kbd>Ctrl+Enter</kbd>. Should be pretty easy to implement 😃

**Comment by jessleenyc** [comment]
Thanks for the suggestion!

**Comment by pkfrank** [comment]
Hey @Defman21 — nice suggestion.  I'm a big gMail user, so I definitely find myself hitting "cmd+enter" to try and finish a comment sometimes.  While I'm _personally_ advocating for us to knock this out, I think it's something we're going to wait on until we're open-source, so that the community can implement it :)

We'll likely make it opt-in on the /settings page, so power-users like us can publish comments with cmd+enter while other people reach for their cursors.  Thanks again for the suggestion!
