### ISSUE TITLE
Handle Missing Chat Channel During Creation

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#5951]
During the chat channel creation process, at some point, we are not able to create a chat channel for some reason with the chat_channel_membership. This causes the validation on the chat_channel_membership to fail with the following error. 

Honeybadger: https://app.honeybadger.io/fault/66984/aa81805a11e4c8c9763e9a9cb665ebcf
Error:
```
NoMethodError: undefined method `direct?' for nil:NilClass
chat_channel_membership.rb  88 permission(...)
[PROJECT_ROOT]/app/models/chat_channel_membership.rb:88:in `permission'
86 
87   def permission
88     errors.add(:user_id, "is not allowed in chat") if chat_channel.direct? && chat_channel.slug.split("/").exclude?(user.username)
89     # To be possibly implemented in future
90     # if chat_channel.users.size > 128
```

Steps to Reproduce: 
I am not sure how to directly reproduce this, that will require a little investigation, but my theory is that the chat_channel is not valid in some way but we continue to try and create the membership regardless and fail on validation. Once again this is totally a guess I have not had the chance to really dig into it.

**Comment by atsmith813** [comment]
I'll take this one 🙋‍♂️

**Comment by atsmith813** [comment]
This one is very strange 🤔 I'm able to get the same error by forcing an invalid `ChatChannel` which supports your hunch (@mstruve).

I can't find a use case though where a `ChatChannel` is being created with invalid params. I'm wondering since this error has only happened twice if it's an edge case of some sort.

Following the stack trace, it looks like this all starts in the `chat_channels_controller` under the `create_chat` action.
https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/chat_channels_controller.rb#L74-L91

On line 79 we call `ChatChannel.create_with_users([current_user, chat_recipient], "direct")`.

That takes us to the `ChatChannel` model to the `create_with_users` method:
https://github.com/thepracticaldev/dev.to/blob/master/app/models/chat_channel.rb#L54-L83

If I jump into the code just above line 72 where we are creating a new channel and invalidate the arguments (i.e. set them all to `nil`), I'm able to reproduce the error. We could perform a check like `channel.valid?` after we try to create it and handle this situation.

Diving further in, I'm not sure what use case would take us into this scenario where the arguments are invalid. Going in order of arguments from calling `.create`:
- `channel_type`: this is called with "direct" which is the same as the default value. It's valid and isn't changed.
- `contrived_name`: this is built above on line 59 based on the `users` Array that is passed in. The issue isn't that one or both of the `users` in the Array are `nil`, because that would result in  `undefined method 'username' for nil:NilClass` instead of the error in HoneyBadger.
- `slug`: this is also built from the `users` Array and is a String.
- `last_message_at`: straight forward, valid timestamp.
- `status`: `"active"` is a valid status.

I looked at the DB table and the model for any additional validations that I might be missing and didn't find anything. This leads me to believe this is some edge case where the specific users have some attributes (username?) that are causing issues. Or there is some sort of race condition where when we go to create it, the `slug` we are providing is no longer unique (even though we try to search by that just above it).

Anyone have a little more context on this behavior to help me understand how we might be ending up in this scenario? Maybe the solution is to catch the error and log these arguments so we can see if/when it happens again what is going on?

**Comment by rhymes** [comment]
Pinging @sarthology who might know more

**Comment by mstruve** [comment]
I'm game for logging and waiting to see if it becomes a bigger problem.

**Comment by sarthology** [comment]
> Pinging @sarthology who might know more

Haven't encountered this before.

**Comment by mstruve** [comment]
Closing since we are tracking in Honeybadger and no further action needs to be taken. Will re-open if we determine its worth fixing.
