### ISSUE TITLE
Syntax highlighting should work regardless the case of the hinted language

### ISSUE THREAD

**Issue by fintatarta** [thepracticaldev/dev.to#6352]
# The problem
When including Ada code with   "```Ada" the code remains in black-and-white instead of being syntax highlighted. 

# What to do
I think that it would be nice to have syntax hightlight with Ada too.  I am willing to do this, but I do not know how.  If someone points me to some documentation and maybe an example of highlighting for other languages, I can give it a try.

# Alternatives?
Well, I do not see many. Just keeping the black-and-white look?  Using the highlighter for other languages does not make much sense.

**Comment by rhymes** [comment]
Hi @fintatarta, it's probably just a "case of upper casing" 😄 

I was able to highlight by using `ada` instead of `Ada`:

![Screenshot_2020-02-28 test ada - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/75536898-4e708a00-5a16-11ea-8461-0a9d92db5328.png)

![Screenshot_2020-02-28 Edit Post - DEV(local) Community 👩‍💻👨‍💻](https://user-images.githubusercontent.com/146201/75536909-53cdd480-5a16-11ea-830f-40e88f368380.png)

Let me know if I can be of further assistance, I'm going to close this in the meantime!

**Comment by fintatarta** [comment]
Oops...  Silly me, trying the lower-case version did not come to my mind.  Sorry

Maybe making both cases acceptable?  Unless there is some convention to always use the lower case version (so it is "php" instead of "PHP") 
The language name is always referred as "Ada" since it is a person name (OK, someone tries with "ADA," but it is immediately corrected... :-) )

**Comment by rhymes** [comment]
@fintatarta I see your point but unfortunately I think all syntax highligthing hints are required to be lowercase regardless of the official spelling of the language.

I just tried "Python" instead of "python" and it didn't work as well. 

As we're using a third party library, [rouge](https://github.com/rouge-ruby/rouge), we don't have direct control on this.

I just tried to verify this:

```ruby
[7] pry(main)> Rouge::Lexer.find("python")
=> Rouge::Lexers::Python
[8] pry(main)> Rouge::Lexer.find("Python")
=> nil
```

**but**

I also think I found a fix, I'm going to reopen this and submit a possible fix. I'll also slightly alter the issue title so it's clearer.

Thanks a lot @fintatarta!
