### ISSUE TITLE
Flash of empty results in /listings typeahead search

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#6444]
On every keystroke there is a brief moment of "no results" before the results load.

I presume this is due to a state where we first get rid of results before replacing them.

Ideal behavior is such that old results are still visible until the new ones populate.

**Comment by gonzar11** [comment]
I would like to grab it.

**Comment by rhymes** [comment]
Go ahead @gonzar11, thanks!

**Comment by gonzar11** [comment]
The same happens when a tag or category is selected. Should we fixed it too?

**Comment by rhymes** [comment]
If you can, yes! Thank you!

**Comment by gonzar11** [comment]
Hey @rhymes I am seeing that `updateListings` method is being called with empty listings. Should we remove it? Could we put `bumped_at` as a filter in ES ?

**Comment by rhymes** [comment]
Hi @gonzar11, it's a bit hard to reason on the correct solution without seeing where the issue lies. 

You do make a good point though I think `bumped_at` can already be used as a filter

Could you submit a draft PR when you're a good point? I'm not totally familiar with how the code works by memory :-/
