### ISSUE TITLE
GitHub Gists rendering in the wrong order

### ISSUE THREAD

**Issue by vanaf1979** [thepracticaldev/dev.to#6469]
GitHub Gists rendering in the wrong order

When a posts has more then one GitHub Gist embed, sometimes (Not always) they render in the wrong order. After a page refresh the do render correctly. I haven't noticed this anywhere else, so it might be a problem with the page rendering.

It was also reported to me by another reader: https://dev.to/vanaf1979/wp-snippet-008-using-transients-to-cache-data-35in

I have noticed this in multiple versions of Firefox on Mac. 

MacOs 10.12.6
Firefox 73.0.1

**Comment by rhymes** [comment]
Hi @vanaf1979, thanks for the raising this issue.

I dug a bit in our issue backlog as I remembered something like it and found out it's a long standing issue we haven't totally fixed.

See https://github.com/thepracticaldev/dev.to/issues/1679

It seems like @maestromac was close to what the problem was in https://github.com/thepracticaldev/dev.to/issues/2648#issuecomment-499218652

I'm closing this as a duplicate, please add your comment on [this issue](https://github.com/thepracticaldev/dev.to/issues/1679).
