### ISSUE TITLE
Gracefully Handle Missing Linked Users From Comments

### ISSUE THREAD

**Issue by mstruve** [thepracticaldev/dev.to#6499]
We recently received a Honeybadger where we went to save comments that both raised errors due to no being able to find linked users.
Honeybadgers:
https://app.honeybadger.io/fault/66984/ac0e5bc2313665cb976dee458505349b
```
StandardError: Invalid username
 user_tag.rb  25 parse_username_to_user(...)
[PROJECT_ROOT]/app/liquid_tags/user_tag.rb:25:in `parse_username_to_user'
23   def parse_username_to_user(user)
24     user = User.find_by(username: user)
25     raise StandardError, "Invalid username" if user.nil?
26 
27     user
```

In these situations, we should gracefully handle the missing user or comments and NOT raise an error. There will be times when users leave the platform and any internal markdown links should not break their related models because of it.

**Comment by Math3v** [comment]
@mstruve I would like to take a look. Have you got any particular solution in mind? When users or articles "leave" the platform, are they gone for good, or are they only marked as deleted? Thanks!

**Comment by danascheider** [comment]
@Math3v are you still working on this? If not I can take a stab at it.

**Comment by Math3v** [comment]
@danascheider I'm not currently, would be awesome if you had a look at it. Maybe it will be really beneficial if you take a look at my solution and the comments I received from the team. :)

**Comment by danascheider** [comment]
Cool, thanks, I'll take a look at what you worked on and see what I can figure out!

**Comment by rhymes** [comment]
@danascheider I'm going to assign you to the issue :)

**Comment by danascheider** [comment]
I have a couple questions about this issue:
1. If a user is missing, presumably we will want to use some kind of default colours. What should those be?
2. What should we do with the parts of the partial that display data that won't be available for a deleted user, such as the follow button, user Twitter handle, etc.?

One idea I had, going off the comments in #6638, was to use an object like this for the user:
```ruby
OpenStruct.new(username: "username", object: <User object or nil>)
```
Then if the user does exist, we can still use the decorator on the user object in `render`, which wouldn't be as easy if we just used the `:persisted?` key as was suggested in the other PR.  If the `:object` is `nil`, we will know the user doesn't exist and can handle it differently.

Does this sound like a reasonable path forward?

**Comment by rhymes** [comment]
Tagging @mstruve and @citizen428 who have been talking about handling `NullUser`s

**Comment by mstruve** [comment]
@danascheider I am not sure how the url would work but if we want to go the empty user route I would try this. 
```ruby
user = User.find_or_initialize_by(username: user)
```

If the user is not found we return an unpersisted user object. I used a similar [pattern here for tracking user ips](https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/application_controller.rb#L100)

**Comment by danascheider** [comment]
Thanks @mstruve, that makes more sense!

**Comment by danascheider** [comment]
I've gotten it to a point where the liquid tag for a deleted user now looks like this:
<img width="644" alt="Screen Shot 2020-05-16 at 9 02 50 am" src="https://user-images.githubusercontent.com/5115928/82102932-74bfdf00-9754-11ea-94d2-81aca66f7f28.png">
(The profile image is messed up because in my local it's getting a 404 from the default profile image URL.) It seemed like poor UX to just have the username as alt text and then no header, so I gave the deleted user a name of `[Deleted User]` too. The catch is, the header text (the user's name) is a link to `user.path`, which of course does not exist for a deleted user.

The ideas I had for handling this were:
1. Change the `User#path` method to return a default or nil path if it's a deleted user
2. Change the template to not render a link if it's a deleted user.
3. Some combination of the two (don't render a link if the path is `nil`?)

Do any of those approaches sound reasonable to you, or is there another way you think this should be done @mstruve?

**Comment by mstruve** [comment]
I would render the username of the person and then that is it and nothing else. Prevent it from creating a nice little stylized link since there is no longer anything to link to.

**Comment by danascheider** [comment]
You got it, thanks!
