### ISSUE TITLE
[P2] Build onboarding task card in feed

### ISSUE THREAD

**Issue by lisasy** [thepracticaldev/dev.to#6552]
### Description
Build an onboarding task card in feed after people leave the onboarding flow so that they have clear call-to-actions.

_Note: this will be a new component we're introducing to feed._

### Design assets

![#6552 onboarding task card](https://user-images.githubusercontent.com/816402/77117307-fc0c0300-69ee-11ea-858d-05549050e751.png)

**[✨ Figma URL ✨](https://www.figma.com/file/fQthjjBLgDLRaHmpIwlhdS/Onboarding?node-id=551%3A23221)**

**Comment by vaidehijoshi** [comment]
@lisasy what's the difference between the default and the hover states on the feed task card? i don't see a difference aside from the `X` having moved locations 🤔

**Comment by vaidehijoshi** [comment]
When the user finishes the `FollowUsers` slide by clicking on `Continue`, we need to redirect them to the feed. This will mean making passing in a function to the `Navigation` component (when it is rendered in the `FollowUsers` component) so that it can handle this redirect.

We'll also need a way redirecting to the feed with the knowledge that we want to display the onboarding task card in the feed. Perhaps we could pass along a param (cookie?) that we can use on the `/feed` page to decide whether or not to render the onboarding task card?

If we decide to send a cookie through here, we could use that to decide when to dismiss the onboarding task card as well.

We'll also want to remove the `ClosingSlide` entirely out of the Onboarding modal flow.

@maestromac I'm curious to hear if you have thoughts on how we should go about actually implementing the onboarding task card. Have we done something like this before? If there's something we can reuse, that seems ideal, otherwise I suppose we can create a new component for this that we render directly above the `homePageFeed`? Let me know what you approach you'd take here.

**Comment by lisasy** [comment]
@vaidehijoshi 

Whoops, the mocks are missing some additional descriptions to explain the difference between the default and hover states 😂 I'll fix this. But in brief, in the hover state example, the second action is "hovered" and the background is slightly lighter 😆

If a user clicks on "Continue" on `FollowUsers`, it does not close the entire onboarding flow because the next step is the `EmailPreferences` step.  Therefore, `Continue` takes them to `EmailPreferences`. I attempted to address these questions through this issue here: 

https://github.com/thepracticaldev/dev.to/issues/6544

Also happy to go over this again in the Figma walkthrough next Monday. Let me know if that helps answer any open questions.

**Comment by lisasy** [comment]
Updated the image. Hope it's clearer!

**Comment by maestromac** [comment]
@vaidehijoshi the closest thing the team has implemented is the latest shecoded campaign banner. I agree we should definitely rely on cookies and create a new component mounted on top of `homePageFeed`

**Comment by lisasy** [comment]
Notes from PR #6667 (Phase 1)

When we write the code for the different onboarding actions (e.g. make a welcome post), we should update them to match the emoji of each <span>, so that we're actually making this modal accessible.

@vaidehijoshi 

---

<img width="651" alt="Screenshot 2020-03-20 10 17 47" src="https://user-images.githubusercontent.com/816402/77189269-878b9f80-6a94-11ea-9705-2b24c85ae13e.png">

**Comment by vaidehijoshi** [comment]
@maestromac + @lisasy after watching the figma walk through meeting's recording, i think we should attempt to make a separate component with the desired behavior for this tile/task card. i have some ideas on how to push the feed down, but i would need to actually dip into the code and try it out (i could be very off base 😂).

i do agree with @lisasy's comment in the meeting that, eventually, we want our design system to be able to handle sending different kinds of messaging out to our users. in fact, i think we'd ideally want to combine the shecoded hero banner with this task card; i can imagine us having an entire messaging service in place in our system so that it's pretty easy to send out different kinds of messages to our users, whether those messages are a one-time thing (like shecoded) or can be automated (like this task card) or are reoccurring (for example, a message that tells folks that DEV is experiencing downtime!).

but, given that this specific task is the _last_ thing in our list of MVP goals, we can use the shecoded approach if we find ourselves running out of time. but if we have the time, i'd say that it's worth trying to implement this the right way, rather than the fast way. we can see how it plays out when we get there, though!

**Comment by lisasy** [comment]
@vaidehijoshi @maestromac 

This plan sounds good to me! As we're nearing approaching this task, I can certainly whip up a quick design of the She-Coded, full hero banner version to help us envision what shipping this version might look like. I'll track this task!
