### ISSUE TITLE
Jump to comments does not work properly

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#657]
## Bug Report

1. Click on the comments counter.

### Current Behavior

You jump somewhere in the middle of the article.

### Expected Behavior

You jump right to the comments.

### Mobile & Desktop Screenshots/Recordings

`None`

### Additional Info (device/browser, helpful links)

I guess that happens because you use turbolink. It injects some new HTML and the browser jumps before the content has loaded.

It doesn't happen on every article though. Only those who has more than text: code blocks, images or `%{ }%` things in them (twitter widgets, etc.). For example: https://dev.to/msarit/the-blessing-of-rejection-or-growing-past-theno-44bi

**Comment by Zhao-Andy** [comment]
Hey @Defman21, thanks for the report. I suspect you're correct about the browser moving there before the content has fully loaded.

**Comment by Defman21** [comment]
bump. Still happens.

**Comment by Defman21** [comment]
Firefox Nightly 66.0a1, Windows 10. Reproducible with [this](https://dev.to/damnjan/when-php-framework-sucks-series-how-not-to-shape-your-app-in-the-shape-of-the-framework-4dm6) article, for example (you have to jump to the comments from the `/` though).

**Comment by maestromac** [comment]
`This video is unavailable.` to me :(

**Comment by Defman21** [comment]
Uh oh, I thought "Private" would allow me to share links. Give me a sec, I'm going to make it unlisted then.

**Comment by abraham** [comment]
I can reproduce this on Firefox 64.0 on Ubuntu. It looks to me like it's caused by the inline images in the post.

- [This post has a small image and was misaligned by a small amount](https://dev.to/itsjzt/declarative-programming--react-3bh2#comments)
- [This post has a larger image and was misaligned by a larger amount](https://dev.to/damnjan/when-php-framework-sucks-series-how-not-to-shape-your-app-in-the-shape-of-the-framework-4dm6#comments)
- [This post has no inline images and was not misaligned](https://dev.to/kelly/freelancing-101-how-to-get-started-36kg#comments)

There are some instances where the image might already be loaded/cached on the client and it will be aligned correctly then.

**Comment by Defman21** [comment]
Not only the images, but any other embeds (such as Github snippets, codepen, etc.)
