### ISSUE TITLE
Discussion count doesn't increase when a user comments.

### ISSUE THREAD

**Issue by samuraiseoul** [thepracticaldev/dev.to#668]
## Bug Report
Discussion count at bottom of the page doesn't update when you comment.

### Current Behavior
When you comment on a post, the discussion count at the bottom stays the same as before the comment was uploaded.

### Expected Behavior
Discussion count increases by one.

### Additional Info (device/browser, helpful links)
Kubuntu 16, Chrome

**Comment by darol100** [comment]
I think, I just experience this bug here is a screenshot of the mismatch of comments:

![screen shot 2018-09-26 at 10 55 55 am](https://user-images.githubusercontent.com/6808460/46099337-5cfca700-c17b-11e8-9469-f68d200c9fbf.png)


This happen on my profile this is my [Dev.to profile](https://dev.to/darol100)

**Comment by samuraiseoul** [comment]
No, my bug was different. Similar though. Mine happens on an actual article where you comment. The count doesn't increase in real time.

**Comment by maestromac** [comment]
Thank you for this issue and sorry we let this one slip through @samuraiseoul . This is probably a caching related issue. I checked it just now it seems to be resolved. Let us know if otherwise!
