### ISSUE TITLE
Allow users to opt-out of welcome notifications

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#6705]
Some users may not want to receive welcome notifications. We should allow them to opt-out/unsubscribe from welcome notifications. Once a user has opted-out of welcome notifications, they shouldn't receive any new ones!

We might want to use notification subscriptions in order to implement this. We also should sync up with @lisasy and see if she has ideas on how to include an "opt-out" link at the bottom of a welcome notification that comes from Sloan.

**Comment by Ridhwana** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by lisasy** [comment]
![Screenshot 2020-03-24 09 44 03](https://user-images.githubusercontent.com/816402/77453083-03972780-6db4-11ea-9d31-47b5151ebcd5.png)

Based on this design and copy, when people have joined DEV, they don't know that they're going to receive a series of welcome notifications from DEV. Therefore, when we think about how to include the opt-out link, the copy should allude to that... I'll explore some light options later and share it with you and the team.

**Comment by vaidehijoshi** [comment]
While working on implementing this today, I realized that there are really two different approaches that we can take in terms of how we want to message the opt-out functionality; as it turns out, the two different approaches significantly impact _where_ the opt-out functionality should live.

Here are two different ideas that I have for how we can surface this to users:
1) Include the opt-out link in the notification itself (or maybe just in the first one):
<img width="1293" alt="Screen Shot 2020-03-24 at 8 53 25 PM" src="https://user-images.githubusercontent.com/6921610/77500274-cd889080-6e11-11ea-946a-85afd32c6b29.png">

2) Include the opt-out as an option on the `/settings` page:
<img width="1310" alt="Screen Shot 2020-03-24 at 8 53 15 PM" src="https://user-images.githubusercontent.com/6921610/77500297-dbd6ac80-6e11-11ea-8ca3-62992abcb4d5.png">

Visually speaking, I like option 1 better because this approach makes it pretty clear to see how to stop the notification if you don't want to receive it. However, from a code-standpoint**, it makes logical sense to go with option 2, which is where we store all the other "subscription setting" information. But visually, imo, it feels weird to put it on the `/settings` page. It's not really an email notification, nor is it a mobile one; if you look at option 2, you'll see that I have had to include a small note to explain what on earth the notification even _is_. My intuition tells me that maybe the welcome notifications are different enough that they ought not live here...but I'm not sure if option 1 is the right choice, either.

Really curious to hear what folks have to say about this! Please let me know what you think 😄 


**The approach I've taken for this is just to add a `welcome_notifications` column to the `users` table, since this made much more sense than trying to use `notification_subscriptions` here given that we'll be dealing with multiple Welcome Broadcasts, rather than just one Article or a Comment.

**Comment by maestromac** [comment]
I like a combination of both approaches. Here's what I think

- Instead of `click here` in the notification, have it as `go to your settings page to disable...` link.
- I think the option there is fine but perhaps only show that field `if user.created_at > 7.days.ago`

I'm getting way ahead of myself here but I can also imagine platform notification to be used to announce new features.

**Comment by lisasy** [comment]
@vaidehijoshi @maestromac 

I like @maestromac's suggested revision to the copy for the opt-out link. Rifting off of that, what if we had something like this that clearly states what they can manage? The entire sentence can be a link.

`Go to your settings to manage your notification settings`

**Comment by juliannatetreault** [comment]
I agree with @maestromac and @lisasy--the combination of both approaches and I like @lisasy's copy. I think that disabling the notifications makes the most sense in the settings and having a link in the notification itself that clearly directs to the settings would make opting out simple. I think that directing new users to the settings page early on is good to do anyway since a handful of the onboarding notifications point to functionality that lives in the settings. By doing this, we'll make it easier for new users to accomplish things like customizing their experience and connecting their GitHub/Twitter.

**Comment by vaidehijoshi** [comment]
@maestromac Great idea! I guess my 9pm self last night just didn't think about combining both approaches, but I think that feels right 😅

Also going to incorporate @lisasy's copy.
