### ISSUE TITLE
Older version of React in production

### ISSUE THREAD

**Issue by nainardev** [thepracticaldev/dev.to#6921]
![Screenshot (156)](https://user-images.githubusercontent.com/59839368/77823972-0c298e00-7125-11ea-9caf-e2b907d7ed71.png)

**Comment by rhymes** [comment]
Hi @nainardev, thanks for the heads up! 

We're actually using Preact (not React). That's probably why the extension is flagging it. It could also be because we're not using the latest available Preact, which is 10, but version 8.

We're working on a PR - #5639 - to update that as well. Hopefully the extension you're using won't flag that :D
