### ISSUE TITLE
Allow admins to suggest default users to follow during onboarding

### ISSUE THREAD

**Issue by vaidehijoshi** [thepracticaldev/dev.to#7106]
Currently, in our onboarding flow, we suggest users to follow (see `Suggester::Users::Recent` service [in the `users_controller`](https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/users_controller.rb#L17-L21)).

However, for newer communities, the list of suggested users to follow isn't populated:
<img width="837" alt="Screen Shot 2020-04-28 at 1 54 57 PM" src="https://user-images.githubusercontent.com/6921610/80536855-e677ea80-8957-11ea-9276-4c38a018795b.png">

We should allow admins to select which users to follow by "default" when their communities are very new/still small. We could probably do this by allowing for a default list to be set via the `SiteConfig` by admins with access, and then showing that in the onboarding flow when applicable.

**Comment by vaidehijoshi** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by vaidehijoshi** [comment]
Looking at this again, I wonder if we should create a separate tab on the `/internal` page that is specifically devoted to Onboarding. That way, there would be a singular place for customizing the placeholder text, the default users to follow, and the already-existing `suggested_tags` on the SiteConfig. 🤔

Or perhaps, maybe we just have one section of SiteConfig just be "Onboarding"? It just seems like there's a lot of stuff happening in SiteConfig and I am weary of overloading it!

**Comment by Ridhwana** [comment]
I would think that the onboarding config should lie with the config view so that users know where to find anything related to configuring their site. We also have a lot of pages/links on the internal interface at the moment so grouping things that are configuration related makes most sense to me, and I'm not sure that it would be obvious t to configure their sites in two separate places even if they are for different parts of the system.

I do however agree that there is _a lot_ happening on the page but I also think that it's nicely separated out into sections that are pretty well defined. We definitely need to do work on this view though, we'd discussed this as a concern at the beginning of our cycle, and some of the options were implementing a tabbed view or just generally a more easily navigable view, we (and well the design team) would need to play around with the UX.

An alternate suggestion could perhaps be to keep the onboarding on a separate page but link/or route it from the config page.

**Comment by vaidehijoshi** [comment]
@Ridhwana Okay, I think this makes sense to me and I tend to agree the more that I look at the `/internal/config` page. One thought I have is to pull out the "suggested tags" into a section of the config that is just used for onboarding, and I think that route will be the best of both worlds at the moment (easier to navigate, but still all in the same view).

**Comment by Ridhwana** [comment]
That sounds pretty good to me 😊
