### ISSUE TITLE
Add "redirect" functionality as an admin option

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#7267]
**Is your feature request related to a problem? Please describe.**
As an admin, I sometimes set up recurring threads such as the Welcome and Challenge threads.  The latest of these threads can be accessed at...

- https://dev.to/welcome
- https://dev.to/challenge

These redirects are currently hardcoded into the app.

**Describe the solution you'd like**
As an admin, I'd like to be able to set up a redirect from a page within `/internal`.

I should be able to do something like: redirect to the latest post by a **specified user** in a **specified tag**.

This would allow us to say:
- Redirect `/welcome` to the latest published `thepracticaldev` post in `#welcome`
- Redirect `/welcome` to the latest published `thepracticaldev` post in `#challenge`
- etc.

**Additional context**
We'll be using this as part of a new recurring thread soon, and it seems like a good time to build the functionality.

As mentioned, searching for `/welcome` and `/challenge` in the code should highlight how we're doing this currently.

**Comment by benhalpern** [comment]
I think we add this as yet another type of object which responds to top-level namespace, or possibly make this a "type" of "page".

This should all fit our current logic for finding welcome and tag posts and give the capacity to extend this behavior.

**Comment by jitendra1998** [comment]
Hi @pkfrank and @benhalpern, interested in working on this feature.

**Comment by rhymes** [comment]
Hi @jitendra1998, you're welcome to do it! Ping us here or in a draft PR if you need any help or have questions. I'm going to assign you the issue in the meantime. 

ps. you can create a new section in `/internals` panel, "Redirects" for this

**Comment by atsmith813** [comment]
A couple of things to keep in mind*...redirects can "ding" our SEO authority. @pkfrank do we care about the SEO juice on these endpoints (i.e. `/welcome` and `/challenge`)?

If so, we should use 302 redirects so we don't hurt our SEO and pass on the juice to other places.

If not, we might want to re-think this a bit. We can dynamically redirect with 302 still, but no SEO juice will be transferred. So that means whatever we redirect to won't get that boost which may be fine if the context of these pages is changing all the time anyway. But if these pages are higher trafficked, that's a tradeoff to consider.

Redirecting with 301 to dynamically returned content (i.e. the latest published post is constantly changing) is also not the best for SEO. You'd basically be telling Google every day that the content at this endpoint has permanently moved and therefore sending SEO juice all over the place. Google is smart enough to understand a redirect, but it will be much less optimal SEO wise, especially over time. AFAIK, Google doesn't bash you hard for redirecting. I believe it does start to hurt if you keep redirecting the same URL (`/welcome`). A potential solution is to redirect to something less dynamically determined.

_*I'm far from an SEO expert, just chiming in some thoughts about redirect behaviors that I've dealt with in the past. If someone is more plugged in with SEO practices, they should definitely chime in 😄_

**Comment by atsmith813** [comment]
Hey @jitendra1998 👋! We haven't heard from you. Just a heads up that we're going to close this issue in favor of a re-scoped version https://github.com/thepracticaldev/dev.to/issues/8075 that doesn't use dynamics redirects because that hurts our SEO. If you're still interested in working on it, feel free to hop over to the new issue and drop a comment/claim it. Thanks for your help!
