### ISSUE TITLE
Remove notification if email was viewed

### ISSUE THREAD

**Issue by jvanbruegge** [thepracticaldev/dev.to#76]
It would be cool to mark a notification on the site as read, if the notification email was openend.

**Comment by Zhao-Andy** [comment]
Thanks for the feedback!

**Comment by jessleenyc** [comment]
Putting this on our backlog.

**Comment by Booligoosh** [comment]
@jvanbruegge IT WOULD BE SO COOL IF EVERY WEBSITE HAD THIS

**Comment by jvanbruegge** [comment]
as far as i can tell this is still the case

**Comment by benhalpern** [comment]
This could be done if we observed changes in email opens and then reflected it back to the relevant notification but it’s not really practical in our current setup.

Currently the "mark as read" concept is universal. Would it make sense to mark my entire notifications as read if one is opened?

Not sure this is practical in our current setup. But we are re-writing notifications and could keep this in mind for future functionality.

**Comment by bakedbird** [comment]
Even though this could be solved technically, and would be a nice feature, there are some legal terms that need to be addressed. This option must be opt-in and not tracked by default, in order to avoid conflicts with GDPR. I do not thing the value weights more than the time that needs to be invested for this particular issue to be resolved.

**Comment by jessleenyc** [comment]
Hey @jvanbruegge, thanks for submitting this request. We've let this idea stew for a bit and while this would be an awesome feature, we feel pretty aligned with @bakedbird's thoughts on this. Going to close this issue for now.
