### ISSUE TITLE
Issue with Rails in Docker setup

### ISSUE THREAD

**Issue by farzadbagheri** [thepracticaldev/dev.to#7663]
**Describe the bug**
Rails aborting while databases are being set up with Docker (LoadError: Error relocating /usr/local/bundle/gems/mini_racer-0.2.10/lib/mini_racer_extension.so...)

**Screenshots**
<img width="1437" alt="Screen Shot 2020-05-03 at 6 31 18 PM" src="https://user-images.githubusercontent.com/10763487/80927533-6d6bff00-8d6c-11ea-8eba-fb2d3f9adf18.png">

OS: Catalina

**Comment by citizen428** [comment]
Thanks for the issue @farzadbagheri! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
This seems to be a problem with Alpine's standard C library (musl instead of glibc), see https://github.com/sgerrand/alpine-pkg-glibc/issues/27

I have to think about how to resolve this, as to the best of my knowledge nobody on the core team uses Docker for their daily development and `mini_racer` was introduced to speed up specs in local development, see #7383.

Possible solutions:

1. Switch from Alpine to a glibc-based distribution. This would require more changes and I'm a bit reluctant to do that.
2. Don't install mini_racer when running inside Docker, which should be achievable with some `Gemfile` hackery.

**Comment by joshpuetz** [comment]
Pinging @jdoss as he's been experimenting with alternate containerization for DEV's development environment

**Comment by jdoss** [comment]
Hey @FarazPatankar give our revamped container setup a try. It should fix this issue. I am going to close this issue for now, but if you have any other problems with our container setup, please open a new one.

**Comment by FarazPatankar** [comment]
@jdoss I think you may have mentioned the wrong person. 😛

**Comment by jdoss** [comment]
@FarazPatankar Woops! My bad! Too much multi-tasking and not enough coffee on my end. My apologizes. I was moving too fast this morning.
