### ISSUE TITLE
Comments are not being truncated

### ISSUE THREAD

**Issue by ludwiczakpawel** [thepracticaldev/dev.to#7790]
Comments should truncate after approx 2 lines of text... Currently what happens instead: 

![image](https://user-images.githubusercontent.com/108287/81703855-68463880-946d-11ea-95d5-2c7e146a95a6.png)

They should also strip all the fancy stuff:

![image](https://user-images.githubusercontent.com/108287/81701141-e6a0db80-9469-11ea-892a-0668438f9d7c.png)

**Comment by rhymes** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by joshpuetz** [comment]
I'm on this: my clever CSS tricks (https://github.com/thepracticaldev/dev.to/pull/7579#discussion_r421052144) only works in a single paragraph 🤦 

I'm back to the drawing board: after discussing with @ludwiczakpawel I'm going to try to truncate these comments on the backend

**Comment by benhalpern** [comment]
@joshpuetz @ludwiczakpawel 

Maybe cut off divs after a certain _height_ and have a sort of "show full" button which could display kind of like this...

<img width="711" alt="Screen Shot 2020-05-12 at 10 57 02 AM" src="https://user-images.githubusercontent.com/3102842/81708656-61083600-943f-11ea-91af-aa19276536c6.png">

I kind of really like that we can have the fully rich comments available in feed like this at a tap and maybe this is the answer to ensure we're not cluttering the feed otherwise.

**Comment by ludwiczakpawel** [comment]
@joshpuetz @benhalpern 

#7797 introduces quick hotfix for truncating comments. Let's get back to this with proper solution after that.

**Comment by joshpuetz** [comment]
Closing as #7802 addresses this issue for now
