### ISSUE TITLE
PWA error on icons

### ISSUE THREAD

**Issue by lomby92** [thepracticaldev/dev.to#8158]
**Describe the bug**
The PWA app is not installable since the `manifest.json` has some errors on links used for icons.

**To Reproduce**
Go with Chrome (tested on Android) into `https://dev.to` and see that the prompt for install the PWA does not appear

**Expected behavior**
The prompt should be visible

**Additional context**

I have tried to directly access the second part of the URL of the 512px icon: https://practicaldev-herokuapp-com.freetls.fastly.net/assets/devlogo-pwa-512.png

It works so i think that the error could be of: https://res.cloudinary.com

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by fdoxyz** [comment]
Thank you again for the report lomby92. I'm checking this out now and it does seem like you're right about the problem in the manifest. I'll follow up on this issue soon.

**Comment by fdoxyz** [comment]
Hi @lomby92, we merged a fix for the image links thanks again for reporting this!

After giving it some time (because of caching) I'm getting the correct links in the manifest, but I still can't see the PWA prompt with my Galaxy S8 (Android 9). If you're able to check again I'd appreciate it, to confirm the issue is closed.

Also a bit out of topic but, I'd also recommend giving [the native app](https://dev.to/downloads) a try if you haven't already too 😄

**Comment by lomby92** [comment]
Thanks @fdoxyz, I can confirm that now it works. (Tested both on Chrome Desktop on Linux and Chrome on Android 9)
