### ISSUE TITLE
Timeouts when deleting a post

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#821]
**Describe the bug**
As a user, I want to be able to `Delete` my posts.  Currently, it occasionally times out.

**To Reproduce**
This seems to happen _more often_ with articles that have a lot of reactions/comments.  So, to reproduce, choose an article you're willing to delete with many reactions/comments and press `Delete` from your dashboard.

**Expected behavior**
The article is deleted without timeouts.

**Comment by rhymes** [comment]
I believe this is due to this line https://github.com/thepracticaldev/dev.to/blob/master/app/controllers/articles_controller.rb#L128

`destroy!` calls in a cascade all destroy methods of all related objects that can be deleted. If it's a *lot* of content it will take some times. Given that deletion is done in process (which means the user has to wait for everything to be deleted during their HTTP request) and given that Heroku times out at 30 seconds, this is a likely reason why big trees of content (the articles, plus many comments and many reactions and notifications) can go past the limit.

In addition there's this [before_destroy_actions](https://github.com/thepracticaldev/dev.to/blob/master/app/models/article.rb#L372) that executes before all of what I mentioned before, I guess this executes synchronously as well.

**Comment by maestromac** [comment]
Yep @rhymes ! give it a whirl.

**Comment by tylermcginnis** [comment]
Getting this as well.

<img width="508" alt="screen shot 2018-12-11 at 8 32 27 am" src="https://user-images.githubusercontent.com/2933430/49811039-a6db3f00-fd1f-11e8-95e1-49627e0f3327.png">

**Comment by Zhao-Andy** [comment]
This is still an issue, so raising it up again and adding a few details:

We could make the `destroy` action in the controller run asynchronously, but I don't think that's ideal. A better solution might be to write a service object whose sole responsibility is to handle destroying articles (and all the dependents).

A few -- but not exhaustive -- list of things we'll need to consider:
1. Properly purging all caches of the article, comments on the article, and possibly any cached routes (`/reactions?article_id=123` for example)
2. Removing the article and comments from Algolia's index
3. Handling any errors that might happen

**Comment by rhymes** [comment]
Hi @Zhao-Andy I haven't actually looked into it after all, I'm sorry. I don't think it's an easy PR for me because it requires familiarity with the caching system or Algolia and I don't have that.

Maybe you can give a read to the [analysis of the bug](https://dev.to/rhymes/come-with-me-on-a-journey-through-this-websites-source-code-by-way-of-a-bug-odj) I wrote back then on dev.to. 

There are a services and aspects to consider: caches, fastly, algolia, stream.io and probably others

I think the best solution is to do a two phase removal:

1. the user needs the article to be gone immediately
2. everything else (caches, algolia, fastly, stream.io maybe as well, dependent objects in the DB) can be removed out of process in the service object that tracks everything and cleans up

**Comment by rhymes** [comment]
still an issue

**Comment by mstruve** [comment]
We now destroy articles in the background 😄
