### ISSUE TITLE
Certain Long inputs in Editor results in double scrollbar

### ISSUE THREAD

**Issue by Amorpheuz** [thepracticaldev/dev.to#8216]
**Describe the bug**
A double scrollbar gets generated if you copy-paste a large amount of text, add a new line within the last four character spaces in the editor and other random behavior. On other occasions, it tends to work flawlessly. I think it has something to do with the `height`  logic for the textarea, but I haven't been able to dig deeper. Check the attached gif for a demo.

**To Reproduce**
1. Click `Write a post`.
2. Add content up to which would cause a scroll bar to appear (or the next few chars would cause a scroll bar to appear).
3. Paste long content/ write a long word/ add a new line by pressing Enter or Return.

**Expected behavior**
Either the text-area gets a scroll, or the main div does.

**Screenshots**
- The first action I perform here is to write a long word and press backspace.
- In the second action, I pasted a long Lorem-ipsum string.
![Bug Demo](https://user-images.githubusercontent.com/22113778/83412874-8550a480-a438-11ea-9af1-674ff2b78811.gif)
*demo from Firefox Developer edition*

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge Chromium and Firefox Developer Edition
- Version: 83 and 77.09b respectively

**Smartphone (please complete the following information):**

It does occur on mobile if I try to add a long word towards the end of the line, but the effect doesn't remain once I minimize my keyboard.

- Device: Nokia 6.1
- OS: Android 10
- Browser: Edge
- Version: 45

**Additional context**
It seems to occur in very specific situations only.

**Comment by rhymes** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by seangwright** [comment]
I'm seeing this same problem.

The change to the editor UI was nice in that it made it easier to switch between edit/preview mode and also upload images.

However this double scrollbar makes for a worse user experience because now I have to scroll the inner container before the outer container starts to scroll.

I'm not sure what causes this, but sometimes I have to scroll a bunch on an already fully scrolled inner container before the outer scroll takes effect.

My currently solution is to stop using my mouse scroll wheel when authoring on dev.to which is ... 😑

Instead I click and drag the outer scroll bar to move around in my post.

**Comment by Ridhwana** [comment]
@ludwiczakpawel do you have any insights on what can be causing this? I'm struggling to replicate it.

**Comment by ludwiczakpawel** [comment]
Hey, looks like it's caused by actually displaying scrollbar - macOS by default doesn't display scrollbars (there's a setting in System Preferences for that). Obviously it's a bug and I'm about to make a PR fixing this issue.

![image](https://user-images.githubusercontent.com/108287/83632542-c0211c80-a59f-11ea-84a9-71e1f7329cb6.png)

Thanks for reporting!
