### ISSUE TITLE
Emails with no opt out.

### ISSUE THREAD

**Issue by Danack** [thepracticaldev/dev.to#894]
Please stop sending emails that can't be opted out of.

Doing that is both a dick move, and against the law in most civilized countries.

**Comment by Zhao-Andy** [comment]
Hey @Danack, thanks for bringing this up. We definitely try to allow everyone to unsubscribe from all emails via [their settings](https://dev.to/settings/notifications), but if that's failing it might be a bug that we're not aware of. Which emails in particular are you getting?

I couldn't find an account with your GitHub username, but if you send us an email to yo@dev.to we're more than happy to unsubscribe you from all emails.

**Comment by Danack** [comment]
> Which emails in particular are you getting?

@Zhao-Andy This is a picture of the email - https://twitter.com/MrDanack/status/1050763883022036992

There should be an opt-out in the email. 

In particular - I don't want to confirm my account. I want to avoid creating it.

**Comment by Zhao-Andy** [comment]
You're getting that email because you've signed in previously before and already created an account: https://dev.to/mrdanack 

If you don't want an account, we can delete it for you. Let us know if it's okay to keep your existing comments under a ghost account, or if you'd like those deleted as well.

I don't think it's common for transactional "confirm your email address"-type emails to have opt-out links, but we can add that in. Thanks again for the heads up.

**Comment by benhalpern** [comment]
Hmmmm if you got this email without specifically triggering it, it is a bug. And I believe that bug is due to a job queue issue we're looking into. Sorry about the frustration.

I'll close the issue because we're currently working on the fix. Thanks for bringing more light to this and I hope there are no hard feelings about the mistake.
