### ISSUE TITLE
Publishing on V2 Beta needs confirmation 

### ISSUE THREAD

**Issue by joelnet** [thepracticaldev/dev.to#898]
**Is your feature request related to a problem? Please describe.**
I accidentally published an article meant to be in Draft.

**Describe the solution you'd like**
A confirmation dialog prior to publishing would prevent accidental publishes.

**Describe alternatives you've considered**
Moving the publish button away from the preview button could also help.

**Additional context**
n/a

**Comment by jessleenyc** [comment]
Hey @joelnet, since an author can always unpublish a post if they accidentally publish, we don't think it makes sense to add that additional step for the majority of the time where you do intend to publish. We tend to add confirmation dialogs for actions that are destructive, like deleting an article, because you wouldn't be able to retrieve it otherwise.

**Comment by joelnet** [comment]
Unpublishing is good also! At the time I created this ticket you could not unpublish in V2.
