### ISSUE TITLE
Problem with numbering in posts

### ISSUE THREAD

**Issue by urielbitton** [thepracticaldev/dev.to#9037]
The problem occurs when numbering text in a post. I number titles from 1 to 8 and when I publish the post the numbers all show 1's.

Here is a video recording of my phone where I attempted to edit the post that was ORIGINALLY CREATED ON MY LAPTOP AND NOT MY MOBILE.

https://www.dropbox.com/sh/kjv68g4sc64nq99/AAA1fmOppE548HfRxNZGlo_1a?dl=0

**Comment by jacobherrington** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by citizen428** [comment]
This is one of the subtleties of Markdown: numbered lists always start from 1 and increment from there, no matter what numbers you actually use. In your case, this becomes a problem because the code blocks between the numbered points interrupt the list, so each numbered element is seen as the start of a new list. To avoid this you have to indent the code blocks by 4 spaces. Let's see this in action.

*Code blocks not indented*

<img width="243" alt="Screen Shot 2020-07-01 at 11 46 21" src="https://user-images.githubusercontent.com/47985/86203988-96541900-bb90-11ea-80ba-c9dc63ed2dcc.png">

renders as

<img width="716" alt="Screen Shot 2020-07-01 at 11 46 29" src="https://user-images.githubusercontent.com/47985/86204005-9eac5400-bb90-11ea-99ce-54d7739c7303.png">

*Code blocks indented*

<img width="281" alt="Screen Shot 2020-07-01 at 11 46 07" src="https://user-images.githubusercontent.com/47985/86204017-a8ce5280-bb90-11ea-8c49-f4a3f5604e55.png">

renders as

<img width="704" alt="Screen Shot 2020-07-01 at 11 45 51" src="https://user-images.githubusercontent.com/47985/86204031-af5cca00-bb90-11ea-8c4d-cceec5b2be6d.png">

Please let us know if this resolves your problem so we can close this issue, thank you!

**Comment by urielbitton** [comment]
Ok thank you it does solve my issue.

On a side note: wouldn't it be more elegant to find a solution to avoid this problem altogether?



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by citizen428** [comment]
Glad this helped 😃 

> On a side note: wouldn't it be more elegant to find a solution to avoid this problem altogether?

This would require a custom Markdown parser that behaves differently from what people familiar with the format expect.
