### ISSUE TITLE
Need help in cofiguring Envfile: Especially TIMBER and SENDGRID

### ISSUE THREAD

**Issue by akhil-naidu** [thepracticaldev/dev.to#9264]
Hello @dev-community

I was able to have a **development instance**, but when I was trying to deploy it in Heroku I face errors. After grinding into the various issue sections I released something and I want to confirm it. If my assumptions are wrong please let me know it and hoping your guidance will keep me in the track and save me some time

- In order to have a working **development** Instance, there is no need for all API keys

- In order to have a working **production** instance, I need to have all the APIs, which are even mentioned as optional

Also, there are two variables in the ENVfile, in which I face maximum difficulties to fill up.

1. TIMBER: Do I need to use the **timber legacy API key**?
2. SENDGRID_USERNAME_ACCEL and SENDGRID_PASSWORD_ACCEL: What is **accel** and are these values equal to my **Username** and **password** of SendGrid respectively? or SENDGRIDs **API-id** and **API-key** respectively.

Thanks in advance.

**Comment by rhymes** [comment]
Hi @akhil-naidu 

I think you can skip Timber as we're moving to drop it, it is effectively optional since very recently:

https://github.com/thepracticaldev/dev.to/blob/ba82e72aa4f7db43615277e887a2ca7c5709c440/config/environments/production.rb#L110-L116

I'm unfamiliar with Sendgrid's configuration but since they pertain to the SMTP configuration I think it needs to be your username and password so that you can send email through it

**Comment by akhil-naidu** [comment]
@rhymes 

So, I can comment or remove the timber-related code in the production.rb file. It will not deter my production deployment.

**Comment by rhymes** [comment]
@akhil-naidu I think you can set `SEND_LOGS_TO_TIMBER` to `false` and it won't initialize

**Comment by akhil-naidu** [comment]
> @akhil-naidu I think you can set `SEND_LOGS_TO_TIMBER` to `false` and it won't initialize

Thankyou
