### ISSUE TITLE
YAML Errors for metadata aren't clear

### ISSUE THREAD

**Issue by good-idea** [thepracticaldev/dev.to#96]
# _BUG_
### Current Behavior

When there's a parsing error in a new post's metadata, the returned error doesn't offer any specifics or guidance.

### Expected Behavior

A more useful error message: "Title and description strings with special characters should be wrapped in quotes"

### Additional Info (steps to replicate, device/browser, helpful links)

Add a title or description that uses a colon `:` and is not wrapped in quotes.

### Screenshots
![image](https://user-images.githubusercontent.com/11514928/31149219-090abb56-a844-11e7-96a8-d553187b39b8.png)

**Comment by Zhao-Andy** [comment]
Thanks for the heads up, we'll take a look into it.

**Comment by rhymes** [comment]
Some info for whomever takes this on.

I can't reproduce this with the new editor:

![2018-10-12 8 09 43 pm](https://user-images.githubusercontent.com/146201/46886354-f6ee7000-ce5a-11e8-8b17-f003d68092aa.gif)

It still affects the old editor but only in the description field. Not in the title. You might want to see what's different about these two fields.

**Comment by Zhao-Andy** [comment]
@rhymes, ah that's because we wrap the title with quotes, but not the description: https://github.com/thepracticaldev/dev.to/blob/7c4396d5350dee8a8809e4a50650eb2c898e0109/app/labor/markdown_fixer.rb#L12-L33

I think we do it in the front end for the v1 editor, too. Can't think of the file off the top of my head.
