### ISSUE TITLE
Embedded comment date alignmemt

### ISSUE THREAD

**Issue by benhalpern** [thepracticaldev/dev.to#962]
When you post a comment within a comment, the date gets messed up. 

![](https://cl.ly/e430cfa111e8/Image%202018-10-19%20at%201.09.08%20PM.png)

PS -> Outside of this scopre, there is a bigger picture issue with regards to liquid tag css scoping in general, if anyone wants to start diving into that in general. These get posted in different contexts and sometimes render improperly via CSS or other issues with nesting etc.

**Comment by Link2Twenty** [comment]
There is a really gross hack around this, but I'm not 100% sure it's a good idea.

The problem is `.single-comment-node .details .comment-date` overides to earlier rule setting the `comment-date` styles.

So we can be more specific by saying this `comment-date` has to be a sibling of a social link.

This would get the desired result but it doesn't feel concrete enough.
`.single-comment-node .details [target=_blank] ~ .comment-date`

**Comment by maestromac** [comment]
not stale

**Comment by akshayymahajan** [comment]
@maestromac I would like to work on this issue..

**Comment by rhymes** [comment]
@akshayymahajan go for it ✌🏾️ and thanks!
