### ISSUE TITLE
Got Unexpected "Error 500" after the wrong url settings

### ISSUE THREAD

**Issue by bauripalash** [thepracticaldev/dev.to#999]
As expecting , There should be a 404 when we enter a wrong url.
On Dev.to everything works fine and as expected on wrong url we gets a amazing 404 page but if the url is behind the setting page it shows 500 Error.

Let me explain , if I go to <https://dev.to/settings/organization> i got expected page but if I accidentally go to <https://dev.to/settings/organizatio> , it would show error 500 , which is unexpected.

Every wrong url after <https://dev.to/settings/> shows error 505

**Comment by Zhao-Andy** [comment]
@bauripalash thanks for the heads up. This is because we're missing an `else` in our case statement here: https://github.com/thepracticaldev/dev.to/blob/9718bd64bfd8096fea120c405360cd71cfbe52bb/app/controllers/users_controller.rb#L137-L177

I think this would be a great candidate for TDDing if anyone wants to take it.

**Comment by fredplante** [comment]
Hi !
I would like to take it, it would be great for my first contribution to Dev.to

**Comment by Zhao-Andy** [comment]
Hey @fredplante, go for it!
